export { PlatformProvider } from "./platform-context";
export { usePlatform, useOptionalPlatform } from "./use-platform";
export {
  PathSelectionInProgressError,
  type LocationActionsCapability,
  type LocationTarget,
  type PathSelectionKind,
  type PlatformAdapter,
  type SaveTextFileOptions,
  type SelectPathOptions,
  type SelectSavePathOptions,
  type SurfaceBounds,
  type SurfaceCapability,
  type SurfaceOpenTarget,
  type SurfaceKind,
  type DownloadAction,
  type ResolveDownloadOutcome,
  type SurfaceEvent,
  type SurfaceRecord,
  type SurfaceState,
  type SurfaceTarget,
  type WindowControlsCapability,
  type WindowManagerOs,
  type WorktreeStorageCapability,
} from "./types";
