//! Endpoint declarations for the fileSystem generated-client namespace.

use crate::frontend::{
    FrontendEndpoint, FrontendHttpMethod, NO_PATH_PARAMS, PROJECT_PATH_PARAMS, TASK_PATH_PARAMS,
};
use ora_contracts::{
    FILE_SYSTEM_DIRECTORY_PATH, PROJECT_DIRECTORY_PATH, PROJECT_FILE_PATH, PROJECT_SEARCH_PATH,
    PROJECT_WATCH_PATH, WORKSPACE_DIRECTORY_PATH, WORKSPACE_FILE_PATH, WORKSPACE_SEARCH_PATH,
    WORKSPACE_WATCH_PATH,
};

const NAMESPACE: &str = "fileSystem";

pub(super) const ENDPOINTS: &[FrontendEndpoint] = &[
    FrontendEndpoint {
        operation_name: "listDirectory",
        namespace: NAMESPACE,
        member_name: "listDirectory",
        method: FrontendHttpMethod::Get,
        path_template: FILE_SYSTEM_DIRECTORY_PATH,
        request_type: "ListDirectoryRequest",
        response_type: "ListDirectoryResponse",
        path_params: NO_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "listWorkspaceDirectory",
        namespace: NAMESPACE,
        member_name: "listWorkspaceDirectory",

        method: FrontendHttpMethod::Post,
        path_template: WORKSPACE_DIRECTORY_PATH,
        request_type: "ListWorkspaceDirectoryRequest",
        response_type: "ListWorkspaceDirectoryResponse",
        path_params: TASK_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "readWorkspaceFile",
        namespace: NAMESPACE,
        member_name: "readWorkspaceFile",
        method: FrontendHttpMethod::Post,
        path_template: WORKSPACE_FILE_PATH,
        request_type: "ReadWorkspaceFileRequest",
        response_type: "ReadWorkspaceFileResponse",
        path_params: TASK_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "searchWorkspace",
        namespace: NAMESPACE,
        member_name: "searchWorkspace",
        method: FrontendHttpMethod::Post,
        path_template: WORKSPACE_SEARCH_PATH,
        request_type: "SearchWorkspaceRequest",
        response_type: "SearchWorkspaceResponse",
        path_params: TASK_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "watchWorkspace",
        namespace: NAMESPACE,
        member_name: "watchWorkspace",
        method: FrontendHttpMethod::Get,
        path_template: WORKSPACE_WATCH_PATH,
        request_type: "WatchWorkspaceRequest",
        response_type: "WorkspaceFileEventBatch",
        path_params: TASK_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "listProjectDirectory",
        namespace: NAMESPACE,
        member_name: "listProjectDirectory",
        method: FrontendHttpMethod::Post,
        path_template: PROJECT_DIRECTORY_PATH,
        request_type: "ListProjectDirectoryRequest",
        response_type: "ListProjectDirectoryResponse",
        path_params: PROJECT_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "readProjectFile",
        namespace: NAMESPACE,
        member_name: "readProjectFile",
        method: FrontendHttpMethod::Post,
        path_template: PROJECT_FILE_PATH,
        request_type: "ReadProjectFileRequest",
        response_type: "ReadProjectFileResponse",
        path_params: PROJECT_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "searchProject",
        namespace: NAMESPACE,
        member_name: "searchProject",
        method: FrontendHttpMethod::Post,
        path_template: PROJECT_SEARCH_PATH,
        request_type: "SearchProjectRequest",
        response_type: "SearchProjectResponse",
        path_params: PROJECT_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "watchProject",
        namespace: NAMESPACE,
        member_name: "watchProject",
        method: FrontendHttpMethod::Get,
        path_template: PROJECT_WATCH_PATH,
        request_type: "WatchProjectRequest",
        response_type: "WorkspaceFileEventBatch",
        path_params: PROJECT_PATH_PARAMS,
        has_json_body: false,
    },
];
