//! Endpoint declarations for the plugin generated-client namespace.

use crate::frontend::{FrontendEndpoint, FrontendResponseMode};

const NAMESPACE: &str = "plugin";

pub(super) const ENDPOINTS: &[FrontendEndpoint] = &[
    FrontendEndpoint {
        operation_name: "listAvailablePlugins",
        namespace: NAMESPACE,
        member_name: "listAvailable",
        request_type: "ListAvailablePluginsRequest",
        response_type: "ListAvailablePluginsResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "syncAvailablePlugins",
        namespace: NAMESPACE,
        member_name: "syncAvailable",
        request_type: "SyncAvailablePluginsRequest",
        response_type: "SyncAvailablePluginsResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "readPluginReadme",
        namespace: NAMESPACE,
        member_name: "readReadme",
        request_type: "ReadPluginReadmeRequest",
        response_type: "ReadPluginReadmeResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "listMarketplaceSources",
        namespace: NAMESPACE,
        member_name: "listSources",
        request_type: "ListMarketplaceSourcesRequest",
        response_type: "ListMarketplaceSourcesResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "addMarketplaceSource",
        namespace: NAMESPACE,
        member_name: "addSource",
        request_type: "AddMarketplaceSourceRequest",
        response_type: "AddMarketplaceSourceResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "deleteMarketplaceSource",
        namespace: NAMESPACE,
        member_name: "deleteSource",
        request_type: "DeleteMarketplaceSourceRequest",
        response_type: "DeleteMarketplaceSourceResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "updateMarketplaceSource",
        namespace: NAMESPACE,
        member_name: "updateSource",
        request_type: "UpdateMarketplaceSourceRequest",
        response_type: "UpdateMarketplaceSourceResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "listInstalledPlugins",
        namespace: NAMESPACE,
        member_name: "listInstalled",
        request_type: "ListInstalledPluginsRequest",
        response_type: "ListInstalledPluginsResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "getPluginConfiguration",
        namespace: NAMESPACE,
        member_name: "getConfiguration",
        request_type: "GetPluginConfigurationRequest",
        response_type: "GetPluginConfigurationResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "savePluginConfiguration",
        namespace: NAMESPACE,
        member_name: "saveConfiguration",
        request_type: "SavePluginConfigurationRequest",
        response_type: "SavePluginConfigurationResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "resetPluginConfiguration",
        namespace: NAMESPACE,
        member_name: "resetConfiguration",
        request_type: "ResetPluginConfigurationRequest",
        response_type: "ResetPluginConfigurationResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "scanPlugins",
        namespace: NAMESPACE,
        member_name: "scan",
        request_type: "ScanPluginsRequest",
        response_type: "ScanPluginsResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "activatePlugin",
        namespace: NAMESPACE,
        member_name: "activate",
        request_type: "ActivatePluginRequest",
        response_type: "ActivatePluginResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "stopPlugin",
        namespace: NAMESPACE,
        member_name: "stop",
        request_type: "StopPluginRequest",
        response_type: "StopPluginResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "uninstallPlugin",
        namespace: NAMESPACE,
        member_name: "uninstall",
        request_type: "UninstallPluginRequest",
        response_type: "UninstallPluginResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "installPlugin",
        namespace: NAMESPACE,
        member_name: "install",
        request_type: "InstallPluginRequest",
        response_type: "InstallPluginResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "updatePlugin",
        namespace: NAMESPACE,
        member_name: "update",
        request_type: "UpdatePluginRequest",
        response_type: "UpdatePluginResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "importPlugin",
        namespace: NAMESPACE,
        member_name: "import",
        request_type: "ImportPluginRequest",
        response_type: "ImportPluginResponse",
        response_mode: FrontendResponseMode::Unary,
    },
];
