//! Endpoint declarations for the repository generated-client namespace.

use crate::frontend::{
    FrontendEndpoint, FrontendHttpMethod, PROJECT_PATH_PARAMS, REPOSITORY_COMMIT_PATH_PARAMS,
};
use ora_contracts::{
    REPOSITORY_BRANCH_CHECKOUT_PATH, REPOSITORY_BRANCH_CREATE_PATH, REPOSITORY_COMMIT_CHANGES_PATH,
    REPOSITORY_COMMIT_DIFF_PATH, REPOSITORY_COMMIT_PATH, REPOSITORY_CONFLICT_RESOLVE_PATH,
    REPOSITORY_FETCH_PATH, REPOSITORY_PULL_PATH, REPOSITORY_PUSH_PATH, REPOSITORY_SNAPSHOT_PATH,
    REPOSITORY_STAGE_CHANGES_PATH, REPOSITORY_SYNC_PATH, REPOSITORY_UNSTAGE_CHANGES_PATH,
    REPOSITORY_WORKING_TREE_DIFF_PATH,
};

const NAMESPACE: &str = "repository";

pub(super) const ENDPOINTS: &[FrontendEndpoint] = &[
    FrontendEndpoint {
        operation_name: "getRepositorySnapshot",
        namespace: NAMESPACE,
        member_name: "getSnapshot",
        method: FrontendHttpMethod::Get,
        path_template: REPOSITORY_SNAPSHOT_PATH,
        request_type: "GetRepositorySnapshotRequest",
        response_type: "GetRepositorySnapshotResponse",
        path_params: PROJECT_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "getRepositoryCommit",
        namespace: NAMESPACE,
        member_name: "getCommit",
        method: FrontendHttpMethod::Get,
        path_template: REPOSITORY_COMMIT_PATH,
        request_type: "GetRepositoryCommitRequest",
        response_type: "GetRepositoryCommitResponse",
        path_params: REPOSITORY_COMMIT_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "getRepositoryCommitDiff",
        namespace: NAMESPACE,
        member_name: "getCommitDiff",
        method: FrontendHttpMethod::Get,
        path_template: REPOSITORY_COMMIT_DIFF_PATH,
        request_type: "GetRepositoryCommitDiffRequest",
        response_type: "GetRepositoryCommitDiffResponse",
        path_params: REPOSITORY_COMMIT_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "getRepositoryWorkingTreeDiff",
        namespace: NAMESPACE,
        member_name: "getWorkingTreeDiff",
        method: FrontendHttpMethod::Get,
        path_template: REPOSITORY_WORKING_TREE_DIFF_PATH,
        request_type: "GetRepositoryWorkingTreeDiffRequest",
        response_type: "GetRepositoryWorkingTreeDiffResponse",
        path_params: PROJECT_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "createRepositoryBranch",
        namespace: NAMESPACE,
        member_name: "createBranch",
        method: FrontendHttpMethod::Post,
        path_template: REPOSITORY_BRANCH_CREATE_PATH,
        request_type: "CreateRepositoryBranchRequest",
        response_type: "CreateRepositoryBranchResponse",
        path_params: PROJECT_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "checkoutRepositoryBranch",
        namespace: NAMESPACE,
        member_name: "checkoutBranch",
        method: FrontendHttpMethod::Post,
        path_template: REPOSITORY_BRANCH_CHECKOUT_PATH,
        request_type: "CheckoutRepositoryBranchRequest",
        response_type: "CheckoutRepositoryBranchResponse",
        path_params: PROJECT_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "fetchRepository",
        namespace: NAMESPACE,
        member_name: "fetch",
        method: FrontendHttpMethod::Post,
        path_template: REPOSITORY_FETCH_PATH,
        request_type: "FetchRepositoryRequest",
        response_type: "FetchRepositoryResponse",
        path_params: PROJECT_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "pullRepository",
        namespace: NAMESPACE,
        member_name: "pull",
        method: FrontendHttpMethod::Post,
        path_template: REPOSITORY_PULL_PATH,
        request_type: "PullRepositoryRequest",
        response_type: "PullRepositoryResponse",
        path_params: PROJECT_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "resolveRepositorySync",
        namespace: NAMESPACE,
        member_name: "resolveSync",
        method: FrontendHttpMethod::Post,
        path_template: REPOSITORY_SYNC_PATH,
        request_type: "ResolveRepositorySyncRequest",
        response_type: "ResolveRepositorySyncResponse",
        path_params: PROJECT_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "resolveRepositoryConflict",
        namespace: NAMESPACE,
        member_name: "resolveConflict",
        method: FrontendHttpMethod::Post,
        path_template: REPOSITORY_CONFLICT_RESOLVE_PATH,
        request_type: "ResolveRepositoryConflictRequest",
        response_type: "ResolveRepositoryConflictResponse",
        path_params: PROJECT_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "pushRepositoryBranch",
        namespace: NAMESPACE,
        member_name: "pushBranch",
        method: FrontendHttpMethod::Post,
        path_template: REPOSITORY_PUSH_PATH,
        request_type: "PushRepositoryBranchRequest",
        response_type: "PushRepositoryBranchResponse",
        path_params: PROJECT_PATH_PARAMS,
        has_json_body: false,
    },
    FrontendEndpoint {
        operation_name: "stageRepositoryChanges",
        namespace: NAMESPACE,
        member_name: "stageChanges",
        method: FrontendHttpMethod::Post,
        path_template: REPOSITORY_STAGE_CHANGES_PATH,
        request_type: "StageRepositoryChangesRequest",
        response_type: "StageRepositoryChangesResponse",
        path_params: PROJECT_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "unstageRepositoryChanges",
        namespace: NAMESPACE,
        member_name: "unstageChanges",
        method: FrontendHttpMethod::Post,
        path_template: REPOSITORY_UNSTAGE_CHANGES_PATH,
        request_type: "UnstageRepositoryChangesRequest",
        response_type: "UnstageRepositoryChangesResponse",
        path_params: PROJECT_PATH_PARAMS,
        has_json_body: true,
    },
    FrontendEndpoint {
        operation_name: "commitRepositoryChanges",
        namespace: NAMESPACE,
        member_name: "commitChanges",
        method: FrontendHttpMethod::Post,
        path_template: REPOSITORY_COMMIT_CHANGES_PATH,
        request_type: "CommitRepositoryChangesRequest",
        response_type: "CommitRepositoryChangesResponse",
        path_params: PROJECT_PATH_PARAMS,
        has_json_body: true,
    },
];
