//! Endpoint declarations for the session generated-client namespace.

use crate::frontend::{FrontendEndpoint, FrontendResponseMode};

const NAMESPACE: &str = "session";

pub(super) const ENDPOINTS: &[FrontendEndpoint] = &[
    FrontendEndpoint {
        operation_name: "startSession",
        namespace: NAMESPACE,
        member_name: "start",
        request_type: "StartSessionRequest",
        response_type: "StartSessionResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "setSessionConfig",
        namespace: NAMESPACE,
        member_name: "setConfig",
        request_type: "SetSessionConfigRequest",
        response_type: "SetSessionConfigResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "getSession",
        namespace: NAMESPACE,
        member_name: "get",
        request_type: "GetSessionRequest",
        response_type: "GetSessionResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "listSessions",
        namespace: NAMESPACE,
        member_name: "list",
        request_type: "ListSessionsRequest",
        response_type: "ListSessionsResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "loadSession",
        namespace: NAMESPACE,
        member_name: "load",
        request_type: "LoadSessionRequest",
        response_type: "LoadSessionEvent",
        response_mode: FrontendResponseMode::Stream,
    },
    FrontendEndpoint {
        operation_name: "promptSession",
        namespace: NAMESPACE,
        member_name: "prompt",
        request_type: "PromptSessionRequest",
        response_type: "PromptSessionEvent",
        response_mode: FrontendResponseMode::Stream,
    },
    FrontendEndpoint {
        operation_name: "respondToSessionPermission",
        namespace: NAMESPACE,
        member_name: "respondToPermission",
        request_type: "RespondToPermissionRequest",
        response_type: "RespondToPermissionResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "cancelSessionPrompt",
        namespace: NAMESPACE,
        member_name: "cancelPrompt",
        request_type: "CancelSessionPromptRequest",
        response_type: "CancelSessionPromptResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "stopSession",
        namespace: NAMESPACE,
        member_name: "stop",
        request_type: "StopSessionRequest",
        response_type: "StopSessionResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "switchSessionAgent",
        namespace: NAMESPACE,
        member_name: "switchAgent",
        request_type: "SwitchSessionAgentRequest",
        response_type: "SwitchSessionAgentResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "resumeSessionHistory",
        namespace: NAMESPACE,
        member_name: "resumeHistory",
        request_type: "ResumeSessionHistoryRequest",
        response_type: "ResumeSessionHistoryResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "deleteSession",
        namespace: NAMESPACE,
        member_name: "delete",
        request_type: "DeleteSessionRequest",
        response_type: "DeleteSessionResponse",
        response_mode: FrontendResponseMode::Unary,
    },
    FrontendEndpoint {
        operation_name: "renameSession",
        namespace: NAMESPACE,
        member_name: "rename",
        request_type: "RenameSessionRequest",
        response_type: "RenameSessionResponse",
        response_mode: FrontendResponseMode::Unary,
    },
];
