use crate::plugin_id::{PluginIdError, PluginIdSegment, validate_segment};
use serde::de::Error as _;
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::fmt::{self, Display, Formatter};

/// Maximum byte length of a namespace.
///
/// A namespace is the first directory level of three durable filesystem paths (the installed
/// package tree, the plugin's private data directory, and its configuration store), so its length
/// must be bounded by the type rather than by whatever URL it was derived from: self-hosted hosts
/// and deeply nested subgroups would otherwise let a path component grow without limit.
pub const MAX_PLUGIN_NAMESPACE_BYTES: usize = 33;

/// Byte budget of the readable slug prefix of a derived namespace.
const DERIVED_SLUG_BYTES: usize = 24;
/// Number of hex characters of the canonical-URL digest suffix.
const DERIVED_DIGEST_HEX: usize = 8;
/// Slug used when a source URL carries no readable repository segment at all.
const PLACEHOLDER_SLUG: &str = "marketplace";

/// Identifies the origin that first introduced a plugin into this installation.
///
/// The namespace is generated by the host, never read from a manifest: manifests are third-party
/// editable content, and a namespace decides which directories a package owns, which `skills`
/// rows it can clear, and which Effect Consumer identity it holds. Two values are reserved —
/// [`PluginNamespace::official`] for the default marketplace and [`PluginNamespace::local`] for
/// packages imported from a local archive — and every other namespace is derived from the
/// canonical URL of the marketplace source that published the plugin.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct PluginNamespace(String);

impl PluginNamespace {
    /// Namespace of the first-party marketplace.
    ///
    /// The default source short-circuits derivation purely for readability: `official/<name>`
    /// reads far better in install paths, logs, and error messages than a digest-suffixed slug,
    /// and the overwhelming majority of plugins come from it.
    pub const OFFICIAL: &'static str = "official";
    /// Namespace of packages imported from a local `.orax` archive.
    ///
    /// Unlike `official` this one is structurally necessary: a local archive has no source URL,
    /// so there is no derivation input and the package still needs a definite owner.
    pub const LOCAL: &'static str = "local";

    /// Returns the reserved namespace of the first-party marketplace.
    pub fn official() -> Self {
        Self(Self::OFFICIAL.to_owned())
    }

    /// Returns the reserved namespace of locally imported packages.
    pub fn local() -> Self {
        Self(Self::LOCAL.to_owned())
    }

    /// Parses one namespace from untrusted text, enforcing the single-path-segment grammar.
    pub fn parse(value: &str) -> Result<Self, PluginIdError> {
        validate_segment(value, PluginIdSegment::Namespace)?;
        Ok(Self(value.to_owned()))
    }

    /// Derives the namespace of a marketplace source from its canonical repository URL.
    ///
    /// The result is `<slug>.<digest>`: a readable prefix taken from the URL's last path segment,
    /// and the first four bytes of the canonical URL's SHA-256 rendered as eight hex characters.
    /// The two halves have separate jobs. The slug is lossy by construction — it folds illegal
    /// characters, collapses hyphens, and truncates — so it can collide, and nothing about
    /// identity may rest on it. The digest hashes the *whole* canonical URL, so two repositories
    /// that differ only in the parts the slug discarded (host, port, organization, subgroup
    /// nesting) still receive different namespaces.
    ///
    /// This function is a compatibility contract: one canonical URL must derive the same
    /// namespace on every platform and in every version, because the result is frozen into
    /// install paths the moment a plugin from that source lands on disk. Neither the digest
    /// length nor the slug rules may change once released.
    ///
    /// The mandatory `.<digest>` suffix is also what makes a reserved collision unrepresentable:
    /// `official` and `local` carry no `.`-separated digest, so no input can derive either.
    pub fn derive_from_canonical_url(canonical_url: &str) -> Self {
        let digest = &ora_utils::hash::sha256_hex(canonical_url.as_bytes())[..DERIVED_DIGEST_HEX];
        let slug = derive_slug(ora_utils::url::repository_url_last_segment(canonical_url));
        Self(format!("{slug}.{digest}"))
    }

    /// Returns the validated namespace spelling.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Reports whether this namespace is one the host reserves for itself.
    ///
    /// Reserved namespaces are never derived, so a source URL can never claim the first-party
    /// marketplace's identity or the local-import identity.
    pub fn is_reserved(&self) -> bool {
        matches!(self.0.as_str(), Self::OFFICIAL | Self::LOCAL)
    }
}

impl Display for PluginNamespace {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl AsRef<str> for PluginNamespace {
    fn as_ref(&self) -> &str {
        &self.0
    }
}

impl From<PluginNamespace> for String {
    fn from(namespace: PluginNamespace) -> Self {
        namespace.0
    }
}

impl Serialize for PluginNamespace {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(&self.0)
    }
}

impl<'de> Deserialize<'de> for PluginNamespace {
    /// Deserializes a namespace, rejecting any spelling that is not a legal path segment.
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Self::parse(&value).map_err(D::Error::custom)
    }
}

/// Folds one raw repository name into the readable prefix of a derived namespace.
///
/// Everything outside `[a-z0-9-]` becomes `-`, runs of `-` collapse, the ends are trimmed, and
/// the remainder is truncated to [`DERIVED_SLUG_BYTES`]. Every step is lossy on purpose: this is
/// the human-readable half only, and uniqueness is the digest's job.
fn derive_slug(last_segment: &str) -> String {
    let mut slug = String::with_capacity(last_segment.len());
    for character in last_segment.chars() {
        let folded = if character.is_ascii_lowercase() || character.is_ascii_digit() {
            character
        } else {
            '-'
        };
        if folded == '-' && slug.ends_with('-') {
            continue;
        }
        slug.push(folded);
    }
    let trimmed = slug.trim_matches('-');
    if trimmed.is_empty() {
        return PLACEHOLDER_SLUG.to_owned();
    }
    // The folded alphabet is ASCII, so a byte budget and a character budget are the same bound.
    trimmed[..trimmed.len().min(DERIVED_SLUG_BYTES)].to_owned()
}

#[cfg(test)]
mod tests {
    use super::{MAX_PLUGIN_NAMESPACE_BYTES, PluginNamespace};
    use crate::plugin_id::{PluginIdError, PluginIdSegment};
    use ora_utils::url::canonical_repository_url;
    use pretty_assertions::assert_eq;

    /// Verifies the published derivation example, so the compatibility contract is pinned to a
    /// literal rather than to whatever the current implementation happens to produce.
    #[test]
    fn derives_the_documented_namespace() {
        let canonical = canonical_repository_url("https://GitHub.com/Acme/Awesome-Plugins.git/");

        assert_eq!(
            (
                canonical.clone(),
                PluginNamespace::derive_from_canonical_url(&canonical)
                    .as_str()
                    .to_owned(),
            ),
            (
                "https://github.com/acme/awesome-plugins".to_string(),
                DOCUMENTED_NAMESPACE.to_string(),
            ),
        );
    }

    /// Verifies equivalent URL spellings derive one namespace while repositories that differ only
    /// in the parts the slug discards still derive different ones.
    #[test]
    fn derives_per_canonical_url_not_per_spelling() {
        let derive = |url: &str| {
            PluginNamespace::derive_from_canonical_url(&canonical_repository_url(url))
                .as_str()
                .to_owned()
        };
        let canonical = derive("https://github.com/acme/plugins");

        assert_eq!(
            [
                derive("https://GitHub.com/Acme/Plugins"),
                derive("https://github.com/acme/plugins.git"),
                derive("https://github.com:443/acme/plugins/"),
                derive("https://token@github.com/acme/plugins.git/"),
            ],
            [
                canonical.clone(),
                canonical.clone(),
                canonical.clone(),
                canonical.clone(),
            ],
        );
        // Same repository name, different organization and different host: the slug halves match
        // and only the digest keeps them apart.
        assert_ne!(derive("https://github.com/other/plugins"), canonical);
        assert_ne!(derive("https://gitlab.com/acme/plugins"), canonical);
    }

    /// Verifies every derived namespace is a legal, bounded, single path segment regardless of
    /// how hostile the source URL's repository name is.
    #[test]
    fn always_derives_a_legal_bounded_segment() {
        let urls = [
            "https://github.com/ora-space/desktop",
            "https://dev.azure.com/contoso/analytics/_git/data-pipeline",
            "https://gitlab.com/acme/platform/tools/orax-registry",
            "https://git.example.com:8443/scm/infra/very-long-repository-name-for-tooling",
            "https://git.example.com/acme/UPPER_Case__Repo",
            "https://git.example.com/acme/-/-/-",
            "https://git.example.com",
        ];
        for url in urls {
            let canonical = canonical_repository_url(url);
            let namespace = PluginNamespace::derive_from_canonical_url(&canonical);
            assert_eq!(
                (
                    PluginNamespace::parse(namespace.as_str()).as_ref(),
                    namespace.as_str().len() <= MAX_PLUGIN_NAMESPACE_BYTES,
                    namespace.is_reserved(),
                ),
                (Ok(&namespace), true, false),
                "{url}",
            );
        }
    }

    /// Verifies the readable half is taken from the repository segment and truncated, and that a
    /// URL with no repository segment still derives a usable placeholder slug.
    #[test]
    fn derives_the_readable_slug_from_the_repository_segment() {
        let slug_of = |url: &str| {
            PluginNamespace::derive_from_canonical_url(&canonical_repository_url(url))
                .as_str()
                .rsplit_once('.')
                .map(|(slug, _digest)| slug.to_owned())
                .unwrap_or_default()
        };

        assert_eq!(
            [
                slug_of("https://github.com/ora-space/desktop"),
                slug_of("https://dev.azure.com/contoso/analytics/_git/data-pipeline"),
                slug_of("https://gitlab.com/acme/platform/tools/orax-registry"),
                slug_of(
                    "https://git.example.com:8443/scm/infra/very-long-repository-name-for-tooling"
                ),
                slug_of("https://git.example.com/acme/UPPER_Case__Repo"),
                slug_of("https://git.example.com"),
            ],
            [
                "desktop".to_string(),
                "data-pipeline".to_string(),
                "orax-registry".to_string(),
                "very-long-repository-nam".to_string(),
                "upper-case-repo".to_string(),
                "marketplace".to_string(),
            ],
        );
    }

    /// Verifies a source URL cannot derive either reserved namespace, including when the
    /// repository is literally named after one.
    #[test]
    fn never_derives_a_reserved_namespace() {
        let derived = [
            "https://github.com/acme/official",
            "https://github.com/acme/local",
            "https://official",
            "https://local/local/local",
        ]
        .map(|url| PluginNamespace::derive_from_canonical_url(&canonical_repository_url(url)));

        assert_eq!(
            (
                derived
                    .iter()
                    .map(PluginNamespace::is_reserved)
                    .collect::<Vec<_>>(),
                PluginNamespace::official().is_reserved(),
                PluginNamespace::local().is_reserved(),
            ),
            (vec![false; derived.len()], true, true),
        );
    }

    /// Verifies parsing rejects anything that is not a single, bounded, lowercase path segment.
    #[test]
    fn rejects_namespaces_that_are_not_legal_path_segments() {
        let too_long = "a".repeat(MAX_PLUGIN_NAMESPACE_BYTES + 1);
        let longest_allowed = "a".repeat(MAX_PLUGIN_NAMESPACE_BYTES);
        let cases = [
            (
                "",
                Err(PluginIdError::EmptySegment {
                    segment: PluginIdSegment::Namespace,
                }),
            ),
            (
                "Official",
                Err(PluginIdError::InvalidCharacter {
                    segment: PluginIdSegment::Namespace,
                    character: 'O',
                }),
            ),
            (
                "acme/plugins",
                Err(PluginIdError::InvalidCharacter {
                    segment: PluginIdSegment::Namespace,
                    character: '/',
                }),
            ),
            (
                "..",
                Err(PluginIdError::RelativeSegment {
                    segment: PluginIdSegment::Namespace,
                }),
            ),
            (
                ".",
                Err(PluginIdError::RelativeSegment {
                    segment: PluginIdSegment::Namespace,
                }),
            ),
            (
                too_long.as_str(),
                Err(PluginIdError::SegmentTooLong {
                    segment: PluginIdSegment::Namespace,
                    max_bytes: MAX_PLUGIN_NAMESPACE_BYTES,
                    actual_bytes: MAX_PLUGIN_NAMESPACE_BYTES + 1,
                }),
            ),
            (
                longest_allowed.as_str(),
                PluginNamespace::parse(&longest_allowed),
            ),
        ];
        for (input, expected) in cases {
            assert_eq!(PluginNamespace::parse(input), expected, "{input:?}");
        }
    }

    /// The namespace the documented derivation example must produce forever.
    const DOCUMENTED_NAMESPACE: &str = "awesome-plugins.2aa64f48";
}
