[package]
name = "ora-skill-package"
version.workspace = true
edition.workspace = true

[lib]
name = "ora_skill_package"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
ora-domain = { workspace = true }
ora-utils = { workspace = true, features = ["archive"] }
serde_yaml = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
