// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
import { endpoints, type EndpointOperation, type EndpointPathParam, type EndpointQueryParam, type RequestByOperation, type ResponseByOperation } from "./endpoints.js";
import type { ContractTransport, ContractTransportRequest } from "./transport.js";

type ClientRequestShape = object;

type ClientOperation<Operation extends EndpointOperation> = (
  request: RequestByOperation[Operation],
) => Promise<ResponseByOperation[Operation]>;

export type ContractsClient = {
  project: {
    create: ClientOperation<"createProject">;
    get: ClientOperation<"getProject">;
    list: ClientOperation<"listProjects">;
    update: ClientOperation<"updateProject">;
    delete: ClientOperation<"deleteProject">;
  };
  projectWorkContext: {
    open: ClientOperation<"openProjectWorkContext">;
    renew: ClientOperation<"renewProjectWorkContext">;
  };
  task: {
    create: ClientOperation<"createTask">;
    get: ClientOperation<"getTask">;
    list: ClientOperation<"listTasks">;
    update: ClientOperation<"updateTask">;
    delete: ClientOperation<"deleteTask">;
  };
  session: {
    create: ClientOperation<"createSession">;
    get: ClientOperation<"getSession">;
    list: ClientOperation<"listSessions">;
    update: ClientOperation<"updateSession">;
    delete: ClientOperation<"deleteSession">;
  };
  skill: {
    create: ClientOperation<"createSkill">;
    get: ClientOperation<"getSkill">;
    list: ClientOperation<"listSkills">;
    update: ClientOperation<"updateSkill">;
    delete: ClientOperation<"deleteSkill">;
  };
  agent: {
    create: ClientOperation<"createAgent">;
    get: ClientOperation<"getAgent">;
    list: ClientOperation<"listAgents">;
    update: ClientOperation<"updateAgent">;
    delete: ClientOperation<"deleteAgent">;
  };
  fileSystem: {
    listDirectory: ClientOperation<"listDirectory">;
  };
};

export function createContractsClient(transport: ContractTransport): ContractsClient {
  return {
    project: {
      create: (request) => executeOperation("createProject", request, transport),
      get: (request) => executeOperation("getProject", request, transport),
      list: (request) => executeOperation("listProjects", request, transport),
      update: (request) => executeOperation("updateProject", request, transport),
      delete: (request) => executeOperation("deleteProject", request, transport),
    },
    projectWorkContext: {
      open: (request) => executeOperation("openProjectWorkContext", request, transport),
      renew: (request) => executeOperation("renewProjectWorkContext", request, transport),
    },
    task: {
      create: (request) => executeOperation("createTask", request, transport),
      get: (request) => executeOperation("getTask", request, transport),
      list: (request) => executeOperation("listTasks", request, transport),
      update: (request) => executeOperation("updateTask", request, transport),
      delete: (request) => executeOperation("deleteTask", request, transport),
    },
    session: {
      create: (request) => executeOperation("createSession", request, transport),
      get: (request) => executeOperation("getSession", request, transport),
      list: (request) => executeOperation("listSessions", request, transport),
      update: (request) => executeOperation("updateSession", request, transport),
      delete: (request) => executeOperation("deleteSession", request, transport),
    },
    skill: {
      create: (request) => executeOperation("createSkill", request, transport),
      get: (request) => executeOperation("getSkill", request, transport),
      list: (request) => executeOperation("listSkills", request, transport),
      update: (request) => executeOperation("updateSkill", request, transport),
      delete: (request) => executeOperation("deleteSkill", request, transport),
    },
    agent: {
      create: (request) => executeOperation("createAgent", request, transport),
      get: (request) => executeOperation("getAgent", request, transport),
      list: (request) => executeOperation("listAgents", request, transport),
      update: (request) => executeOperation("updateAgent", request, transport),
      delete: (request) => executeOperation("deleteAgent", request, transport),
    },
    fileSystem: {
      listDirectory: (request) => executeOperation("listDirectory", request, transport),
    },
  };
}

async function executeOperation<Operation extends EndpointOperation>(
  operation: Operation,
  request: RequestByOperation[Operation],
  transport: ContractTransport,
): Promise<ResponseByOperation[Operation]> {
  const endpoint = endpoints[operation];
  const path = buildPath(endpoint.pathTemplate, endpoint.pathParams, endpoint.queryParams, request as ClientRequestShape);
  const body = buildJsonBody(endpoint.pathParams, endpoint.queryParams, endpoint.hasJsonBody, request as ClientRequestShape);
  const transportRequest: ContractTransportRequest = {
    operationName: endpoint.operationName,
    method: endpoint.method,
    path,
    body,
    headers: buildHeaders(endpoint.hasJsonBody),
  };

  return transport.send<ResponseByOperation[Operation]>(transportRequest);
}

function buildPath(
  pathTemplate: string,
  pathParams: readonly EndpointPathParam[],
  queryParams: readonly EndpointQueryParam[],
  request: ClientRequestShape,
): string {
  const requestRecord = request as Record<string, unknown>;
  let path = pathTemplate;

  for (const pathParam of pathParams) {
    const value = requestRecord[pathParam.wireName];

    if (value === undefined || value === null) {
      throw new Error(`missing path parameter ${pathParam.wireName}`);
    }

    path = path.replace(`{${pathParam.wireName}}`, encodeURIComponent(String(value)));
  }

  const query = new URLSearchParams();

  for (const queryParam of queryParams) {
    const value = requestRecord[queryParam.wireName];

    if (value !== undefined && value !== null) {
      query.append(queryParam.wireName, String(value));
    }
  }

  const queryString = query.toString();
  return queryString === "" ? path : `${path}?${queryString}`;
}

function buildJsonBody(
  pathParams: readonly EndpointPathParam[],
  queryParams: readonly EndpointQueryParam[],
  hasJsonBody: boolean,
  request: ClientRequestShape,
): Record<string, unknown> | undefined {
  if (!hasJsonBody) {
    return undefined;
  }

  const requestRecord = request as Record<string, unknown>;
  const pathParamNames = new Set(pathParams.map((pathParam) => pathParam.wireName));

  const queryParamNames = new Set(queryParams.map((queryParam) => queryParam.wireName));

  return Object.fromEntries(
    Object.entries(requestRecord).filter(
      ([fieldName]) => !pathParamNames.has(fieldName) && !queryParamNames.has(fieldName),
    ),
  );
}

function buildHeaders(hasJsonBody: boolean): Record<string, string> {
  if (!hasJsonBody) {
    return {};
  }

  return {
    "content-type": "application/json",
  };
}
