// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One stable item of intent selecting an exact immutable Effect Revision.
 */
export type DesiredEffectDto = {
  id: string;
  revisionId: string;
  parameters: EffectParametersDto;
  audience: EffectTargetSelectorDto;
};

/**
 * Transport projection of one current structured Effect Condition.
 */
export type EffectConditionDto = {
  id: string;
  ownerKind: string;
  ownerId: string;
  subjectKind: string;
  subjectId: string;
  code: string;
  impact: EffectConditionImpactDto;
  retry: EffectConditionRetryDto;
  generation: bigint | null;
  message: string;
  firstObservedAt: bigint;
  lastObservedAt: bigint;
};

/**
 * Whether a current Condition blocks its owner's watermark progression.
 */
export type EffectConditionImpactDto = "blocking" | "non_blocking";

/**
 * Stable retry classification without exposing internal scheduler parameters.
 */
export type EffectConditionRetryDto = "on_change" | "backoff" | "manual";

/**
 * One stable Consumer identity used by an Effect Target selector.
 */
export type EffectConsumerRefDto = { kind: string; stableKey: string };

/**
 * Closed transport representation of validated kind-specific Effect parameters.
 */
export type EffectParametersDto = { "kind": "skill" };

/**
 * One exact Effect protocol version required from a Consumer Revision.
 */
export type EffectProtocolRequirementDto = { kind: string; version: number };

/**
 * Public projection of one complete Workspace Effect Scope generation.
 */
export type EffectStateDto = {
  workspaceId: string;
  generation: number;
  effects: Array<DesiredEffectDto>;
};

/**
 * Explicit inclusion mode for a Desired Effect's Target audience.
 */
export type EffectTargetInclusionDto = { "kind": "all_eligible" } | {
  "kind": "only";
  "consumers": Array<EffectConsumerRefDto>;
};

/**
 * Generic Target convergence position without Consumer-specific runtime phases.
 */
export type EffectTargetPhaseDto =
  | "pending"
  | "planning"
  | "coordinating"
  | "applying"
  | "verifying"
  | "activating"
  | "current"
  | "current_with_issues"
  | "retiring"
  | "recovery_required";

/**
 * Complete capability and identity selector for one Desired Effect.
 */
export type EffectTargetSelectorDto = {
  requiredProtocols: Array<EffectProtocolRequirementDto>;
  requiredMaterializationContracts: Array<string>;
  include: EffectTargetInclusionDto;
  exclude: Array<EffectConsumerRefDto>;
};

/**
 * Transaction-consistent persisted Target status and its current Conditions.
 */
export type EffectTargetStatusDto = {
  targetId: string;
  desiredGeneration: number;
  observedGeneration: number;
  appliedGeneration: number;
  readyGeneration: number;
  phase: EffectTargetPhaseDto;
  statusVersion: number;
  recoveryOperationId: string | null;
  updatedAt: bigint;
  conditions: Array<EffectConditionDto>;
};

export type GetEffectStateRequest = { workspaceId: string };

export type GetEffectStateResponse = { state: EffectStateDto };

export type GetEffectTargetStatusRequest = {
  "selector": "target";
  targetId: string;
} | {
  "selector": "workspace_agent";
  workspaceId: string;
  agentPluginId: string;
};

export type GetEffectTargetStatusResponse = {
  status: EffectTargetStatusDto | null;
};

/**
 * Complete replacement request using optimistic generation compare-and-swap.
 */
export type ReplaceEffectStateRequest = {
  workspaceId: string;
  expectedGeneration: number;
  effects: Array<DesiredEffectDto>;
};

export type ReplaceEffectStateResponse = {
  state: EffectStateDto;
  changed: boolean;
};

/**
 * Explicit retry only wakes Target reconciliation; it never mutates Desired State.
 */
export type RetryEffectTargetRequest = { targetId: string };

export type RetryEffectTargetResponse = { requested: boolean };
