// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exact catalog-backed Skill state supplied as part of a complete desired replacement.
 */
export type DesiredSkillStateDto = {
  sourceKind: EffectSourceKind;
  namespace: string;
  name: string;
  version: string;
  skillMdDigest: string;
};

/**
 * Transport projection of a structured current Effect condition.
 */
export type EffectConditionDto = {
  subjectKind: string;
  subjectId: string;
  reason: string;
  message: string;
  firstOccurredAt: bigint;
  lastOccurredAt: bigint;
  failedGeneration: number;
  retryPolicy: EffectRetryPolicy;
};

/**
 * Retry behavior derived from a condition's stable reason.
 */
export type EffectRetryPolicy = "on_change" | "backoff" | "manual";

/**
 * Catalog owner of one desired Skill selection.
 */
export type EffectSourceKind = "local" | "plugin";

/**
 * Stable reconcile phases without embedding a blocking reason in the phase itself.
 */
export type EffectSurfacePhase =
  | "pending"
  | "waiting_for_idle"
  | "quiescing"
  | "applying"
  | "resuming"
  | "current"
  | "degraded"
  | "retiring"
  | "recovery_required";

/**
 * Transaction-consistent persisted surface status snapshot.
 */
export type EffectSurfaceStatusDto = {
  workspaceId: string;
  surfaceKey: string;
  desiredGeneration: number;
  observedGeneration: number;
  appliedGeneration: number;
  phase: EffectSurfacePhase;
  revision: number;
  updatedAt: bigint;
  conditions: Array<EffectConditionDto>;
};

export type GetEffectSurfaceStatusRequest = {
  workspaceId: string;
  surfaceKey: string;
};

export type GetEffectSurfaceStatusResponse = {
  status: EffectSurfaceStatusDto | null;
};

export type GetWorkspaceEffectRequest = { workspaceId: string };

export type GetWorkspaceEffectResponse = { effect: WorkspaceEffectDto };

/**
 * Full replacement request using optimistic generation compare-and-swap.
 */
export type ReplaceWorkspaceEffectRequest = {
  workspaceId: string;
  expectedGeneration: number;
  skills: Array<DesiredSkillStateDto>;
};

export type ReplaceWorkspaceEffectResponse = {
  effect: WorkspaceEffectDto;
  changed: boolean;
};

/**
 * Explicit retry only wakes reconciliation; it never mutates Desired or bypasses conflicts.
 */
export type RetryEffectSurfaceRequest = {
  workspaceId: string;
  surfaceKey: string;
};

export type RetryEffectSurfaceResponse = { requested: boolean };

/**
 * Public projection of one complete Workspace desired generation.
 */
export type WorkspaceEffectDto = {
  workspaceId: string;
  generation: number;
  skills: Array<DesiredSkillStateDto>;
};
