// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
import type { CreateAgentRequest, CreateAgentResponse, DeleteAgentRequest, DeleteAgentResponse, GetAgentRequest, GetAgentResponse, ListAgentsRequest, ListAgentsResponse, UpdateAgentRequest, UpdateAgentResponse } from "./agent.js";
import type { CreateProjectRequest, CreateProjectResponse, DeleteProjectRequest, DeleteProjectResponse, GetProjectRequest, GetProjectResponse, ListProjectsRequest, ListProjectsResponse, UpdateProjectRequest, UpdateProjectResponse } from "./project.js";
import type { OpenProjectWorkContextRequest, OpenProjectWorkContextResponse, RenewProjectWorkContextRequest, RenewProjectWorkContextResponse } from "./project-work-context.js";
import type { CreateSessionRequest, CreateSessionResponse, DeleteSessionRequest, DeleteSessionResponse, GetSessionRequest, GetSessionResponse, ListSessionsRequest, ListSessionsResponse, UpdateSessionRequest, UpdateSessionResponse } from "./session.js";
import type { CreateSkillRequest, CreateSkillResponse, DeleteSkillRequest, DeleteSkillResponse, GetSkillRequest, GetSkillResponse, ListSkillsRequest, ListSkillsResponse, UpdateSkillRequest, UpdateSkillResponse } from "./skill.js";
import type { CreateTaskRequest, CreateTaskResponse, DeleteTaskRequest, DeleteTaskResponse, GetTaskRequest, GetTaskResponse, ListTasksRequest, ListTasksResponse, UpdateTaskRequest, UpdateTaskResponse } from "./task.js";
import type { HttpMethod } from "./transport.js";

export type EndpointPathParam = {
  rustFieldName: string;
  wireName: string;
};

export type FrontendEndpointDefinition = {
  operationName: string;
  namespace: string;
  memberName: string;
  method: HttpMethod;
  pathTemplate: string;
  requestType: string;
  responseType: string;
  pathParams: readonly EndpointPathParam[];
  hasJsonBody: boolean;
};

export type RequestByOperation = {
  createProject: CreateProjectRequest;
  getProject: GetProjectRequest;
  listProjects: ListProjectsRequest;
  updateProject: UpdateProjectRequest;
  deleteProject: DeleteProjectRequest;
  openProjectWorkContext: OpenProjectWorkContextRequest;
  renewProjectWorkContext: RenewProjectWorkContextRequest;
  createTask: CreateTaskRequest;
  getTask: GetTaskRequest;
  listTasks: ListTasksRequest;
  updateTask: UpdateTaskRequest;
  deleteTask: DeleteTaskRequest;
  createSession: CreateSessionRequest;
  getSession: GetSessionRequest;
  listSessions: ListSessionsRequest;
  updateSession: UpdateSessionRequest;
  deleteSession: DeleteSessionRequest;
  createSkill: CreateSkillRequest;
  getSkill: GetSkillRequest;
  listSkills: ListSkillsRequest;
  updateSkill: UpdateSkillRequest;
  deleteSkill: DeleteSkillRequest;
  createAgent: CreateAgentRequest;
  getAgent: GetAgentRequest;
  listAgents: ListAgentsRequest;
  updateAgent: UpdateAgentRequest;
  deleteAgent: DeleteAgentRequest;
};

export type ResponseByOperation = {
  createProject: CreateProjectResponse;
  getProject: GetProjectResponse;
  listProjects: ListProjectsResponse;
  updateProject: UpdateProjectResponse;
  deleteProject: DeleteProjectResponse;
  openProjectWorkContext: OpenProjectWorkContextResponse;
  renewProjectWorkContext: RenewProjectWorkContextResponse;
  createTask: CreateTaskResponse;
  getTask: GetTaskResponse;
  listTasks: ListTasksResponse;
  updateTask: UpdateTaskResponse;
  deleteTask: DeleteTaskResponse;
  createSession: CreateSessionResponse;
  getSession: GetSessionResponse;
  listSessions: ListSessionsResponse;
  updateSession: UpdateSessionResponse;
  deleteSession: DeleteSessionResponse;
  createSkill: CreateSkillResponse;
  getSkill: GetSkillResponse;
  listSkills: ListSkillsResponse;
  updateSkill: UpdateSkillResponse;
  deleteSkill: DeleteSkillResponse;
  createAgent: CreateAgentResponse;
  getAgent: GetAgentResponse;
  listAgents: ListAgentsResponse;
  updateAgent: UpdateAgentResponse;
  deleteAgent: DeleteAgentResponse;
};

export type EndpointOperation = keyof RequestByOperation;

export const endpoints = {
  createProject: {
    operationName: "createProject",
    namespace: "project",
    memberName: "create",
    method: "POST",
    pathTemplate: "/api/projects",
    requestType: "CreateProjectRequest",
    responseType: "CreateProjectResponse",
    pathParams: [],
    hasJsonBody: true,
  },
  getProject: {
    operationName: "getProject",
    namespace: "project",
    memberName: "get",
    method: "GET",
    pathTemplate: "/api/projects/{projectId}",
    requestType: "GetProjectRequest",
    responseType: "GetProjectResponse",
    pathParams: [{ rustFieldName: "project_id", wireName: "projectId" }],
    hasJsonBody: false,
  },
  listProjects: {
    operationName: "listProjects",
    namespace: "project",
    memberName: "list",
    method: "GET",
    pathTemplate: "/api/projects",
    requestType: "ListProjectsRequest",
    responseType: "ListProjectsResponse",
    pathParams: [],
    hasJsonBody: false,
  },
  updateProject: {
    operationName: "updateProject",
    namespace: "project",
    memberName: "update",
    method: "PUT",
    pathTemplate: "/api/projects/{projectId}",
    requestType: "UpdateProjectRequest",
    responseType: "UpdateProjectResponse",
    pathParams: [{ rustFieldName: "project_id", wireName: "projectId" }],
    hasJsonBody: true,
  },
  deleteProject: {
    operationName: "deleteProject",
    namespace: "project",
    memberName: "delete",
    method: "DELETE",
    pathTemplate: "/api/projects/{projectId}",
    requestType: "DeleteProjectRequest",
    responseType: "DeleteProjectResponse",
    pathParams: [{ rustFieldName: "project_id", wireName: "projectId" }],
    hasJsonBody: false,
  },
  openProjectWorkContext: {
    operationName: "openProjectWorkContext",
    namespace: "projectWorkContext",
    memberName: "open",
    method: "POST",
    pathTemplate: "/api/project-work-contexts/open",
    requestType: "OpenProjectWorkContextRequest",
    responseType: "OpenProjectWorkContextResponse",
    pathParams: [],
    hasJsonBody: true,
  },
  renewProjectWorkContext: {
    operationName: "renewProjectWorkContext",
    namespace: "projectWorkContext",
    memberName: "renew",
    method: "POST",
    pathTemplate: "/api/project-work-contexts/renew",
    requestType: "RenewProjectWorkContextRequest",
    responseType: "RenewProjectWorkContextResponse",
    pathParams: [],
    hasJsonBody: true,
  },
  createTask: {
    operationName: "createTask",
    namespace: "task",
    memberName: "create",
    method: "POST",
    pathTemplate: "/api/tasks",
    requestType: "CreateTaskRequest",
    responseType: "CreateTaskResponse",
    pathParams: [],
    hasJsonBody: true,
  },
  getTask: {
    operationName: "getTask",
    namespace: "task",
    memberName: "get",
    method: "GET",
    pathTemplate: "/api/tasks/{taskId}",
    requestType: "GetTaskRequest",
    responseType: "GetTaskResponse",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    hasJsonBody: false,
  },
  listTasks: {
    operationName: "listTasks",
    namespace: "task",
    memberName: "list",
    method: "GET",
    pathTemplate: "/api/tasks",
    requestType: "ListTasksRequest",
    responseType: "ListTasksResponse",
    pathParams: [],
    hasJsonBody: false,
  },
  updateTask: {
    operationName: "updateTask",
    namespace: "task",
    memberName: "update",
    method: "PUT",
    pathTemplate: "/api/tasks/{taskId}",
    requestType: "UpdateTaskRequest",
    responseType: "UpdateTaskResponse",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    hasJsonBody: true,
  },
  deleteTask: {
    operationName: "deleteTask",
    namespace: "task",
    memberName: "delete",
    method: "DELETE",
    pathTemplate: "/api/tasks/{taskId}",
    requestType: "DeleteTaskRequest",
    responseType: "DeleteTaskResponse",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    hasJsonBody: false,
  },
  createSession: {
    operationName: "createSession",
    namespace: "session",
    memberName: "create",
    method: "POST",
    pathTemplate: "/api/sessions",
    requestType: "CreateSessionRequest",
    responseType: "CreateSessionResponse",
    pathParams: [],
    hasJsonBody: true,
  },
  getSession: {
    operationName: "getSession",
    namespace: "session",
    memberName: "get",
    method: "GET",
    pathTemplate: "/api/sessions/{sessionId}",
    requestType: "GetSessionRequest",
    responseType: "GetSessionResponse",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    hasJsonBody: false,
  },
  listSessions: {
    operationName: "listSessions",
    namespace: "session",
    memberName: "list",
    method: "GET",
    pathTemplate: "/api/sessions",
    requestType: "ListSessionsRequest",
    responseType: "ListSessionsResponse",
    pathParams: [],
    hasJsonBody: false,
  },
  updateSession: {
    operationName: "updateSession",
    namespace: "session",
    memberName: "update",
    method: "PUT",
    pathTemplate: "/api/sessions/{sessionId}",
    requestType: "UpdateSessionRequest",
    responseType: "UpdateSessionResponse",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    hasJsonBody: true,
  },
  deleteSession: {
    operationName: "deleteSession",
    namespace: "session",
    memberName: "delete",
    method: "DELETE",
    pathTemplate: "/api/sessions/{sessionId}",
    requestType: "DeleteSessionRequest",
    responseType: "DeleteSessionResponse",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    hasJsonBody: false,
  },
  createSkill: {
    operationName: "createSkill",
    namespace: "skill",
    memberName: "create",
    method: "POST",
    pathTemplate: "/api/skills",
    requestType: "CreateSkillRequest",
    responseType: "CreateSkillResponse",
    pathParams: [],
    hasJsonBody: true,
  },
  getSkill: {
    operationName: "getSkill",
    namespace: "skill",
    memberName: "get",
    method: "GET",
    pathTemplate: "/api/skills/{skillId}",
    requestType: "GetSkillRequest",
    responseType: "GetSkillResponse",
    pathParams: [{ rustFieldName: "skill_id", wireName: "skillId" }],
    hasJsonBody: false,
  },
  listSkills: {
    operationName: "listSkills",
    namespace: "skill",
    memberName: "list",
    method: "GET",
    pathTemplate: "/api/skills",
    requestType: "ListSkillsRequest",
    responseType: "ListSkillsResponse",
    pathParams: [],
    hasJsonBody: false,
  },
  updateSkill: {
    operationName: "updateSkill",
    namespace: "skill",
    memberName: "update",
    method: "PUT",
    pathTemplate: "/api/skills/{skillId}",
    requestType: "UpdateSkillRequest",
    responseType: "UpdateSkillResponse",
    pathParams: [{ rustFieldName: "skill_id", wireName: "skillId" }],
    hasJsonBody: true,
  },
  deleteSkill: {
    operationName: "deleteSkill",
    namespace: "skill",
    memberName: "delete",
    method: "DELETE",
    pathTemplate: "/api/skills/{skillId}",
    requestType: "DeleteSkillRequest",
    responseType: "DeleteSkillResponse",
    pathParams: [{ rustFieldName: "skill_id", wireName: "skillId" }],
    hasJsonBody: false,
  },
  createAgent: {
    operationName: "createAgent",
    namespace: "agent",
    memberName: "create",
    method: "POST",
    pathTemplate: "/api/agents",
    requestType: "CreateAgentRequest",
    responseType: "CreateAgentResponse",
    pathParams: [],
    hasJsonBody: true,
  },
  getAgent: {
    operationName: "getAgent",
    namespace: "agent",
    memberName: "get",
    method: "GET",
    pathTemplate: "/api/agents/{agentId}",
    requestType: "GetAgentRequest",
    responseType: "GetAgentResponse",
    pathParams: [{ rustFieldName: "agent_id", wireName: "agentId" }],
    hasJsonBody: false,
  },
  listAgents: {
    operationName: "listAgents",
    namespace: "agent",
    memberName: "list",
    method: "GET",
    pathTemplate: "/api/agents",
    requestType: "ListAgentsRequest",
    responseType: "ListAgentsResponse",
    pathParams: [],
    hasJsonBody: false,
  },
  updateAgent: {
    operationName: "updateAgent",
    namespace: "agent",
    memberName: "update",
    method: "PUT",
    pathTemplate: "/api/agents/{agentId}",
    requestType: "UpdateAgentRequest",
    responseType: "UpdateAgentResponse",
    pathParams: [{ rustFieldName: "agent_id", wireName: "agentId" }],
    hasJsonBody: true,
  },
  deleteAgent: {
    operationName: "deleteAgent",
    namespace: "agent",
    memberName: "delete",
    method: "DELETE",
    pathTemplate: "/api/agents/{agentId}",
    requestType: "DeleteAgentRequest",
    responseType: "DeleteAgentResponse",
    pathParams: [{ rustFieldName: "agent_id", wireName: "agentId" }],
    hasJsonBody: false,
  },
} as const satisfies Record<EndpointOperation, FrontendEndpointDefinition>;
