// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes one server-derived ancestor used to navigate without parsing path separators in JavaScript.
 */
export type FileSystemBreadcrumb = { name: string; path: string };

/**
 * Describes one child entry returned by a server-side directory listing.
 */
export type FileSystemEntry = {
  name: string;
  path: string;
  kind: FileSystemEntryKind;
  isSymbolicLink: boolean;
};

/**
 * Distinguishes selectable filesystem entries from entries whose metadata cannot be resolved.
 */
export type FileSystemEntryKind = "file" | "directory" | "unavailable";

/**
 * Requests one server-side directory, defaulting to the server user's home when omitted.
 */
export type ListDirectoryRequest = { path?: string };

/**
 * Returns the resolved directory, its parent, and every visible child entry.
 */
export type ListDirectoryResponse = {
  currentPath: string;
  parentPath: string | null;
  breadcrumbs: Array<FileSystemBreadcrumb>;
  entries: Array<FileSystemEntry>;
};
