// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests process activation for one enabled plugin.
 */
export type ActivatePluginRequest = { pluginId: string };

/**
 * Returns the immediate starting or already-running plugin snapshot.
 */
export type ActivatePluginResponse = { plugin: InstalledPlugin };

/**
 * Describes one marketplace plugin listed by the cached registry index.
 */
export type AvailablePlugin = {
  id: string;
  name: string;
  namespace: string;
  version: string;
  description: string;
  /**
   * Security-validated SVG source for the marketplace icon, absent when none is published.
   */
  logo: string | null;
};

/**
 * Requests persistent ineligibility for one installed plugin.
 */
export type DisablePluginRequest = { pluginId: string };

/**
 * Returns the stopped and disabled plugin snapshot after persistence succeeds.
 */
export type DisablePluginResponse = { plugin: InstalledPlugin };

/**
 * Requests durable eligibility for one installed plugin without starting its process.
 */
export type EnablePluginRequest = { pluginId: string };

/**
 * Returns the enabled plugin snapshot observed after persistence succeeds.
 */
export type EnablePluginResponse = { plugin: InstalledPlugin };

/**
 * Requests the current editor snapshot for one installed plugin.
 */
export type GetPluginConfigurationRequest = { pluginId: string };

/**
 * Returns the resolved editor snapshot without exposing its filesystem location.
 */
export type GetPluginConfigurationResponse = {
  configuration: PluginConfigurationDetails;
};

/**
 * Requests installation of one marketplace plugin by its registry identifier.
 */
export type InstallPluginRequest = { pluginId: string };

/**
 * Confirms the identifier installed after download, verification, and extraction complete.
 */
export type InstallPluginResponse = { pluginId: string };

/**
 * Describes one installed plugin discovered from its package manifest.
 */
export type InstalledPlugin =
  & {
    id: string;
    packageName: string;
    displayName: string;
    version: string;
    kind: string;
    main: string;
    agent: InstalledPluginAgent;
    enabled: boolean;
    /**
     * Security-validated SVG source for the package icon, absent when the package ships none.
     *
     * The icon travels as inline source instead of a filesystem path because the webview cannot
     * read the plugin directory; surfaces render it from a `data:` URL and fall back to a
     * generic mark when it is absent.
     */
    logo: string | null;
    installationValidity: PluginInstallationValidity;
    configuration: PluginConfigurationSummary;
  }
  & ({ "runtime": "stopped" } | { "runtime": "starting" } | {
    "runtime": "running";
  } | { "runtime": "failed"; failureReason: string });

/**
 * Describes the single agent contributed by an installed agent plugin package.
 *
 * The agent carries no id: one package provides exactly one agent, identified by the package.
 */
export type InstalledPluginAgent = {
  displayName: string;
  contractVersion: number;
};

/**
 * Requests the cached marketplace registry index used to populate the plugin catalog.
 */
export type ListAvailablePluginsRequest = Record<symbol, never>;

/**
 * Returns the marketplace plugins cached in the registry index.
 */
export type ListAvailablePluginsResponse = {
  updatedAt: bigint;
  plugins: Array<AvailablePlugin>;
};

/**
 * Requests the immutable startup snapshot of installed plugin packages.
 */
export type ListInstalledPluginsRequest = Record<symbol, never>;

/**
 * Returns every valid installed plugin in stable identifier order.
 */
export type ListInstalledPluginsResponse = { plugins: Array<InstalledPlugin> };

/**
 * Reports whether every required Setting has an effective type-correct value.
 */
export type PluginConfigurationCompleteness = "complete" | "incomplete";

/**
 * Carries one complete editor snapshot bound to a revision and declaration fingerprint.
 */
export type PluginConfigurationDetails = {
  pluginId: string;
  schemaVersion: number;
  revision: bigint;
  declarationFingerprint: string;
  settings: Array<PluginSettingDetails>;
  summary: PluginConfigurationSummary;
};

/**
 * Represents the exclusive list-facing Plugin Configuration state.
 */
export type PluginConfigurationSummary = { "state": "not_declared" } | {
  "state": "available";
  completeness: PluginConfigurationCompleteness;
} | { "state": "unavailable"; errorCode: string };

/**
 * Selects whether uninstall retains or deletes host-owned plugin data.
 */
export type PluginDataDisposition = "delete" | "retain";

/**
 * Represents whether the installed package and its immutable declaration are usable.
 */
export type PluginInstallationValidity = { "validity": "valid" } | {
  "validity": "invalid_declaration";
  errorCode: string;
};

/**
 * Represents the process-scoped lifecycle of one installed plugin.
 */
export type PluginRuntimeStatus =
  | { "runtime": "stopped" }
  | { "runtime": "starting" }
  | { "runtime": "running" }
  | { "runtime": "failed"; failureReason: string };

/**
 * Describes one immutable plugin-authored Setting.
 */
export type PluginSettingDeclaration = {
  id: string;
  title: string;
  description: string;
  type: PluginSettingType;
  required: boolean;
  order: bigint | null;
  default: PluginSettingValue | null;
};

/**
 * Projects one Setting into an editor field without exposing raw files.
 */
export type PluginSettingDetails = {
  declaration: PluginSettingDeclaration;
  storedValue: PluginSettingValue | null;
  effectiveValue: PluginSettingValue | null;
  source: PluginSettingValueSource;
  valueErrorCode: string | null;
};

/**
 * Enumerates Setting types supported by declaration schema version one.
 */
export type PluginSettingType = "string" | "number" | "boolean";

/**
 * Carries one non-secret scalar override accepted by schema version one.
 */
export type PluginSettingValue = string | number | boolean;

/**
 * Identifies the source of one effective editor value.
 */
export type PluginSettingValueSource = "stored" | "default" | "absent";

/**
 * Selects the explicit reset operation authorized by the user.
 */
export type ResetPluginConfigurationMode = {
  "mode": "reset_all";
  expectedRevision: bigint;
} | { "mode": "recover_corrupt" };

/**
 * Requests Reset All or confirmed damaged-data recovery for one plugin.
 */
export type ResetPluginConfigurationRequest =
  & { pluginId: string; declarationFingerprint: string }
  & ({ "mode": "reset_all"; expectedRevision: bigint } | {
    "mode": "recover_corrupt";
  });

/**
 * Returns the authoritative editor snapshot after a reset operation.
 */
export type ResetPluginConfigurationResponse = {
  configuration: PluginConfigurationDetails;
};

/**
 * Replaces every explicit override recognized by the loaded declaration.
 */
export type SavePluginConfigurationRequest = {
  pluginId: string;
  expectedRevision: bigint;
  declarationFingerprint: string;
  values: { [key in string]: PluginSettingValue };
};

/**
 * Returns the authoritative post-save editor snapshot and list summary.
 */
export type SavePluginConfigurationResponse = {
  configuration: PluginConfigurationDetails;
};

/**
 * Requests explicit filesystem discovery and state reconciliation.
 */
export type ScanPluginsRequest = Record<symbol, never>;

/**
 * Returns the refreshed installed-plugin snapshot produced by an explicit scan.
 */
export type ScanPluginsResponse = { plugins: Array<InstalledPlugin> };

/**
 * Requests process shutdown for one plugin without changing durable eligibility.
 */
export type StopPluginRequest = { pluginId: string };

/**
 * Returns the stopped plugin snapshot after process exit is confirmed.
 */
export type StopPluginResponse = { plugin: InstalledPlugin };

/**
 * Requests a marketplace source sync followed by an atomic registry-index rebuild.
 */
export type SyncAvailablePluginsRequest = Record<symbol, never>;

/**
 * Returns the registry index rebuilt immediately after a marketplace sync succeeds.
 */
export type SyncAvailablePluginsResponse = {
  updatedAt: bigint;
  plugins: Array<AvailablePlugin>;
};

/**
 * Requests complete removal of one plugin package and its durable lifecycle state.
 */
export type UninstallPluginRequest = {
  pluginId: string;
  dataDisposition: PluginDataDisposition;
};

/**
 * Confirms the identifier removed after process shutdown and package deletion complete.
 */
export type UninstallPluginResponse = { pluginId: string };
