// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests process activation for one enabled plugin.
 */
export type ActivatePluginRequest = { pluginId: string };

/**
 * Returns the immediate starting or already-running plugin snapshot.
 */
export type ActivatePluginResponse = { plugin: InstalledPlugin };

/**
 * Requests persistent ineligibility for one installed plugin.
 */
export type DisablePluginRequest = { pluginId: string };

/**
 * Returns the stopped and disabled plugin snapshot after persistence succeeds.
 */
export type DisablePluginResponse = { plugin: InstalledPlugin };

/**
 * Requests durable eligibility for one installed plugin without starting its process.
 */
export type EnablePluginRequest = { pluginId: string };

/**
 * Returns the enabled plugin snapshot observed after persistence succeeds.
 */
export type EnablePluginResponse = { plugin: InstalledPlugin };

/**
 * Describes one installed plugin discovered from its package manifest.
 */
export type InstalledPlugin =
  & {
    id: string;
    packageName: string;
    displayName: string;
    version: string;
    main: string;
    enabled: boolean;
  }
  & ({ "kind": "agent"; agentDisplayName: string; contractVersion: number } | {
    "kind": "ui";
    contractVersion: number;
    surfaces: Array<InstalledPluginSurface>;
  })
  & ({ "runtime": "stopped" } | { "runtime": "starting" } | {
    "runtime": "running";
  } | { "runtime": "failed"; failureReason: string });

/**
 * Describes the kind-specific contribution of one installed plugin, discriminated by `kind`.
 *
 * The agent variant names its display name `agentDisplayName` because the contribution is
 * flattened into [`InstalledPlugin`], which already owns the top-level `displayName`.
 */
export type InstalledPluginContribution = {
  "kind": "agent";
  agentDisplayName: string;
  contractVersion: number;
} | {
  "kind": "ui";
  contractVersion: number;
  surfaces: Array<InstalledPluginSurface>;
};

/**
 * Describes one surface a ui plugin contributes, with its source flattened beside the identity.
 */
export type InstalledPluginSurface =
  & { id: string; title: string }
  & ({ "source": "remote_site"; entryUrl: string });

/**
 * Describes where a surface loads its content from, discriminated by `source`.
 */
export type InstalledPluginSurfaceSource = {
  "source": "remote_site";
  entryUrl: string;
};

/**
 * Requests the immutable startup snapshot of installed plugin packages.
 */
export type ListInstalledPluginsRequest = Record<symbol, never>;

/**
 * Returns every valid installed plugin in stable identifier order.
 */
export type ListInstalledPluginsResponse = { plugins: Array<InstalledPlugin> };

/**
 * Represents the process-scoped lifecycle of one installed plugin.
 */
export type PluginRuntimeStatus =
  | { "runtime": "stopped" }
  | { "runtime": "starting" }
  | { "runtime": "running" }
  | { "runtime": "failed"; failureReason: string };

/**
 * Requests explicit filesystem discovery and state reconciliation.
 */
export type ScanPluginsRequest = Record<symbol, never>;

/**
 * Returns the refreshed installed-plugin snapshot produced by an explicit scan.
 */
export type ScanPluginsResponse = { plugins: Array<InstalledPlugin> };

/**
 * Requests process shutdown for one plugin without changing durable eligibility.
 */
export type StopPluginRequest = { pluginId: string };

/**
 * Returns the stopped plugin snapshot after process exit is confirmed.
 */
export type StopPluginResponse = { plugin: InstalledPlugin };

/**
 * Requests complete removal of one plugin package and its durable lifecycle state.
 */
export type UninstallPluginRequest = { pluginId: string };

/**
 * Confirms the identifier removed after process shutdown and package deletion complete.
 */
export type UninstallPluginResponse = { pluginId: string };
