// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries the payload used to open or switch a client window into a project.
 */
export type OpenProjectWorkContextRequest = {
  surface: ProjectWorkContextSurface;
  windowId: string;
  projectId: string;
};

/**
 * Returns the active project work context after a successful open or switch.
 */
export type OpenProjectWorkContextResponse = { context: ProjectWorkContext };

/**
 * Describes the public project work context payload shared across adapter responses.
 */
export type ProjectWorkContext = {
  id: string;
  surface: ProjectWorkContextSurface;
  windowId: string;
  projectId: string;
  leaseExpiresAt: number;
};

/**
 * Describes which client surface owns one project work context.
 */
export type ProjectWorkContextSurface = "web" | "tauri";

/**
 * Carries the payload used to renew an existing project work context lease.
 */
export type RenewProjectWorkContextRequest = {
  surface: ProjectWorkContextSurface;
  windowId: string;
};

/**
 * Returns the active project work context after a successful lease renewal.
 */
export type RenewProjectWorkContextResponse = { context: ProjectWorkContext };
