// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests probing one URL through an explicit proxy configuration.
 */
export type CheckProxySettingsRequest = {
  /**
   * Absolute HTTP(S) URL to fetch through the supplied proxy.
   */
  url: string;
  /**
   * Proxy configuration to probe with, independent of whatever is currently persisted.
   */
  settings: ProxySettings;
};

/**
 * Reports whether the supplied proxy could reach the requested URL.
 *
 * Any HTTP response, including 4xx and 5xx, means the proxy path reached a host. Transport
 * failures such as timeouts, refused connections, and invalid URLs are `unreachable`.
 */
export type CheckProxySettingsResponse = {
  "outcome": "reachable";
  status: number;
} | { "outcome": "unreachable"; message: string };

/**
 * Requests deleting the configured network proxy.
 */
export type ClearProxySettingsRequest = Record<symbol, never>;

/**
 * Confirms the network proxy has been cleared.
 */
export type ClearProxySettingsResponse = { settings: ProxySettings | null };

/**
 * Requests the configured network proxy without additional parameters.
 */
export type GetProxySettingsRequest = Record<symbol, never>;

/**
 * Returns the configured network proxy.
 */
export type GetProxySettingsResponse = { settings: ProxySettings | null };

/**
 * Describes an optional host-level network proxy used by marketplace traffic.
 */
export type ProxySettings = {
  /**
   * Proxy hostname or address without a scheme.
   */
  host: string;
  /**
   * Proxy TCP port.
   */
  port: number;
  /**
   * Optional HTTP Basic username for the proxy.
   */
  username: string | null;
  /**
   * Optional HTTP Basic password for the proxy.
   */
  password: string | null;
};

/**
 * Requests replacing the configured network proxy.
 */
export type SetProxySettingsRequest = { settings: ProxySettings };

/**
 * Returns the authoritative network proxy after a save.
 */
export type SetProxySettingsResponse = { settings: ProxySettings | null };
