// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a local branch to check out in the project's main worktree.
 */
export type CheckoutRepositoryBranchRequest = {
  projectId: string;
  branchName: string;
};

/**
 * Returns the branch selected in the project's main worktree.
 */
export type CheckoutRepositoryBranchResponse = { branch: string };

/**
 * Identifies the commit message for staged changes in the project's main checkout.
 */
export type CommitRepositoryChangesRequest = {
  projectId: string;
  message: string;
};

/**
 * Returns the new commit and refreshed main checkout status after committing changes.
 */
export type CommitRepositoryChangesResponse = {
  commitId: string;
  summary: string;
  workingTree: RepositoryWorkingTree;
};

/**
 * Identifies a local branch to create from the repository's current HEAD.
 */
export type CreateRepositoryBranchRequest = {
  projectId: string;
  branchName: string;
};

/**
 * Returns the local branch created for the repository.
 */
export type CreateRepositoryBranchResponse = { branch: string };

/**
 * Identifies the project repository whose remote refs should be refreshed.
 */
export type FetchRepositoryRequest = { projectId: string };

/**
 * Returns the refreshed graph and remote tracking state after fetching.
 */
export type FetchRepositoryResponse = { snapshot: RepositorySnapshot };

/**
 * Identifies the bounded patch requested after a commit file is opened.
 */
export type GetRepositoryCommitDiffRequest = {
  projectId: string;
  commitId: string;
  parentCommitId: string | null;
  path: string;
};

/**
 * Returns one historical commit's bounded unified patch.
 */
export type GetRepositoryCommitDiffResponse = { patch: string };

/**
 * Identifies one commit detail request using a project-owned repository root.
 */
export type GetRepositoryCommitRequest = {
  projectId: string;
  commitId: string;
};

/**
 * Returns a selected commit and its changed paths without loading the full patch.
 */
export type GetRepositoryCommitResponse = { commit: RepositoryCommitDetails };

/**
 * Identifies the project whose Git repository should be inspected.
 */
export type GetRepositorySnapshotRequest = { projectId: string };

/**
 * Returns the repository metadata, refs, bounded history, and current worktree status.
 */
export type GetRepositorySnapshotResponse = { snapshot: RepositorySnapshot };

/**
 * Identifies the project whose main checkout changes should be rendered.
 */
export type GetRepositoryWorkingTreeDiffRequest = { projectId: string };

/**
 * Returns the main checkout revision and its bounded working-tree patch.
 */
export type GetRepositoryWorkingTreeDiffResponse = {
  diff: RepositoryWorkingTreeDiff;
};

/**
 * Describes the result of a repository synchronization attempt.
 */
export type PullRepositoryOutcome =
  | { "kind": "alreadyUpToDate" }
  | { "kind": "fastForwarded" }
  | { "kind": "merged" }
  | { "kind": "rebased" }
  | { "kind": "diverged"; ahead: number; behind: number }
  | { "kind": "conflicted"; operation: RepositorySyncOperation };

/**
 * Identifies the project repository whose current branch should be synchronized.
 */
export type PullRepositoryRequest = {
  projectId: string;
  strategy: PullRepositoryStrategy;
};

/**
 * Returns the pull outcome and refreshed graph/tracking state.
 */
export type PullRepositoryResponse = {
  outcome: PullRepositoryOutcome;
  snapshot: RepositorySnapshot;
};

/**
 * Selects how a fetched upstream should be integrated into the current branch.
 */
export type PullRepositoryStrategy = "fastForwardOnly" | "merge" | "rebase";

/**
 * Identifies the project's checked-out branch to publish to its default remote.
 */
export type PushRepositoryBranchRequest = { projectId: string };

/**
 * Returns the published branch and the refreshed graph/tracking state.
 */
export type PushRepositoryBranchResponse = {
  branchName: string;
  remoteName: string;
  snapshot: RepositorySnapshot;
};

/**
 * Selects every pending change or an explicit set of repository-relative paths.
 */
export type RepositoryChangeSelection = { "kind": "all" } | {
  "kind": "paths";
  "paths": Array<string>;
};

/**
 * Contains the topology and author metadata needed for one graph row.
 */
export type RepositoryCommit = {
  id: string;
  shortId: string;
  parents: Array<string>;
  subject: string;
  authorName: string;
  authorEmail: string;
  authoredAt: string;
  referenceNames: Array<string>;
};

/**
 * Extends graph metadata with the files changed by the selected commit.
 */
export type RepositoryCommitDetails = {
  id: string;
  shortId: string;
  parents: Array<string>;
  subject: string;
  authorName: string;
  authorEmail: string;
  authoredAt: string;
  files: Array<RepositoryCommitFile>;
};

/**
 * Describes one changed path using Git's compact name-status code.
 */
export type RepositoryCommitFile = { status: string; path: string };

/**
 * Selects the Git side to use when resolving one unmerged path.
 */
export type RepositoryConflictSide = "ours" | "theirs";

/**
 * Identifies which ref family decorates a repository graph commit.
 */
export type RepositoryRefKind = "local" | "remote" | "tag";

/**
 * Associates one visible ref with the commit it decorates.
 */
export type RepositoryReference = {
  name: string;
  commitId: string;
  kind: RepositoryRefKind;
};

/**
 * Summarizes the current branch's configured upstream and commit distance.
 */
export type RepositoryRemoteStatus = {
  upstream: string | null;
  ahead: number;
  behind: number;
};

/**
 * Represents the first read-only repository graph slice consumed by the app shell.
 */
export type RepositorySnapshot = {
  projectId: string;
  rootPath: string;
  headCommitId: string | null;
  currentBranch: string | null;
  references: Array<RepositoryReference>;
  commits: Array<RepositoryCommit>;
  workingTree: RepositoryWorkingTree;
  remoteStatus: RepositoryRemoteStatus;
  syncOperation: RepositorySyncOperation | null;
};

/**
 * Selects whether an active merge or rebase should continue or be rolled back.
 */
export type RepositorySyncAction = "continue" | "abort";

/**
 * Identifies the integration operation that can remain active while conflicts are resolved.
 */
export type RepositorySyncOperation = "merge" | "rebase";

/**
 * Describes the result of resolving an active synchronization operation.
 */
export type RepositorySyncOutcome = "completed" | "aborted" | "conflicted";

/**
 * Summarizes the checked-out worktree without exposing raw porcelain output to the UI.
 */
export type RepositoryWorkingTree = {
  changedFiles: number;
  stagedFiles: number;
  unstagedFiles: number;
  untrackedFiles: number;
  conflictedFiles: number;
  files: Array<RepositoryWorkingTreeFile>;
};

/**
 * Contains only the patch needed to review the project's main checkout.
 */
export type RepositoryWorkingTreeDiff = {
  headCommitId: string | null;
  patch: string;
};

/**
 * Describes one pending main-checkout path and which side of the index differs.
 */
export type RepositoryWorkingTreeFile = {
  path: string;
  status: string;
  staged: boolean;
  unstaged: boolean;
};

/**
 * Identifies one conflicted path in the project's main checkout.
 */
export type ResolveRepositoryConflictRequest = {
  projectId: string;
  path: string;
  side: RepositoryConflictSide;
};

/**
 * Returns refreshed status after selecting and staging one conflict side.
 */
export type ResolveRepositoryConflictResponse = {
  workingTree: RepositoryWorkingTree;
};

/**
 * Identifies the project repository whose active synchronization should be resolved.
 */
export type ResolveRepositorySyncRequest = {
  projectId: string;
  action: RepositorySyncAction;
};

/**
 * Returns the resolution result and refreshed graph/worktree state.
 */
export type ResolveRepositorySyncResponse = {
  outcome: RepositorySyncOutcome;
  snapshot: RepositorySnapshot;
};

/**
 * Identifies changes to stage in the project's main checkout.
 */
export type StageRepositoryChangesRequest = {
  projectId: string;
  selection: RepositoryChangeSelection;
};

/**
 * Returns the refreshed main checkout status after staging changes.
 */
export type StageRepositoryChangesResponse = {
  workingTree: RepositoryWorkingTree;
};

/**
 * Identifies changes to remove from the index in the project's main checkout.
 */
export type UnstageRepositoryChangesRequest = {
  projectId: string;
  selection: RepositoryChangeSelection;
};

/**
 * Returns the refreshed main checkout status after unstaging changes.
 */
export type UnstageRepositoryChangesResponse = {
  workingTree: RepositoryWorkingTree;
};
