// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlock } from "./acp/content.js";
import type { PermissionOption } from "./acp/permission.js";
import type { StopReason } from "./acp/prompt.js";
import type { SessionUpdate } from "./acp/session.js";
import type { AvailableCommand } from "./acp/slash_command.js";
import type { ToolCallUpdate } from "./acp/tool_call.js";

/**
 * Identifies the shared CLI runtime selected for a provider-backed session.
 */
export type AgentCli = "open_code" | "nga" | "code_agent_cli";

/**
 * Groups the model identifiers reported by one currently available CLI.
 */
export type AgentCliModels = { agentCli: AgentCli; models: Array<string> };

/**
 * Creates a provider-backed session on one selected application-scoped CLI.
 */
export type CreateSessionRequest = { taskId: string; agentCli: AgentCli };

/**
 * Returns the created session after the ACP `session/new` handshake succeeds.
 */
export type CreateSessionResponse = {
  session: Session;
  availableCommands: Array<AvailableCommand>;
};

/**
 * Identifies which Ora session record to remove.
 */
export type DeleteSessionRequest = { sessionId: string };

/**
 * Returns the removed Ora session identifier without deleting provider history.
 */
export type DeleteSessionResponse = { sessionId: string };

/**
 * Identifies which session to fetch.
 */
export type GetSessionRequest = { sessionId: string };

/**
 * Returns one session payload after a successful fetch.
 */
export type GetSessionResponse = { session: Session };

/**
 * Requests model catalogs from every CLI without failing on unavailable runtimes.
 */
export type ListAgentModelsRequest = Record<symbol, never>;

/**
 * Returns only CLI groups whose model command completed successfully.
 */
export type ListAgentModelsResponse = { groups: Array<AgentCliModels> };

/**
 * Requests the full visible session list.
 */
export type ListSessionsRequest = Record<symbol, never>;

/**
 * Returns the visible session list.
 */
export type ListSessionsResponse = { sessions: Array<Session> };

/**
 * Replays Ora's recorded history while keeping JSON-RPC framing private to the backend.
 *
 * The stream carries assembled updates read back from Ora's own record, not the
 * provider's replay. `TurnEnded` has no ACP equivalent and exists because a
 * cancelled turn would otherwise be indistinguishable from a completed one —
 * information provider replay never carried.
 */
export type LoadSessionEvent =
  | { "type": "session_update"; update: SessionUpdate }
  | { "type": "permission_request" } & SessionPermissionRequest
  | { "type": "turn_ended"; stopReason: StopReason }
  | { "type": "completed" };

/**
 * Identifies a stopped session whose provider history should be replayed.
 */
export type LoadSessionRequest = { sessionId: string };

/**
 * Streams one prompt turn and ends with the provider's typed stop reason.
 */
export type PromptSessionEvent =
  | { "type": "session_update"; update: SessionUpdate }
  | { "type": "permission_request" } & SessionPermissionRequest
  | { "type": "completed"; stopReason: StopReason };

/**
 * Carries one or more ACP content blocks to the provider session.
 */
export type PromptSessionRequest = {
  sessionId: string;
  prompt: Array<ContentBlock>;
};

/**
 * Selects one option for a still-pending permission request.
 */
export type RespondToPermissionRequest = {
  sessionId: string;
  permissionRequestId: string;
  optionId: string;
};

/**
 * Confirms that a permission response was delivered to the agent.
 */
export type RespondToPermissionResponse = Record<symbol, never>;

/**
 * Returns a session whose history writes failed to a writable state.
 *
 * Resuming appends a record of what went missing before accepting new content,
 * so the conversation never contains a gap that cannot be seen.
 */
export type ResumeSessionHistoryRequest = { sessionId: string };

/**
 * Returns the session after its history became writable again.
 */
export type ResumeSessionHistoryResponse = { session: Session };

/**
 * Describes the public session payload without exposing the provider session identifier.
 */
export type Session = {
  id: string;
  taskId: string;
  /**
   * The CLI this conversation currently runs on, which switching replaces.
   */
  agentCli: AgentCli;
  status: SessionStatus;
  historyState: SessionHistoryState;
};

/**
 * Reports whether Ora can still extend this session's recorded history.
 *
 * Separate from [`SessionStatus`] on purpose: that says whether the conversation
 * is registered on a CLI connection, this says whether the record of it can
 * still grow. A running session whose disk filled is both at once, and the user
 * has to be told which one broke.
 */
export type SessionHistoryState = { "type": "writable" } | {
  "type": "degraded";
  reason: string;
};

/**
 * Exposes an opaque permission request while preserving the agent's typed option payload.
 */
export type SessionPermissionRequest = {
  permissionRequestId: string;
  toolCall: ToolCallUpdate;
  options: Array<PermissionOption>;
};

/**
 * Describes whether a persisted session is registered on its shared CLI connection.
 */
export type SessionStatus = "running" | "stopped";

/**
 * Identifies a running session whose child process should be stopped.
 */
export type StopSessionRequest = { sessionId: string };

/**
 * Returns the stopped public session snapshot.
 */
export type StopSessionResponse = { session: Session };

/**
 * Moves one existing conversation onto a different agent CLI.
 *
 * Only the binding changes: the session keeps its identifier, its task, and the
 * history it has accumulated. The new CLI starts with no context, so Ora's
 * recorded transcript is prepended to the next prompt sent into it.
 */
export type SwitchSessionAgentRequest = {
  sessionId: string;
  agentCli: AgentCli;
};

/**
 * Returns the session rebound to its new CLI.
 */
export type SwitchSessionAgentResponse = {
  session: Session;
  availableCommands: Array<AvailableCommand>;
};
