// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries the app-facing payload for session creation requests.
 */
export type CreateSessionRequest = {
  taskId: string;
  agentId: string;
  agentSessionId: string | null;
  status: SessionStatus;
};

/**
 * Returns the created session after a successful create request.
 */
export type CreateSessionResponse = { session: Session };

/**
 * Identifies which session to delete.
 */
export type DeleteSessionRequest = { sessionId: string };

/**
 * Returns the deleted session identifier after a successful delete request.
 */
export type DeleteSessionResponse = { sessionId: string };

/**
 * Identifies which session to fetch.
 */
export type GetSessionRequest = { sessionId: string };

/**
 * Returns one session payload after a successful fetch.
 */
export type GetSessionResponse = { session: Session };

/**
 * Requests the full visible session list.
 */
export type ListSessionsRequest = Record<symbol, never>;

/**
 * Returns the visible session list.
 */
export type ListSessionsResponse = { sessions: Array<Session> };

/**
 * Describes the public session payload shared across adapter responses.
 */
export type Session = {
  id: string;
  taskId: string;
  agentId: string;
  agentSessionId: string | null;
  status: SessionStatus;
};

/**
 * Describes whether the public session view is still running.
 */
export type SessionStatus = "running" | "stopped";

/**
 * Carries the full replacement payload for session updates in the first slice.
 */
export type UpdateSessionRequest = {
  sessionId: string;
  taskId: string;
  agentId: string;
  agentSessionId: string | null;
  status: SessionStatus;
};

/**
 * Returns the updated session after a successful update request.
 */
export type UpdateSessionResponse = { session: Session };
