// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries the app-facing payload for session creation requests.
 */
export type CreateSessionRequest = {
  taskId: string;
  agentId: string;
  agentSessionId: string | null;
  status: SessionStatus;
  terminal: TerminalSessionStartup | null;
};

/**
 * Returns the created session after a successful create request.
 */
export type CreateSessionResponse = { session: Session };

/**
 * Identifies which session to delete.
 */
export type DeleteSessionRequest = { sessionId: string };

/**
 * Returns the deleted session identifier after a successful delete request.
 */
export type DeleteSessionResponse = { sessionId: string };

/**
 * Identifies which session to fetch.
 */
export type GetSessionRequest = { sessionId: string };

/**
 * Returns one session payload after a successful fetch.
 */
export type GetSessionResponse = { session: Session };

/**
 * Requests the full visible session list.
 */
export type ListSessionsRequest = Record<symbol, never>;

/**
 * Returns the visible session list.
 */
export type ListSessionsResponse = { sessions: Array<Session> };

/**
 * Describes the public session payload shared across adapter responses.
 */
export type Session = {
  id: string;
  taskId: string;
  agentId: string;
  agentSessionId: string | null;
  status: SessionStatus;
};

/**
 * Describes whether the public session view is still running.
 */
export type SessionStatus = "running" | "stopped";

/**
 * Describes one client-to-server terminal control message.
 */
export type TerminalClientMessage = { "type": "input"; data: string } | {
  "type": "resize";
  cols: number;
  rows: number;
} | { "type": "kill" };

/**
 * Describes one server-to-client terminal stream message.
 */
export type TerminalServerMessage =
  | { "type": "ready"; sessionId: string }
  | { "type": "history"; data: string }
  | { "type": "output"; data: string }
  | { "type": "exit"; exitCode: number | null }
  | { "type": "error"; code: string; message: string };

/**
 * Describes the initial PTY dimensions used only during terminal session startup.
 */
export type TerminalSessionStartup = { cols: number; rows: number };

/**
 * Carries the full replacement payload for session updates in the first slice.
 */
export type UpdateSessionRequest = {
  sessionId: string;
  taskId: string;
  agentId: string;
  agentSessionId: string | null;
  status: SessionStatus;
};

/**
 * Returns the updated session after a successful update request.
 */
export type UpdateSessionResponse = { session: Session };
