// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests every visible workspace so clients can resolve direct chats to the main workspace.
 */
export type ListWorkspacesRequest = Record<symbol, never>;

/**
 * Returns the visible workspace identities in stable creation order.
 */
export type ListWorkspacesResponse = { workspaces: Array<Workspace> };

/**
 * Describes the stable workspace identity used by Sessions and WorkflowRuns.
 */
export type Workspace = {
  id: string;
  projectId: string;
  kind: WorkspaceKind;
  lifecycle: WorkspaceLifecycle;
};

/**
 * Identifies the canonical project checkout or an isolated execution environment.
 */
export type WorkspaceKind = "main" | "isolated";

/**
 * Reports the lifecycle admission state visible to workspace consumers.
 */
export type WorkspaceLifecycle =
  | "provisioning"
  | "active"
  | "unavailable"
  | "retiring"
  | "deleted";
