// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the running run whose node sessions should be stopped and run cancelled.
 */
export type CancelWorkflowRunRequest = { runId: string };

/**
 * Returns the cancelled run.
 */
export type CancelWorkflowRunResponse = { run: WorkflowRun };

/**
 * Identifies the awaiting interactive node to complete.
 */
export type CompleteWorkflowNodeRequest = {
  runId: string;
  nodeId: string;
  requester?: NodeCompletionRequester;
};

/**
 * Returns the run after the node completed.
 */
export type CompleteWorkflowNodeResponse = { run: WorkflowRun };

/**
 * Carries the fields required to create a workflow run against a published snapshot and workspace.
 */
export type CreateWorkflowRunRequest = {
  workspaceId: string;
  workflowId: string;
  locale: WorkflowRunLocale;
  snapshotId?: string;
  kickoffInput?: string;
  name?: string;
};

/**
 * Returns the created workspace-owned run.
 */
export type CreateWorkflowRunResponse = { run: WorkflowRun };

/**
 * Identifies the workflow run to soft-delete.
 */
export type DeleteWorkflowRunRequest = { runId: string };

/**
 * Returns the identifier of the soft-deleted run.
 */
export type DeleteWorkflowRunResponse = { runId: string };

/**
 * Identifies the workflow run to retrieve by its stable identifier.
 */
export type GetWorkflowRunRequest = { runId: string };

/**
 * Returns the full run detail including its display name and node runs.
 */
export type GetWorkflowRunResponse = {
  run: WorkflowRun;
  name: string;
  workspaceId: string;
  projectId: string;
  nodes: Array<WorkflowNodeRun>;
};

/**
 * Identifies the run whose node-run history to retrieve.
 */
export type ListWorkflowNodeRunsRequest = { runId: string };

/**
 * Returns the node-run records of one run.
 */
export type ListWorkflowNodeRunsResponse = { nodes: Array<WorkflowNodeRun> };

/**
 * Requests the workflow run summaries for one workflow.
 */
export type ListWorkflowRunsByWorkflowRequest = { workflowId: string };

/**
 * Returns the visible run summaries for the workflow.
 */
export type ListWorkflowRunsByWorkflowResponse = {
  runs: Array<WorkflowRunSummary>;
};

/**
 * Requests the workflow run summaries for one project.
 */
export type ListWorkflowRunsRequest = { projectId: string };

/**
 * Returns the visible run summaries for the project.
 */
export type ListWorkflowRunsResponse = { runs: Array<WorkflowRunSummary> };

/**
 * Who requested the completion of one workflow node.
 *
 * Phase 1 carries only the human path; the agent/CLI path reuses the same command later.
 */
export type NodeCompletionRequester = "human";

/**
 * Identifies the workflow run whose Workspace-owned display name should change.
 */
export type RenameWorkflowRunRequest = { runId: string; name: string };

/**
 * Returns the workflow run after its display name was replaced.
 */
export type RenameWorkflowRunResponse = { run: WorkflowRun };

/**
 * Identifies the non-running run to reset and re-run from its start node.
 */
export type RestartWorkflowRunRequest = { runId: string };

/**
 * Returns the reset and re-running run.
 */
export type RestartWorkflowRunResponse = { run: WorkflowRun };

/**
 * Identifies the run to start executing against its frozen snapshot graph.
 */
export type StartWorkflowRunRequest = { runId: string };

/**
 * Returns the run after starting (or idempotently its current state).
 */
export type StartWorkflowRunResponse = { run: WorkflowRun };

/**
 * Sets the kickoff input of a pending run, used as the start node's input on start.
 */
export type UpdateWorkflowRunInputRequest = {
  runId: string;
  input: string | null;
};

/**
 * Returns the run with its updated input.
 */
export type UpdateWorkflowRunInputResponse = { run: WorkflowRun };

/**
 * Public node-run payload without persistence audit metadata.
 */
export type WorkflowNodeRun = {
  id: string;
  runId: string;
  nodeId: string;
  nodeType: string;
  sessionId: string | null;
  status: WorkflowNodeStatus;
  input: string | null;
  output: string | null;
  error: string | null;
  payload: string | null;
  startedAt: bigint | null;
  finishedAt: bigint | null;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Describes the lifecycle state of one node execution in the public contract.
 */
export type WorkflowNodeStatus =
  | "pending"
  | "running"
  | "succeeded"
  | "failed"
  | "cancelled";

/**
 * Public workflow run payload without persistence audit metadata.
 */
export type WorkflowRun = {
  id: string;
  workspaceId: string;
  workflowId: string;
  snapshotId: string;
  name: string;
  status: WorkflowRunStatus;
  state: string | null;
  input: string | null;
  output: string | null;
  error: string | null;
  payload: string | null;
  startedAt: bigint | null;
  finishedAt: bigint | null;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Identifies the Ora display language frozen for generated workflow-run prompts.
 */
export type WorkflowRunLocale = "zh-CN" | "en-US";

/**
 * Describes the lifecycle state of a workflow run in the public contract.
 */
export type WorkflowRunStatus =
  | "pending"
  | "running"
  | "succeeded"
  | "failed"
  | "cancelled"
  | "awaitingInput";

/**
 * Lightweight run summary for list views with direct workspace ownership.
 */
export type WorkflowRunSummary = {
  id: string;
  name: string;
  workspaceId: string;
  projectId: string;
  workflowId: string;
  status: WorkflowRunStatus;
  startedAt: bigint | null;
  finishedAt: bigint | null;
  createdAt: bigint;
};
