// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.

use super::stream::StreamStart;
use crate::{error::CommandError, state::DesktopState};
use tauri::State;

/// Typed requests preserve the public DTO while rejecting unknown operations.
#[derive(serde::Deserialize)]
#[serde(tag = "operationName", content = "request")]
pub(super) enum StreamOperation {
    #[serde(rename = "loadSession")]
    LoadSession(ora_contracts::LoadSessionRequest),
    #[serde(rename = "promptSession")]
    PromptSession(ora_contracts::PromptSessionRequest),
    #[serde(rename = "watchAppEvents")]
    WatchAppEvents(ora_contracts::WatchAppEventsRequest),
    #[serde(rename = "watchProject")]
    WatchProject(ora_contracts::WatchProjectRequest),
    #[serde(rename = "watchWorkspace")]
    WatchWorkspace(ora_contracts::WatchWorkspaceRequest),
}

/// Dispatches a request without embedding domain logic in the transport lifecycle.
pub(super) async fn start(
    state: State<'_, DesktopState>,
    operation: StreamOperation,
    context: StreamStart,
) -> Result<(), CommandError> {
    match operation {
        StreamOperation::LoadSession(request) => {
            crate::commands::session::start_load(state, request, context).await
        }
        StreamOperation::PromptSession(request) => {
            crate::commands::session::start_prompt(state, request, context).await
        }
        StreamOperation::WatchAppEvents(request) => {
            crate::commands::app_events::start_watch(state, request, context).await
        }
        StreamOperation::WatchProject(request) => {
            crate::commands::files::start_project_watch(state, request, context).await
        }
        StreamOperation::WatchWorkspace(request) => {
            crate::commands::files::start_workspace_watch(state, request, context).await
        }
    }
}
