[package]
name = "ora-utils"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
default = ["validation"]
archive = ["dep:zip", "dep:tar", "dep:flate2"]
validation = ["dep:sha2", "dep:quick-xml"]

[dependencies]
flate2 = { workspace = true, optional = true }
quick-xml = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
tar = { workspace = true, optional = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
unicode-normalization = { workspace = true }
zip = { workspace = true, optional = true }

[dev-dependencies]
flate2 = { workspace = true }
pretty_assertions = { workspace = true }
tar = { workspace = true }
zip = { workspace = true }