//! Verifies the application ACL boundary: only the `main` webview may invoke
//! application commands, while `remote-surface:*` webviews are denied every app
//! command and every plugin/core command, because no capability names them.

use pretty_assertions::assert_eq;
use tauri::WebviewWindowBuilder;
use tauri::ipc::{CallbackFn, InvokeBody, InvokeResponseBody};
use tauri::test::MockRuntime;
use tauri::test::{INVOKE_KEY, get_ipc_response, mock_builder};
use tauri::webview::InvokeRequest;
use tauri::{App, WebviewUrl, WebviewWindow};

/// Builds an app from the real `tauri.conf.json` and the ACL manifest generated by
/// `build.rs`, so the test exercises the shipped capabilities rather than the empty
/// ACL of `mock_context`. No invoke handler is installed: an allowed command then
/// fails with "not found", which is distinguishable from an ACL rejection.
fn app_with_shipped_acl() -> App<MockRuntime> {
    mock_builder()
        .build(tauri::generate_context!())
        .expect("build mock app with shipped ACL")
}

/// Creates a webview window with the given label, loading the bundled app URL.
fn webview(app: &App<MockRuntime>, label: &str) -> WebviewWindow<MockRuntime> {
    WebviewWindowBuilder::new(app, label, WebviewUrl::App("index.html".into()))
        .build()
        .unwrap_or_else(|error| panic!("create webview {label}: {error}"))
}

/// Invokes `cmd` from `webview` as a local-origin request and returns the outcome.
fn invoke(webview: &WebviewWindow<MockRuntime>, cmd: &str) -> Result<InvokeResponseBody, String> {
    get_ipc_response(
        webview,
        InvokeRequest {
            cmd: cmd.to_owned(),
            callback: CallbackFn(0),
            error: CallbackFn(1),
            url: "tauri://localhost".parse().expect("local origin"),
            body: InvokeBody::default(),
            headers: Default::default(),
            invoke_key: INVOKE_KEY.to_owned(),
        },
    )
    .map_err(|error| {
        error
            .as_str()
            .map(str::to_owned)
            .unwrap_or_else(|| error.to_string())
    })
}

/// Classifies an IPC error message as an ACL rejection. Debug builds explain
/// which window/webview context is missing; release builds use a fixed message.
fn is_acl_rejection(message: &str) -> bool {
    message.contains("not allowed")
}

/// Verifies a `remote-surface:*` webview is denied app, plugin, and core commands.
#[test]
fn remote_surface_webview_is_denied_everything() {
    let app = app_with_shipped_acl();
    let remote = webview(&app, "remote-surface:test:market:1");

    let outcomes: Vec<(&str, bool)> = [
        "list_projects",
        "surface_open",
        "plugin:dialog|open",
        "core:event|emit",
    ]
    .into_iter()
    .map(|cmd| {
        let denied = match invoke(&remote, cmd) {
            Ok(_) => false,
            Err(message) => is_acl_rejection(&message),
        };
        (cmd, denied)
    })
    .collect();

    assert_eq!(
        outcomes,
        vec![
            ("list_projects", true),
            ("surface_open", true),
            ("plugin:dialog|open", true),
            ("core:event|emit", true),
        ]
    );
}

/// Verifies the `main` webview passes the ACL for an app command: without an invoke
/// handler the command is reported as missing, never as not allowed.
#[test]
fn main_webview_passes_acl_for_app_commands() {
    let app = app_with_shipped_acl();
    let main = webview(&app, "main");

    let error = invoke(&main, "list_projects").expect_err("no handler is installed");

    assert_eq!(
        (is_acl_rejection(&error), error.contains("not found")),
        (false, true),
        "unexpected error: {error}"
    );
}
