// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable receipt for durable acceptance, independent of eventual execution success.
 */
export type MiniCloneAccepted = {
  requestId: string;
  operationId: string;
  executionId: string;
};

/**
 * Known clone failure categories, without raw Git output or deployment credentials.
 */
export type MiniCloneFailure =
  | "sourceUnavailable"
  | "branchNotFound"
  | "destinationConflict"
  | "operationFailed"
  | "interrupted";

/**
 * One durable operation for list and detail views; paths remain Node-local facts.
 */
export type MiniCloneOperation = {
  operationId: string;
  executionId: string;
  nodeId: string;
  repository: string;
  branch: string;
  state: MiniCloneState;
};

/**
 * Public clone intent; target Node and deployment paths belong to server configuration.
 */
export type MiniCloneRequest = {
  requestId: string;
  repository: string;
  branch: string;
};

/**
 * Presentation of durable facts; pending does not assert that Node is connected or running Git.
 */
export type MiniCloneState = { "kind": "pending" } | {
  "kind": "succeeded";
  path: string;
  commit: string;
} | { "kind": "failed"; reason: MiniCloneFailure; retainedPath: string | null };

/**
 * Stable error envelope for the non-production HTTP adapter.
 */
export type MiniError = { code: MiniErrorCode };

/**
 * HTTP failures do not become terminal execution failures.
 */
export type MiniErrorCode =
  | "invalidInput"
  | "conflict"
  | "notFound"
  | "unavailable";
