// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lists Host MCP health for currently eligible installed members.
 *
 * An absent `cwd` is the plugin-card view; a present absolute `cwd` is the Session-banner view.
 */
export type ListMcpHealthRequest = { cwd: string | null };

/**
 * Eligible members and their current in-process health.
 */
export type ListMcpHealthResponse = { entries: Array<McpHealthEntry> };

/**
 * One secret-free health entry returned to clients.
 */
export type McpHealthEntry = {
  identity: McpHealthIdentity;
  status: McpHealthStatus;
};

/**
 * Closed Host MCP health failure codes.
 *
 * The family is deliberately separate from Session MCP setup codes (`mcp_setting_missing`,
 * `mcp_http_capability_missing`, …): a probe failure is a runtime observation and never a
 * delivery error. Adding a variant is an external compatibility change and requires a new
 * decision.
 */
export type McpHealthErrorCode =
  | "mcp_spawn_failed"
  | "mcp_exited_prematurely"
  | "mcp_handshake_failed"
  | "mcp_probe_timeout"
  | "mcp_tools_unavailable"
  | "mcp_http_unreachable"
  | "mcp_http_unauthorized"
  | "mcp_http_server_error";

/**
 * Secret-free identity of one MCP health cache entry.
 *
 * Aligns with the Session MCP member revision — canonical Plugin ID, exact package version,
 * configuration revision, and transport. Members whose arguments substitute
 * `{ "context": "workspace" }` also bind the absolute Session `cwd`; card-view identities leave
 * `cwd` absent so one Workspace's probe can never be presented as another's.
 */
export type McpHealthIdentity = {
  pluginId: string;
  packageVersion: string;
  configurationRevision: number;
  transport: McpHealthTransport;
  cwd: string | null;
};

/**
 * Host-observed MCP health outcome for one identity.
 *
 * This is Ora's own bounded observation, never the Agent's session-internal state: `Healthy`
 * means the Host completed `initialize` and `tools/list` against this binding product, not that
 * the Agent connected the server or that its tools are visible to the model.
 */
export type McpHealthStatus = { "status": "healthy" } | {
  "status": "unhealthy";
  error_code: McpHealthErrorCode;
} | { "status": "unknown"; reason: McpHealthUnknownReason };

/**
 * Transport carried by a health identity.
 */
export type McpHealthTransport = "stdio" | "http";

/**
 * Closed reasons an eligible member has no health result yet.
 */
export type McpHealthUnknownReason = "not_probed" | "context_missing";

/**
 * Requests one Host MCP health probe for a currently eligible member.
 *
 * Absent `cwd` is the card view, where a workspace-context member stays `context_missing`; a
 * present absolute `cwd` allows workspace-context substitution for a Session-scoped identity.
 */
export type ProbeMcpHealthRequest = { pluginId: string; cwd: string | null };

/**
 * Result of one awaited Host MCP health probe.
 */
export type ProbeMcpHealthResponse = { entry: McpHealthEntry };
