// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeLogLevel } from "./runtime-log-level.ts";

/**
 * Reads the effective Plugin log level of one plugin identity.
 */
export type GetPluginLogLevelRequest = { pluginId: string };

/**
 * The effective level and whether it comes from an explicit setting rather than the default.
 */
export type PluginLogLevelResponse = {
  pluginId: string;
  level: RuntimeLogLevel;
  configured: boolean;
};

/**
 * Persists and immediately applies a new Plugin log level to one plugin identity.
 */
export type SetPluginLogLevelRequest = {
  pluginId: string;
  level: RuntimeLogLevel;
};
