// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests process activation for one installed plugin.
 */
export type ActivatePluginRequest = { pluginId: string };

/**
 * Returns the immediate starting or already-running plugin snapshot.
 */
export type ActivatePluginResponse = { plugin: InstalledPlugin };

/**
 * Requests adding one marketplace Git source.
 *
 * New sources use Direct HTTPS retrieval. Configure S3 SigV4 and its credential pair with
 * `UpdateMarketplaceSourceRequest` after the source has been added.
 */
export type AddMarketplaceSourceRequest = {
  url: string;
  branch: string;
  useProxy: boolean;
};

/**
 * Returns the source list immediately after one source is persisted.
 */
export type AddMarketplaceSourceResponse = {
  sources: Array<MarketplaceSource>;
};

/**
 * Describes one marketplace plugin listed by the cached registry index.
 */
export type AvailablePlugin =
  & {
    id: string;
    name: string;
    /**
     * Human-readable display title declared by the manifest; falls back to `name` when a cached
     * index or older manifest omits it.
     */
    title: string;
    /**
     * The plugin kind (`agent`, `workbench`, `webview`, `skill`, `mcp`, or `hook`).
     */
    kind: string;
    namespace: string;
    /**
     * Canonical URL of the marketplace source that publishes this listing.
     *
     * Two sources may publish the same `identifier`, and both listings then appear side by side.
     * Every other field on the card — title, description, icon — comes from a manifest either
     * repository can copy verbatim, and `namespace` is a digest-suffixed slug that means nothing
     * to a reader, so this is the only field that lets the user tell the two cards apart.
     */
    sourceUrl: string;
    version: string;
    description: string;
    /**
     * Host-local asset URLs for the marketplace icon, absent when none is published.
     */
    logo: PluginLogo | null;
    /**
     * Declared member identifiers when this listing is a pack (`kind = "pack"`), absent for
     * every other kind. Display data only: the ownership journal stays the authority for
     * what a pack installation actually created.
     */
    packMembers?: Array<string>;
  }
  & ({ "compatibility": "compatible" } | {
    "compatibility": "incompatible";
    reason: string;
  });

/**
 * Requests removal of one marketplace Git source by its URL.
 */
export type DeleteMarketplaceSourceRequest = { url: string };

/**
 * Returns the source list immediately after one source is removed.
 */
export type DeleteMarketplaceSourceResponse = {
  sources: Array<MarketplaceSource>;
};

/**
 * Requests the current editor snapshot for one installed plugin.
 */
export type GetPluginConfigurationRequest = { pluginId: string };

/**
 * Returns the resolved editor snapshot without exposing its filesystem location.
 */
export type GetPluginConfigurationResponse = {
  configuration: PluginConfigurationDetails;
};

/**
 * Reports how one lifecycle execution ended.
 *
 * The two states are a closed enum rather than a success flag plus optional error text so a
 * caller cannot observe a failure without a reason to show the user.
 */
export type HookLifecycleOutcome = {
  "state": "succeeded";
  /**
   * Wall-clock time the command took, so a slow tool is visible without reading logs.
   */
  durationMs: number;
} | {
  "state": "failed";
  /**
   * The process exit code, absent when the command was killed or never started.
   */
  exitCode: number | null;
  /**
   * Wall-clock time the attempt took, including the timeout that ended it.
   */
  durationMs: number;
  /**
   * Why the attempt failed, shown to the user so retrying is an informed decision.
   */
  reason: string;
};

/**
 * Names one lifecycle phase a Hook package declares a command for.
 */
export type HookLifecyclePhase = "init" | "deinit";

/**
 * Describes the most recent lifecycle execution the host performed for one installed package.
 *
 * The result is keyed by plugin rather than by phase: an update re-runs `init`, and an uninstall
 * runs `deinit` immediately before the package disappears, so only the latest execution is ever
 * meaningful to a reader. A Hook the host has never executed for has no report at all, which is
 * how a pack-installed member reports "not initialized" without the pack path having to run
 * anything (D2).
 */
export type HookLifecycleReport = {
  pluginId: string;
  phase: HookLifecyclePhase;
  /**
   * The package-relative executable that ran, so the result stays tied to the disclosure the
   * user authorized even if a later version of the package ships a different one.
   */
  executable: string;
  outcome: HookLifecycleOutcome;
  /**
   * The command's captured `stderr`, bounded by the host's capture limit and trimmed.
   *
   * A tool that refuses to install its Hook explains why on its error stream, so the failure
   * stays actionable in the UI instead of only in the host logs. Empty when the command wrote
   * nothing or never started.
   */
  output: string;
  /**
   * Whether `output` was cut at the host's capture limit.
   */
  outputTruncated: boolean;
};

/**
 * Requests importing one local `.orax` release archive into the installed plugins tree.
 */
export type ImportPluginRequest = {
  /**
   * Absolute path to the local `.orax` archive.
   */
  path: string;
  /**
   * Declares that the user authorized the Hook lifecycle command this import would run; see
   * [`InstallPluginRequest::hook_execution_acknowledged`].
   */
  hookExecutionAcknowledged: boolean;
};

/**
 * Confirms the identifier imported after the archive is verified and extracted.
 */
export type ImportPluginResponse = {
  pluginId: string;
  /**
   * The typed installation outcome, identical in shape to a marketplace install.
   */
  outcome: InstallOutcome;
};

/**
 * Requests the `init` lifecycle command of one installed Hook package.
 *
 * This is the retry path for a failed `init` and the only way a pack-installed Hook member is
 * ever initialized: a pack install lands packages without running anything (D2), so the user
 * authorizes each member individually afterwards.
 */
export type InitializeHookRequest = {
  pluginId: string;
  /**
   * Declares that the user authorized this execution; see
   * [`InstallPluginRequest::hook_execution_acknowledged`](crate::InstallPluginRequest).
   */
  hookExecutionAcknowledged: boolean;
};

/**
 * Returns the result of the initialization the caller asked for.
 */
export type InitializeHookResponse = { report: HookLifecycleReport };

/**
 * Models the closed set of installation outcomes.
 *
 * The outcome is a closed enum rather than a pair of booleans so a caller can never observe
 * contradictory success flags. Installation always succeeds and the package remains available.
 */
export type InstallOutcome = { "state": "installed" } | {
  "state": "pack_installed";
  /**
   * Applicable members that were installed by this operation, in declaration order.
   */
  members: Array<string>;
  /**
   * Applicable members that were already installed (any version) and therefore skipped;
   * their existing versions were left untouched.
   */
  skipped: Array<string>;
  /**
   * The first member that failed, when one did; members after it were not attempted.
   */
  failed: PackInstallFailure | null;
};

/**
 * Requests installation of one marketplace plugin by its registry identifier.
 */
export type InstallPluginRequest = {
  pluginId: string;
  /**
   * Declares that the user authorized the Hook lifecycle command this operation would run.
   *
   * The flag is the request-side form of the confirmation dialog the user answered. It is a
   * process gate rather than a security boundary — the host still re-validates the package
   * before every spawn — and it defaults to "not authorized" so a caller that never learned
   * about Hook execution cannot silently start a package's program. The install itself is
   * always authorized: without the declaration the package still lands, its `init` simply does
   * not run until the user asks for it explicitly.
   */
  hookExecutionAcknowledged: boolean;
};

/**
 * Confirms the identifier installed after download, verification, and extraction complete.
 */
export type InstallPluginResponse = {
  pluginId: string;
  /**
   * The typed installation outcome. Installation always retains the package and never executes
   * anything the package ships; a Hook's lifecycle commands run only on an explicitly
   * authorized single-plugin operation.
   */
  outcome: InstallOutcome;
};

/**
 * Describes one installed plugin discovered from its `orax.toml` manifest.
 *
 * `id` is the canonical `<namespace>/<name>` spelling and is what every plugin request carries
 * back; `namespace` and `name` repeat the two segments so the frontend never has to split it.
 */
export type InstalledPlugin =
  & {
    id: string;
    namespace: string;
    name: string;
    displayName: string;
    version: string;
    description: string;
    homepage: string | null;
    license: string | null;
    /**
     * Host-local asset URLs for the package icon, absent when the package ships none.
     */
    logo: PluginLogo | null;
    installationValidity: PluginInstallationValidity;
    configuration: PluginConfigurationSummary;
  }
  & (
    | { "kind": "agent"; agentDisplayName: string }
    | { "kind": "workbench"; title: string }
    | { "kind": "webview"; title: string; startUrl: string }
    | { "kind": "skill" }
    | { "kind": "mcp" }
    | {
      "kind": "hook";
      /**
       * The package-relative executable path the host runs. It is always inside the installed
       * package; the path is shown so the user can see which file the disclosure refers to.
       */
      executable: string;
      /**
       * Agent identifiers the author claims the tool supports. Display only: the host validates
       * their shape and never matches them against Agents it knows about.
       */
      supportedAgents: Array<string>;
      /**
       * The target triple the installed physical artifact self-declares, absent for a
       * universal release.
       */
      target: string | null;
    }
  )
  & ({ "runtime": "stopped" } | { "runtime": "starting" } | {
    "runtime": "running";
  } | { "runtime": "failed"; failureReason: string });

/**
 * Describes the kind-specific contribution of one installed plugin, discriminated by `kind`.
 *
 * The agent variant names its display name `agentDisplayName` because the contribution is
 * flattened into [`InstalledPlugin`], which already owns the top-level `displayName`. The two
 * surface kinds expose only what the launcher needs to render an entry: the frontend never
 * learns asset paths, origin allow lists, or download rules, which is what keeps those host
 * policies non-negotiable from the page side.
 */
export type InstalledPluginContribution =
  | { "kind": "agent"; agentDisplayName: string }
  | { "kind": "workbench"; title: string }
  | { "kind": "webview"; title: string; startUrl: string }
  | { "kind": "skill" }
  | { "kind": "mcp" }
  | {
    "kind": "hook";
    /**
     * The package-relative executable path the host runs. It is always inside the installed
     * package; the path is shown so the user can see which file the disclosure refers to.
     */
    executable: string;
    /**
     * Agent identifiers the author claims the tool supports. Display only: the host validates
     * their shape and never matches them against Agents it knows about.
     */
    supportedAgents: Array<string>;
    /**
     * The target triple the installed physical artifact self-declares, absent for a
     * universal release.
     */
    target: string | null;
  };

/**
 * Requests the cached marketplace registry index used to populate the plugin catalog.
 */
export type ListAvailablePluginsRequest = Record<symbol, never>;

/**
 * Returns the marketplace plugins cached in the registry index.
 */
export type ListAvailablePluginsResponse = {
  updatedAt: bigint;
  plugins: Array<AvailablePlugin>;
};

/**
 * Requests this session's Hook lifecycle results.
 */
export type ListHookLifecycleReportsRequest = Record<symbol, never>;

/**
 * Returns one result per Hook package this session has executed a command for.
 *
 * Packages with no result are absent rather than reported as a state of their own: the caller
 * distinguishes "never ran" from "ran and failed" by presence, which is the same distinction the
 * host makes.
 */
export type ListHookLifecycleReportsResponse = {
  reports: Array<HookLifecycleReport>;
};

/**
 * Requests the immutable startup snapshot of installed plugin packages.
 */
export type ListInstalledPluginsRequest = Record<symbol, never>;

/**
 * Returns every valid installed plugin in stable identifier order.
 */
export type ListInstalledPluginsResponse = { plugins: Array<InstalledPlugin> };

/**
 * Requests the configured marketplace source repositories.
 */
export type ListMarketplaceSourcesRequest = Record<symbol, never>;

/**
 * Returns every configured marketplace source in source-precedence order.
 */
export type ListMarketplaceSourcesResponse = {
  sources: Array<MarketplaceSource>;
};

/**
 * Requests every recorded pack installation with its reconciled member states.
 */
export type ListPackInstallationsRequest = Record<symbol, never>;

/**
 * Returns every recorded pack installation, each member reconciled against the installed
 * tree. Read-only: reconciliation identifies drift, it never repairs the journal or the
 * installed tree.
 */
export type ListPackInstallationsResponse = {
  packs: Array<PackInstallationStatus>;
};

/**
 * Describes how one marketplace source retrieves its `.orax` release artifacts.
 *
 * The S3 variant deliberately excludes credentials: source queries may populate editors and
 * logs, so secrets remain write-only outside the backend persistence boundary.
 */
export type MarketplaceArtifactRetrieval = { "type": "direct_https" } | {
  "type": "s3_sigv4";
  endpoint: string;
  bucket: string;
  region: string;
};

/**
 * Carries the complete artifact-retrieval state submitted by the source editor.
 */
export type MarketplaceArtifactRetrievalUpdate = { "type": "direct_https" } | {
  "type": "s3_sigv4";
  endpoint: string;
  bucket: string;
  region: string;
  credentials: MarketplaceS3CredentialsUpdate;
};

/**
 * Selects whether an S3 source update retains or atomically replaces its credential pair.
 *
 * # Security
 *
 * `Serialize` emits plaintext credentials for IPC transport to the backend, including when
 * this value is nested in an update request. Never serialize it into logs, traces, or telemetry.
 * Only the manual `Debug` implementation redacts the credential pair.
 */
export type MarketplaceS3CredentialsUpdate = { "action": "preserve" } | {
  "action": "replace";
  accessKeyId: string;
  secretAccessKey: string;
};

/**
 * Lists one configured marketplace source repository and its tracked branch.
 */
export type MarketplaceSource = {
  /**
   * HTTPS Git repository URL of the marketplace checkout.
   */
  url: string;
  /**
   * Short branch name tracked by the source.
   */
  branch: string;
  /**
   * Whether Git fetches and plugin downloads for this source use the configured proxy.
   */
  useProxy: boolean;
  /**
   * Whether this source participates in marketplace sync, listing, and install.
   */
  enabled: boolean;
  /**
   * Release-artifact retrieval policy, with S3 credentials omitted.
   */
  artifactRetrieval: MarketplaceArtifactRetrieval;
};

/**
 * Identifies the first pack member whose installation failed and the classified reason.
 */
export type PackInstallFailure = {
  pluginId: string;
  /**
   * The stable public error code the member's install failure classified as.
   */
  errorCode: string;
  /**
   * Members created before the original failure whose rollback also failed, in creation
   * order. These members remain installed and are journaled as pack-managed so a later
   * uninstall or retry can recover. Empty when the rollback completed.
   */
  rollbackFailures: Array<PackRollbackFailure>;
};

/**
 * One recorded pack installation projected for the installed-packs presentation.
 */
export type PackInstallationStatus = {
  /**
   * Canonical `namespace/identifier` of the pack listing.
   */
  packId: string;
  /**
   * Canonical URL of the marketplace source the pack was installed from.
   */
  sourceUrl: string;
  /**
   * Every journaled member, reconciled against the installed tree.
   */
  members: Array<PackMemberStatus>;
};

/**
 * Whether the pack installation created this member or found it already installed.
 */
export type PackMemberOwnership = "managed_by_pack" | "pre_existing";

/**
 * The reconciled state of one journaled pack member against the installed tree.
 */
export type PackMemberReconciliationState =
  | { "state": "expected_and_present" }
  | { "state": "version_changed"; currentVersion: string }
  | { "state": "missing" };

/**
 * One journaled pack member with its reconciled state.
 */
export type PackMemberStatus = {
  memberId: string;
  /**
   * The member version at the moment the pack relationship was established.
   */
  versionAtInstall: string;
  ownership: PackMemberOwnership;
  state: PackMemberReconciliationState;
};

/**
 * One member whose rollback failed during a failed pack install.
 */
export type PackRollbackFailure = {
  pluginId: string;
  /**
   * The stable public error code the member's rollback failure classified as.
   */
  errorCode: string;
};

/**
 * The computed, not-yet-executed uninstall plan for one recorded pack.
 */
export type PackUninstallPlan = {
  /**
   * Members the pack created at their recorded versions: safe to remove.
   */
  remove: Array<string>;
  /**
   * Members preserved with the structured reason the UI presents.
   */
  preserve: Array<PackUninstallPreservation>;
  /**
   * Managed members that are already absent: released without filesystem work.
   */
  alreadyMissing: Array<string>;
};

/**
 * Requests the ownership-aware uninstall plan for one pack id.
 */
export type PackUninstallPlanRequest = { pluginId: string };

/**
 * Returns the ownership-aware uninstall plan, absent when the id has no journal.
 */
export type PackUninstallPlanResponse = { plan: PackUninstallPlan | null };

/**
 * One preserved member and why the pack uninstall leaves it alone.
 */
export type PackUninstallPreservation = {
  memberId: string;
  reason: PackUninstallPreservationReason;
};

/**
 * Why a pack uninstall preserves a member.
 */
export type PackUninstallPreservationReason =
  | "pre_existing"
  | "version_changed";

/**
 * Reports whether every required Setting has an effective type-correct value.
 */
export type PluginConfigurationCompleteness = "complete" | "incomplete";

/**
 * Carries one complete editor snapshot bound to a revision and declaration fingerprint.
 */
export type PluginConfigurationDetails = {
  pluginId: string;
  schemaVersion: number;
  revision: bigint;
  declarationFingerprint: string;
  settings: Array<PluginSettingDetails>;
  summary: PluginConfigurationSummary;
};

/**
 * Represents the exclusive list-facing Plugin Configuration state.
 */
export type PluginConfigurationSummary = { "state": "not_declared" } | {
  "state": "available";
  completeness: PluginConfigurationCompleteness;
} | { "state": "unavailable"; errorCode: string };

/**
 * Selects whether uninstall retains or deletes host-owned plugin data.
 */
export type PluginDataDisposition = "delete" | "retain";

/**
 * Reports whether the current host can install one marketplace listing.
 *
 * A universal release is always compatible. A targeted release is compatible only when the host
 * target has a matching artifact. A listing with no downloadable release is incompatible.
 */
export type PluginHostCompatibility = { "compatibility": "compatible" } | {
  "compatibility": "incompatible";
  reason: string;
};

/**
 * Represents whether the installed package and its immutable declaration are usable.
 */
export type PluginInstallationValidity = { "validity": "valid" } | {
  "validity": "invalid_declaration";
  errorCode: string;
};

/**
 * Locates one plugin's icon as host-local asset URLs, never as icon content.
 *
 * The host serves the bytes from its own `ora-plugin` protocol, so the payload of every listing
 * stays constant no matter how large or how many icons there are, the bytes of a listing that
 * is never drawn are never read, and the icon's format stops being visible to the contract at
 * all — which is what lets an icon be a bitmap rather than only inline SVG source.
 *
 * The two shapes are an enum rather than a pair of optional URLs so that a half-built theme
 * pair cannot be expressed: the host decides once which files back which theme, and the
 * renderer only picks a branch. `Universal` is drawn under both themes; `Themed` always carries
 * both halves, which may come from different files and different image formats.
 */
export type PluginLogo = { "variant": "universal"; url: string } | {
  "variant": "themed";
  light: string;
  dark: string;
};

/**
 * Represents the process-scoped lifecycle of one installed plugin.
 */
export type PluginRuntimeStatus =
  | { "runtime": "stopped" }
  | { "runtime": "starting" }
  | { "runtime": "running" }
  | { "runtime": "failed"; failureReason: string };

/**
 * Describes one immutable plugin-authored Setting.
 */
export type PluginSettingDeclaration = {
  id: string;
  title: string;
  description: string;
  type: PluginSettingType;
  required: boolean;
  order: bigint | null;
  default: PluginSettingValue | null;
};

/**
 * Projects one Setting into an editor field without exposing raw files.
 */
export type PluginSettingDetails = {
  declaration: PluginSettingDeclaration;
  storedValue: PluginSettingValue | null;
  effectiveValue: PluginSettingValue | null;
  /**
   * True when the host deliberately withholds a value used by an MCP process.
   */
  redacted: boolean;
  source: PluginSettingValueSource;
  valueErrorCode: string | null;
};

/**
 * Enumerates Setting types supported by declaration schema version one.
 */
export type PluginSettingType = "string" | "number" | "boolean";

/**
 * Carries one non-secret scalar override accepted by schema version one.
 */
export type PluginSettingValue = string | number | boolean;

/**
 * Identifies the source of one effective editor value.
 */
export type PluginSettingValueSource = "stored" | "default" | "absent";

/**
 * Requests the README one marketplace listing publishes beside its `orax.toml`.
 */
export type ReadPluginReadmeRequest = {
  /**
   * The canonical `namespace/name` marketplace identifier.
   */
  pluginId: string;
};

/**
 * Returns the README text the winning marketplace source publishes, absent when none ships.
 */
export type ReadPluginReadmeResponse = { readme: string | null };

/**
 * Selects the explicit reset operation authorized by the user.
 */
export type ResetPluginConfigurationMode = {
  "mode": "reset_all";
  expectedRevision: bigint;
} | { "mode": "recover_corrupt" };

/**
 * Requests Reset All or confirmed damaged-data recovery for one plugin.
 */
export type ResetPluginConfigurationRequest =
  & { pluginId: string; declarationFingerprint: string }
  & ({ "mode": "reset_all"; expectedRevision: bigint } | {
    "mode": "recover_corrupt";
  });

/**
 * Returns the authoritative editor snapshot after a reset operation.
 */
export type ResetPluginConfigurationResponse = {
  configuration: PluginConfigurationDetails;
};

/**
 * Replaces every explicit override recognized by the loaded declaration.
 */
export type SavePluginConfigurationRequest = {
  pluginId: string;
  expectedRevision: bigint;
  declarationFingerprint: string;
  values: { [key in string]: PluginSettingValue };
  /**
   * Host-redacted stored values that an unchanged editor must retain.
   */
  preserveSettingIds: Array<string>;
};

/**
 * Returns the authoritative post-save editor snapshot and list summary.
 */
export type SavePluginConfigurationResponse = {
  configuration: PluginConfigurationDetails;
};

/**
 * Requests explicit filesystem discovery and state reconciliation.
 */
export type ScanPluginsRequest = Record<symbol, never>;

/**
 * Returns the refreshed installed-plugin snapshot produced by an explicit scan.
 */
export type ScanPluginsResponse = { plugins: Array<InstalledPlugin> };

/**
 * Requests process shutdown while leaving the installed plugin available.
 */
export type StopPluginRequest = { pluginId: string };

/**
 * Returns the stopped plugin snapshot after process exit is confirmed.
 */
export type StopPluginResponse = { plugin: InstalledPlugin };

/**
 * Requests a marketplace source sync followed by an atomic registry-index rebuild.
 */
export type SyncAvailablePluginsRequest = Record<symbol, never>;

/**
 * Returns the registry index rebuilt immediately after a marketplace sync succeeds.
 */
export type SyncAvailablePluginsResponse = {
  updatedAt: bigint;
  plugins: Array<AvailablePlugin>;
};

/**
 * Requests complete removal of one plugin package and its durable lifecycle state.
 */
export type UninstallPluginRequest = {
  pluginId: string;
  dataDisposition: PluginDataDisposition;
  /**
   * Declares that the user authorized the `deinit` command this removal would run; see
   * [`InstallPluginRequest::hook_execution_acknowledged`].
   */
  hookExecutionAcknowledged: boolean;
};

/**
 * Confirms the identifier removed after process shutdown and package deletion complete.
 */
export type UninstallPluginResponse = { pluginId: string };

/**
 * Requests replacing the editable fields of one marketplace source.
 *
 * `url` identifies the persisted row. `new_url` is the replacement Git address and may equal
 * `url` when only branch, proxy policy, or enabled state changes.
 */
export type UpdateMarketplaceSourceRequest = {
  url: string;
  newUrl: string;
  branch: string;
  useProxy: boolean;
  enabled: boolean;
  artifactRetrieval: MarketplaceArtifactRetrievalUpdate;
};

/**
 * Returns the source list immediately after one source is updated.
 */
export type UpdateMarketplaceSourceResponse = {
  sources: Array<MarketplaceSource>;
};

/**
 * Requests updating one installed marketplace plugin to the version its source publishes.
 */
export type UpdatePluginRequest = {
  pluginId: string;
  /**
   * Declares that the user authorized the `init` command this update would run; every update
   * re-runs it, because only the tool knows whether the new version needs a migration. See
   * [`InstallPluginRequest::hook_execution_acknowledged`].
   */
  hookExecutionAcknowledged: boolean;
};

/**
 * Confirms the identifier updated after the new release is verified and stale versions removed.
 */
export type UpdatePluginResponse = { pluginId: string };
