// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the running run whose node sessions should be stopped and run cancelled.
 */
export type CancelWorkflowRunRequest = { runId: string };

/**
 * Returns the cancelled run.
 */
export type CancelWorkflowRunResponse = { run: WorkflowRun };

/**
 * Identifies the awaiting interactive node to complete.
 */
export type CompleteWorkflowNodeRequest = {
  runId: string;
  nodeId: string;
  requester?: NodeCompletionRequester;
};

/**
 * Returns the run after the node completed.
 */
export type CompleteWorkflowNodeResponse = { run: WorkflowRun };

/**
 * Carries the fields required to create a workflow run against a published snapshot and workspace.
 */
export type CreateWorkflowRunRequest = {
  workspaceId: string;
  workflowId: string;
  locale: WorkflowRunLocale;
  snapshotId?: string;
  kickoffInput?: string;
  name?: string;
  /**
   * `None` means inject last-failure context (the same as `Some(true)`).
   */
  injectLastFailure?: boolean;
};

/**
 * Returns the created workspace-owned run.
 */
export type CreateWorkflowRunResponse = { run: WorkflowRun };

/**
 * Identifies the workflow run to soft-delete.
 */
export type DeleteWorkflowRunRequest = { runId: string };

/**
 * Returns the identifier of the soft-deleted run.
 */
export type DeleteWorkflowRunResponse = { runId: string };

/**
 * Identifies the failed agent node whose one-off AI diagnosis should be generated.
 */
export type DiagnoseWorkflowNodeFailureRequest = {
  runId: string;
  nodeId: string;
};

/**
 * Returns the generated diagnosis; nothing in scheduling or resume reads this value.
 */
export type DiagnoseWorkflowNodeFailureResponse = {
  diagnosis: WorkflowNodeAiDiagnosis;
};

/**
 * Identifies the workflow run to retrieve by its stable identifier.
 */
export type GetWorkflowRunRequest = { runId: string };

/**
 * Returns the full run detail including its display name and node runs.
 */
export type GetWorkflowRunResponse = {
  run: WorkflowRun;
  name: string;
  workspaceId: string;
  projectId: string;
  nodes: Array<WorkflowNodeRun>;
  /**
   * Loop round identities; internal variable pools and branch decisions remain private.
   */
  scopes?: Array<WorkflowExecutionScope>;
  /**
   * Typed variable-pool projection; persistence metadata remains internal.
   */
  variables: Array<WorkflowRunVariable>;
  /**
   * Condition decisions keyed by node id for branch-aware rendering.
   */
  conditionDecisions: { [key in string]: string };
};

/**
 * Identifies the run whose node-run history to retrieve.
 */
export type ListWorkflowNodeRunsRequest = { runId: string };

/**
 * Returns the node-run records of one run.
 */
export type ListWorkflowNodeRunsResponse = { nodes: Array<WorkflowNodeRun> };

/**
 * Requests the workflow run summaries for one workflow.
 */
export type ListWorkflowRunsByWorkflowRequest = { workflowId: string };

/**
 * Returns the visible run summaries for the workflow.
 */
export type ListWorkflowRunsByWorkflowResponse = {
  runs: Array<WorkflowRunSummary>;
};

/**
 * Requests the workflow run summaries for one project.
 */
export type ListWorkflowRunsRequest = { projectId: string };

/**
 * Returns the visible run summaries for the project.
 */
export type ListWorkflowRunsResponse = { runs: Array<WorkflowRunSummary> };

/**
 * Who requested the completion of one workflow node.
 *
 * Phase 1 carries only the human path; the agent/CLI path reuses the same command later.
 */
export type NodeCompletionRequester = "human";

/**
 * Identifies the failed or cancelled run whose resume preview should be loaded.
 */
export type PreviewWorkflowRunResumeRequest = { runId: string };

/**
 * Describes whether a run can be resumed and which rollback modes are available.
 */
export type PreviewWorkflowRunResumeResponse = {
  /**
   * Run is failed/cancelled, no running node, and at least one failed/cancelled node.
   */
  resumable: boolean;
  failedNodes: Array<ResumeFailedNodePreview>;
  /**
   * Every failed node has a checkpoint.
   */
  nodeFilesAvailable: boolean;
  /**
   * `"no_file_changes"` when a failed node has no checkpoint / recorded changes;
   * `"composite_region"` when the resume unit is an iteration composite.
   */
  nodeFilesUnavailableReason: string | null;
  /**
   * Available when the run is resumable, the resume unit has a checkpoint, and no live node
   * run outside that unit was still active after the unit's earliest start (`finished_at` is
   * none or later than that instant, or `started_at` is later). Start/Condition/Output rows
   * that finished before the unit started do not count.
   */
  checkpointAvailable: boolean;
  /**
   * `"no_checkpoint"` | `"siblings_ran_after_checkpoint"` | `"not_resumable"`.
   */
  checkpointUnavailableReason: string | null;
  currentSnapshotId: string;
  currentSnapshotVersion: string;
  publishedSnapshotId: string | null;
  publishedSnapshotVersion: string | null;
  publishedSnapshotSwitchable: boolean;
  publishedSnapshotIncompatibleReason: string | null;
};

/**
 * Identifies the workflow run whose Workspace-owned display name should change.
 */
export type RenameWorkflowRunRequest = { runId: string; name: string };

/**
 * Returns the workflow run after its display name was replaced.
 */
export type RenameWorkflowRunResponse = { run: WorkflowRun };

/**
 * Identifies the non-running run to reset and re-run from its start node.
 */
export type RestartWorkflowRunRequest = { runId: string };

/**
 * Returns the reset and re-running run.
 */
export type RestartWorkflowRunResponse = { run: WorkflowRun };

/**
 * Preview of one failed or cancelled node that would be re-run.
 */
export type ResumeFailedNodePreview = {
  nodeId: string;
  nodeRunId: string;
  startedAt: bigint | null;
  checkpoint: string | null;
  checkpointError: string | null;
  /**
   * What the node itself recorded (`payload.file_changes` of the failed run).
   */
  nodeFileChanges: Array<WorkflowFileChange>;
  /**
   * Live diff of the worktree against this node's checkpoint (includes edits made after the failure).
   */
  changedSinceCheckpoint: Array<WorkflowFileChange>;
  /**
   * Owning composite node id when this row belongs to an iteration resume unit.
   */
  resumeUnitNodeId?: string;
};

/**
 * How the worktree is treated before a failed run is resumed.
 */
export type ResumeRollbackMode = "keep" | "node_files" | "checkpoint";

/**
 * Identifies the failed or cancelled run to resume from its failed nodes.
 */
export type ResumeWorkflowRunRequest = {
  runId: string;
  /**
   * `None` keeps the worktree as it is.
   */
  rollback?: ResumeRollbackMode;
  /**
   * `None` keeps the run on its current snapshot.
   */
  snapshotId?: string;
};

/**
 * Returns the resumed and re-running run.
 */
export type ResumeWorkflowRunResponse = {
  run: WorkflowRun;
  preRollbackCheckpoint: string | null;
};

/**
 * Identifies the run to start executing against its frozen snapshot graph.
 */
export type StartWorkflowRunRequest = { runId: string };

/**
 * Returns the run after starting (or idempotently its current state).
 */
export type StartWorkflowRunResponse = { run: WorkflowRun };

/**
 * Sets the kickoff input of a pending run, used as the start node's input on start.
 */
export type UpdateWorkflowRunInputRequest = {
  runId: string;
  input: string | null;
  /**
   * Start-variable values keyed by their declared short name; JSON null clears an assignment.
   */
  variables?: Record<string, unknown>;
};

/**
 * Returns the run with its updated input.
 */
export type UpdateWorkflowRunInputResponse = { run: WorkflowRun };

/**
 * Public Loop-round identity used to group repeated node definitions in run history.
 */
export type WorkflowExecutionScope = {
  id: string;
  runId: string;
  parentLoopNodeRunId: string;
  roundIndex: number;
  status: WorkflowExecutionScopeStatus;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Lifecycle state of one persisted Loop round.
 */
export type WorkflowExecutionScopeStatus =
  | "pending"
  | "running"
  | "succeeded"
  | "failed"
  | "cancelled";

/**
 * One file's incremental change, matching the node payload `file_changes` shape.
 */
export type WorkflowFileChange = {
  path: string;
  additions: bigint;
  deletions: bigint;
};

/**
 * Plain-text diagnosis stored on the node run as `payload.ai_diagnosis` and shown as an AI guess.
 */
export type WorkflowNodeAiDiagnosis = {
  text: string;
  agentCli: string;
  model: string;
  generatedAt: bigint;
};

/**
 * Public node-run payload without persistence audit metadata.
 */
export type WorkflowNodeRun = {
  id: string;
  runId: string;
  scopeId: string;
  nodeId: string;
  nodeType: string;
  sessionId: string | null;
  status: WorkflowNodeStatus;
  input: string | null;
  output: string | null;
  error: string | null;
  payload: string | null;
  /**
   * Composite-region round this row executed in; `null` for outer rows. A region node holds
   * one row per round, so the run view groups states by `(node_id, iteration)`.
   */
  iteration: number | null;
  startedAt: bigint | null;
  finishedAt: bigint | null;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Describes the lifecycle state of one node execution in the public contract.
 */
export type WorkflowNodeStatus =
  | "pending"
  | "running"
  | "succeeded"
  | "failed"
  | "cancelled";

/**
 * Public workflow run payload without persistence audit metadata.
 */
export type WorkflowRun = {
  id: string;
  workspaceId: string;
  workflowId: string;
  snapshotId: string;
  name: string;
  status: WorkflowRunStatus;
  state: string | null;
  input: string | null;
  output: string | null;
  error: string | null;
  startedAt: bigint | null;
  finishedAt: bigint | null;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Identifies the Ora display language frozen for generated workflow-run prompts.
 */
export type WorkflowRunLocale = "zh-CN" | "en-US";

/**
 * Describes the lifecycle state of a workflow run in the public contract.
 */
export type WorkflowRunStatus =
  | "pending"
  | "running"
  | "succeeded"
  | "failed"
  | "cancelled"
  | "awaitingInput";

/**
 * Lightweight run summary for list views with direct workspace ownership.
 */
export type WorkflowRunSummary = {
  id: string;
  name: string;
  workspaceId: string;
  projectId: string;
  workflowId: string;
  /**
   * The published snapshot version the run froze, distinguishing runs created from different
   * versions of the same workflow.
   */
  version: string;
  status: WorkflowRunStatus;
  startedAt: bigint | null;
  finishedAt: bigint | null;
  createdAt: bigint;
};

/**
 * One declared run variable and its optional current value.
 */
export type WorkflowRunVariable = {
  selector: Array<string>;
  valueType: string;
  sourceNodeId: string;
  value?: unknown;
};
