import type { Agent, Skill } from "@ora/contracts";

/**
 * Stable identifiers let the settings UI keep prototype records local while real
 * records continue to use the backend CRUD path.
 */
export const MOCK_ATOM_ID_PREFIX = "mock-catalog-";

export const MOCK_AGENTS = [
  { id: "mock-catalog-role-product-strategist", name: "产品策略师", description: "梳理市场机会、用户价值与商业目标，形成可执行的产品路线图。" },
  { id: "mock-catalog-role-user-researcher", name: "用户研究员", description: "设计访谈与可用性研究，从真实反馈中提炼关键洞察。" },
  { id: "mock-catalog-role-growth-advisor", name: "增长顾问", description: "分析转化漏斗与留存路径，提出可验证的增长实验。" },
  { id: "mock-catalog-role-requirement-analyst", name: "需求分析师", description: "澄清业务目标、边界与验收标准，将模糊想法转成需求。" },
  { id: "mock-catalog-role-project-manager", name: "项目经理", description: "拆解里程碑、依赖和风险，帮助团队保持稳定交付节奏。" },
  { id: "mock-catalog-role-business-analyst", name: "商业分析师", description: "评估商业模式、成本收益与竞争格局，辅助关键决策。" },
  { id: "mock-catalog-role-content-strategist", name: "内容策略师", description: "规划内容主题、渠道与表达方式，让信息更一致、更有效。" },
  { id: "mock-catalog-role-experience-designer", name: "体验设计师", description: "从任务流到界面细节优化端到端体验与可用性。" },
  { id: "mock-catalog-role-service-designer", name: "服务设计师", description: "梳理跨触点服务蓝图，发现流程断点并设计协同方案。" },
  { id: "mock-catalog-role-accessibility-consultant", name: "无障碍顾问", description: "依据可访问性原则检查交互、内容和前端实现。" },
  { id: "mock-catalog-role-frontend-architect", name: "前端架构师", description: "设计可维护的前端架构、状态边界与组件协作方式。" },
  { id: "mock-catalog-role-backend-architect", name: "后端架构师", description: "规划服务边界、数据模型和可靠的接口契约。" },
  { id: "mock-catalog-role-fullstack-engineer", name: "全栈工程师", description: "跨前后端完成需求实现，并关注数据流与部署闭环。" },
  { id: "mock-catalog-role-rust-expert", name: "Rust 专家", description: "以类型安全、性能和可测试性为重点审查 Rust 代码。" },
  { id: "mock-catalog-role-typescript-expert", name: "TypeScript 专家", description: "构建清晰的类型边界，减少运行时错误与隐式约定。" },
  { id: "mock-catalog-role-api-designer", name: "API 设计师", description: "定义一致、可演进且便于调用者理解的接口协议。" },
  { id: "mock-catalog-role-database-expert", name: "数据库专家", description: "优化数据模型、索引与查询，兼顾一致性和扩展性。" },
  { id: "mock-catalog-role-desktop-engineer", name: "桌面端工程师", description: "处理原生能力、跨平台差异和桌面应用性能问题。" },
  { id: "mock-catalog-role-mobile-engineer", name: "移动端工程师", description: "围绕移动设备约束设计流畅、可靠的客户端体验。" },
  { id: "mock-catalog-role-solution-architect", name: "解决方案架构师", description: "将业务约束映射为系统能力、集成路径与交付方案。" },
  { id: "mock-catalog-role-code-reviewer", name: "代码审查员", description: "识别正确性、维护性与安全风险，并给出具体修改建议。" },
  { id: "mock-catalog-role-test-architect", name: "测试架构师", description: "规划测试分层、覆盖范围和稳定的自动化验证策略。" },
  { id: "mock-catalog-role-quality-engineer", name: "质量工程师", description: "从需求到发布建立质量门禁，降低缺陷逃逸风险。" },
  { id: "mock-catalog-role-performance-engineer", name: "性能工程师", description: "定位延迟、吞吐和资源瓶颈，设计可量化的优化方案。" },
  { id: "mock-catalog-role-debugging-specialist", name: "故障诊断专家", description: "根据日志、指标与复现线索系统定位复杂故障。" },
  { id: "mock-catalog-role-release-manager", name: "发布经理", description: "检查变更范围、回滚准备与发布风险，保障平稳上线。" },
  { id: "mock-catalog-role-documentation-reviewer", name: "文档审校员", description: "检查结构、术语和示例，使技术文档准确且易于理解。" },
  { id: "mock-catalog-role-devops-engineer", name: "DevOps 工程师", description: "优化构建、部署与环境管理流程，提升交付可重复性。" },
  { id: "mock-catalog-role-sre", name: "SRE 可靠性工程师", description: "围绕 SLO、容量与故障恢复改进系统可靠性。" },
  { id: "mock-catalog-role-cloud-architect", name: "云架构师", description: "设计安全、弹性且成本可控的云上系统架构。" },
  { id: "mock-catalog-role-security-auditor", name: "安全审计员", description: "识别代码和配置中的攻击面、权限与数据泄露风险。" },
  { id: "mock-catalog-role-privacy-advisor", name: "隐私合规顾问", description: "审查数据收集、处理与保留策略中的隐私风险。" },
  { id: "mock-catalog-role-incident-commander", name: "应急响应指挥", description: "在故障期间组织研判、分工、沟通与恢复行动。" },
  { id: "mock-catalog-role-platform-engineer", name: "平台工程师", description: "建设自助式工程平台，降低研发团队的交付认知负担。" },
  { id: "mock-catalog-role-finops-advisor", name: "云成本顾问", description: "分析资源利用与账单结构，平衡成本、性能和可靠性。" },
  { id: "mock-catalog-role-data-analyst", name: "数据分析师", description: "清洗和分析业务数据，用清晰结论支持产品决策。" },
  { id: "mock-catalog-role-data-engineer", name: "数据工程师", description: "设计稳定的数据管道、质量规则与可追溯的数据资产。" },
  { id: "mock-catalog-role-ml-engineer", name: "机器学习工程师", description: "推进模型训练、评估、部署与监控的工程闭环。" },
  { id: "mock-catalog-role-ai-product-manager", name: "AI 产品经理", description: "将模型能力转化为可靠、可衡量的产品体验。" },
  { id: "mock-catalog-role-prompt-engineer", name: "提示词工程师", description: "设计结构化提示、评估集与迭代策略以稳定模型输出。" },
  { id: "mock-catalog-role-agent-architect", name: "Agent 架构师", description: "规划工具调用、上下文、记忆和多 Agent 协作边界。" },
  { id: "mock-catalog-role-rag-expert", name: "RAG 检索专家", description: "优化切分、召回、重排与引用链路，提升回答可信度。" },
  { id: "mock-catalog-role-model-evaluator", name: "模型评测专家", description: "构建评测维度、数据集和回归基线，量化模型质量。" },
  { id: "mock-catalog-role-ai-safety-reviewer", name: "AI 安全评审员", description: "检查提示注入、越权调用和不安全输出等模型风险。" },
  { id: "mock-catalog-role-knowledge-engineer", name: "知识工程师", description: "组织领域知识、术语与关系，提升检索和推理质量。" },
  { id: "mock-catalog-role-visualization-expert", name: "数据可视化专家", description: "选择合适的图表与叙事结构，让复杂数据易于判断。" },
  { id: "mock-catalog-role-technical-writer", name: "技术写作专家", description: "将复杂实现转化为清晰、准确、可操作的技术内容。" },
  { id: "mock-catalog-role-localization-expert", name: "本地化专家", description: "优化跨语言文案、术语与区域体验的一致性。" },
  { id: "mock-catalog-role-open-source-maintainer", name: "开源维护者", description: "评估贡献质量、版本策略与社区协作中的长期影响。" },
  { id: "mock-catalog-role-interview-coach", name: "技术面试教练", description: "围绕目标岗位设计练习、追问并提供针对性反馈。" },
  { id: "mock-catalog-role-team-coach", name: "研发效能教练", description: "发现协作与交付瓶颈，帮助团队建立持续改进机制。" },
  { id: "mock-catalog-role-architecture-moderator", name: "架构评审主持人", description: "组织方案对比、约束澄清和架构决策记录。" },
  { id: "mock-catalog-role-migration-advisor", name: "系统迁移顾问", description: "规划分阶段迁移、兼容验证和风险可控的切换路径。" },
  { id: "mock-catalog-role-huawei-harmonyos-architect", name: "鸿蒙应用架构师", description: "围绕 HarmonyOS 与 ArkTS 规划应用分层、状态与设备协同。" },
  { id: "mock-catalog-role-huawei-ascend-expert", name: "昇腾推理优化专家", description: "面向昇腾计算环境分析模型推理瓶颈与部署策略。" },
  { id: "mock-catalog-role-huawei-kunpeng-advisor", name: "鲲鹏迁移顾问", description: "评估应用迁移至鲲鹏平台时的依赖、性能与兼容风险。" },
  { id: "mock-catalog-role-huawei-cloud-operator", name: "华为云运维助手", description: "围绕云资源、告警与变更设计稳健的日常运维流程。" },
  { id: "mock-catalog-role-huawei-mindspore-engineer", name: "MindSpore 工程师", description: "协助设计 MindSpore 训练、评估与部署的工程流程。" },
  { id: "mock-catalog-role-huawei-device-cloud-designer", name: "端云协同体验设计师", description: "聚焦华为终端与云服务协同场景中的连续用户体验。" },
  { id: "mock-catalog-role-huawei-enterprise-network-advisor", name: "企业网络方案顾问", description: "结合华为企业网络场景梳理园区、分支与云端连接方案。" },
] satisfies Agent[];

export const MOCK_SKILLS = [
  { id: "mock-catalog-skill-requirement-breakdown", name: "需求拆解", description: "把目标拆成范围清晰、可验证且有优先级的任务。" },
  { id: "mock-catalog-skill-user-story", name: "用户故事编写", description: "生成包含用户价值、场景和验收标准的用户故事。" },
  { id: "mock-catalog-skill-roadmap", name: "路线图规划", description: "依据目标、依赖与风险整理阶段性产品路线图。" },
  { id: "mock-catalog-skill-competitive-analysis", name: "竞品分析", description: "对比定位、能力和体验差异，提炼可行动机会。" },
  { id: "mock-catalog-skill-interview-guide", name: "访谈提纲生成", description: "围绕研究问题生成开放式访谈问题与追问。" },
  { id: "mock-catalog-skill-journey-map", name: "用户旅程梳理", description: "识别关键触点、目标、情绪与体验断点。" },
  { id: "mock-catalog-skill-prd-review", name: "PRD 评审", description: "检查需求完整性、边界、异常流程与验收条件。" },
  { id: "mock-catalog-skill-copy-polish", name: "产品文案润色", description: "让界面文案简洁、一致并贴合用户任务。" },
  { id: "mock-catalog-skill-information-architecture", name: "信息架构设计", description: "组织内容层级、导航和命名，降低查找成本。" },
  { id: "mock-catalog-skill-accessibility-audit", name: "无障碍检查", description: "检查键盘、语义、对比度和焦点等可访问性问题。" },
  { id: "mock-catalog-skill-code-review", name: "代码审查", description: "按严重程度识别正确性、维护性和安全问题。" },
  { id: "mock-catalog-skill-refactoring-plan", name: "重构方案设计", description: "在保持行为稳定的前提下规划渐进式结构改进。" },
  { id: "mock-catalog-skill-unit-test", name: "单元测试生成", description: "围绕公开行为、边界和失败路径生成可靠测试。" },
  { id: "mock-catalog-skill-integration-test", name: "集成测试设计", description: "覆盖组件协作、数据边界与关键系统流程。" },
  { id: "mock-catalog-skill-debugging", name: "故障定位", description: "从症状、日志和复现条件建立可验证的故障假设。" },
  { id: "mock-catalog-skill-api-design", name: "API 契约设计", description: "生成一致、清晰且可演进的接口与错误模型。" },
  { id: "mock-catalog-skill-schema-design", name: "数据模型设计", description: "依据领域约束设计实体、关系和数据不变量。" },
  { id: "mock-catalog-skill-sql-optimization", name: "SQL 优化", description: "分析执行路径、索引与数据分布以降低查询成本。" },
  { id: "mock-catalog-skill-typescript-hardening", name: "TypeScript 类型加固", description: "消除隐式 any 和不安全断言，收紧类型边界。" },
  { id: "mock-catalog-skill-rust-api-review", name: "Rust API 评审", description: "用类型系统表达约束并改善所有权与错误设计。" },
  { id: "mock-catalog-skill-frontend-performance", name: "前端性能分析", description: "定位渲染、资源与交互延迟中的主要瓶颈。" },
  { id: "mock-catalog-skill-responsive-layout", name: "响应式布局", description: "为不同视口规划稳定、清晰的布局变化。" },
  { id: "mock-catalog-skill-component-design", name: "组件接口设计", description: "定义职责单一、组合友好且可测试的组件 API。" },
  { id: "mock-catalog-skill-state-machine", name: "状态机建模", description: "用明确状态与事件消除互相冲突的可选字段。" },
  { id: "mock-catalog-skill-git-diff-summary", name: "Git 变更摘要", description: "归纳改动意图、影响范围和需要关注的风险。" },
  { id: "mock-catalog-skill-commit-message", name: "Commit 信息生成", description: "根据变更生成准确、简洁的 Conventional Commit。" },
  { id: "mock-catalog-skill-release-notes", name: "发布说明生成", description: "将技术变更转化为清晰的用户可见发布内容。" },
  { id: "mock-catalog-skill-ci-diagnosis", name: "CI 失败诊断", description: "分析检查日志，定位首个有效失败和修复路径。" },
  { id: "mock-catalog-skill-deployment-checklist", name: "部署清单生成", description: "整理上线前验证、监控、沟通与回滚准备。" },
  { id: "mock-catalog-skill-incident-summary", name: "故障复盘摘要", description: "形成时间线、影响、根因和可跟踪改进项。" },
  { id: "mock-catalog-skill-log-analysis", name: "日志分析", description: "从大量日志中提取异常模式、关联事件和线索。" },
  { id: "mock-catalog-skill-threat-model", name: "威胁建模", description: "识别资产、信任边界、攻击路径与缓解措施。" },
  { id: "mock-catalog-skill-dependency-audit", name: "依赖安全审计", description: "检查依赖漏洞、许可证与供应链风险。" },
  { id: "mock-catalog-skill-secret-scan", name: "敏感信息检查", description: "发现代码和配置中可能泄露的凭据与隐私数据。" },
  { id: "mock-catalog-skill-cloud-cost-review", name: "云成本审查", description: "评估资源利用、规格选择与潜在浪费。" },
  { id: "mock-catalog-skill-dockerfile-review", name: "容器镜像审查", description: "优化镜像安全性、体积、缓存和运行时配置。" },
  { id: "mock-catalog-skill-kubernetes-review", name: "Kubernetes 配置审查", description: "检查资源、探针、权限和高可用配置。" },
  { id: "mock-catalog-skill-terraform-review", name: "IaC 变更审查", description: "评估基础设施变更的安全、漂移与回滚风险。" },
  { id: "mock-catalog-skill-data-cleaning", name: "数据清洗", description: "识别缺失、异常与重复数据并制定处理规则。" },
  { id: "mock-catalog-skill-data-visualization", name: "图表方案推荐", description: "依据数据关系和沟通目标选择合适图表。" },
  { id: "mock-catalog-skill-metric-design", name: "指标体系设计", description: "定义口径明确、可归因且服务决策的指标。" },
  { id: "mock-catalog-skill-experiment-design", name: "实验方案设计", description: "规划假设、分组、指标与有效性判断标准。" },
  { id: "mock-catalog-skill-prompt-optimization", name: "提示词优化", description: "重构指令、上下文和输出约束以提升稳定性。" },
  { id: "mock-catalog-skill-rag-evaluation", name: "RAG 效果评测", description: "评估召回、忠实度、引用与端到端回答质量。" },
  { id: "mock-catalog-skill-eval-dataset", name: "评测集构建", description: "设计覆盖常规、边界与对抗场景的评测样本。" },
  { id: "mock-catalog-skill-agent-tool-design", name: "Agent 工具设计", description: "定义清晰的工具输入、输出、权限与失败反馈。" },
  { id: "mock-catalog-skill-context-compression", name: "上下文压缩", description: "保留关键事实与约束，同时减少无效上下文。" },
  { id: "mock-catalog-skill-prompt-injection-audit", name: "提示注入审查", description: "检查外部内容影响指令与工具调用的风险。" },
  { id: "mock-catalog-skill-technical-translation", name: "技术中英互译", description: "保持术语、语气和技术含义一致的双语转换。" },
  { id: "mock-catalog-skill-document-outline", name: "文档大纲生成", description: "依据读者与目标生成层级清晰的内容结构。" },
  { id: "mock-catalog-skill-meeting-summary", name: "会议纪要整理", description: "提取结论、分歧、行动项与明确负责人。" },
  { id: "mock-catalog-skill-architecture-decision", name: "架构决策记录", description: "整理背景、备选方案、权衡和最终决定。" },
  { id: "mock-catalog-skill-huawei-arkts", name: "HarmonyOS ArkTS 开发", description: "生成符合 ArkTS 场景的界面、状态与工程实现建议。" },
  { id: "mock-catalog-skill-huawei-cann", name: "昇腾 CANN 调优", description: "分析算子、内存与执行链路中的昇腾推理性能问题。" },
  { id: "mock-catalog-skill-huawei-mindspore", name: "MindSpore 训练诊断", description: "排查训练配置、收敛、数据管道与性能异常。" },
  { id: "mock-catalog-skill-huawei-kunpeng", name: "鲲鹏迁移评估", description: "梳理指令集、依赖和性能验证等迁移关注项。" },
  { id: "mock-catalog-skill-huawei-cloud-iac", name: "华为云 IaC 审查", description: "检查华为云资源编排中的权限、规格和变更风险。" },
  { id: "mock-catalog-skill-huawei-distributed", name: "鸿蒙分布式能力设计", description: "围绕跨设备流转、数据同步和异常恢复设计交互。" },
  { id: "mock-catalog-skill-huawei-hiview", name: "HiView 可观测性分析", description: "结合华为终端日志与性能线索梳理问题定位路径。" },
  { id: "mock-catalog-skill-huawei-cloud-security", name: "华为云安全基线检查", description: "检查身份权限、网络边界与云资源安全配置。" },
] satisfies Skill[];

/** Distinguishes bundled catalog examples from persisted records without extra API fields. */
export function isMockAtom(item: Agent | Skill): boolean {
  return item.id.startsWith(MOCK_ATOM_ID_PREFIX);
}

/** Marks the small set of vendor-flavoured examples for transparent UI labeling. */
export function isHuaweiAtom(item: Agent | Skill): boolean {
  return isMockAtom(item) && item.id.includes("-huawei-");
}
