[package]
name = "ora-application"
version.workspace = true
edition.workspace = true

[lib]
name = "ora_application"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
gitlancer = { workspace = true }
ora-contracts = { workspace = true }
ora-domain = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
uuid = { workspace = true }

[dev-dependencies]
ora-logging = { workspace = true }
pretty_assertions = { workspace = true }
