//! TypeScript export for the protocol shared by plugin processes and the Ora host.

use std::fs;
use std::path::Path;

use ora_plugin_protocol::*;

const GENERATED_FILE_HEADER: &str = "// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.\n";

/// Refreshes Rust-owned plugin DTOs and method constants without touching hand-written SDK files.
pub(crate) fn run(workspace_root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let output_directory = workspace_root.join("packages/plugin-sdk/src/protocol");
    fs::create_dir_all(&output_directory)?;
    remove_stale_typescript_bindings(&output_directory)?;
    export_typescript_bindings_to(&output_directory)?;

    let constants = render_constants();
    fs::write(output_directory.join("constants.ts"), constants)?;
    Ok(())
}

/// Removes only files owned by ts-rs so hand-written transport and barrel modules survive.
fn remove_stale_typescript_bindings(directory: &Path) -> Result<(), Box<dyn std::error::Error>> {
    const TS_RS_HEADER: &str = "// This file was generated by [ts-rs]";

    for entry in fs::read_dir(directory)? {
        let path = entry?.path();
        if path.is_dir() {
            remove_stale_typescript_bindings(&path)?;
        } else if path.extension().is_some_and(|extension| extension == "ts")
            && fs::read_to_string(&path)?.starts_with(TS_RS_HEADER)
        {
            fs::remove_file(path)?;
        }
    }
    Ok(())
}

/// Renders runtime values as grouped objects so callers never repeat wire method spellings.
fn render_constants() -> String {
    format!(
        "{GENERATED_FILE_HEADER}\
export const JSON_RPC_VERSION = {JSON_RPC_VERSION:?} as const;\n\
export const JSON_RPC_FRAME_TYPE = {JSON_RPC_FRAME_TYPE};\n\
export const MAX_FRAME_LENGTH = {MAX_FRAME_LENGTH};\n\
export const INVALID_PARAMS = {INVALID_PARAMS_CODE};\n\
export const METHOD_NOT_FOUND = {METHOD_NOT_FOUND_CODE};\n\
export const INTERNAL_ERROR = {INTERNAL_ERROR_CODE};\n\
export const AGENT_NOT_INSTALLED = {AGENT_NOT_INSTALLED_CODE};\n\
export const AGENT_UNUSABLE = {AGENT_UNUSABLE_CODE};\n\
export const SUPPORTED_ACP_VERSION = {SUPPORTED_ACP_VERSION};\n\
export const SKILL_DIRECTORY_V1 = {SKILL_DIRECTORY_V1:?} as const;\n\
export const OPENCODE_MCP_CONFIG_V1 = {OPENCODE_MCP_CONFIG_V1:?} as const;\n\
export const CLAUDE_MCP_CONFIG_V1 = {CLAUDE_MCP_CONFIG_V1:?} as const;\n\
export const MAX_STORAGE_FILE_BYTES = {MAX_STORAGE_FILE_BYTES};\n\n\
export const PLUGIN_METHODS = {{\n\
\x20\x20register: {REGISTER_METHOD:?},\n\
\x20\x20shutdown: {SHUTDOWN_METHOD:?},\n\
}} as const;\n\n\
export const AGENT_METHODS = {{\n\
\x20\x20start: {AGENT_START_METHOD:?},\n\
\x20\x20stop: {AGENT_STOP_METHOD:?},\n\
\x20\x20listModels: {AGENT_LIST_MODELS_METHOD:?},\n\
\x20\x20acp: {AGENT_ACP_METHOD:?},\n\
}} as const;\n\n\
export const EFFECT_METHODS = {{\n\
\x20\x20coordinate: {EFFECT_COORDINATE_METHOD:?},\n\
\x20\x20reactivate: {EFFECT_REACTIVATE_METHOD:?},\n\
\x20\x20verifyReady: {EFFECT_VERIFY_READY_METHOD:?},\n\
}} as const;\n\n\
export const STORAGE_METHODS = {{\n\
\x20\x20list: {STORAGE_LIST_METHOD:?},\n\
\x20\x20read: {STORAGE_READ_METHOD:?},\n\
\x20\x20write: {STORAGE_WRITE_METHOD:?},\n\
\x20\x20remove: {STORAGE_REMOVE_METHOD:?},\n\
}} as const;\n\n\
export const CHILD_PROCESS_METHODS = {{\n\
\x20\x20spawn: {CHILDPROCESS_SPAWN_METHOD:?},\n\
\x20\x20write: {CHILDPROCESS_WRITE_METHOD:?},\n\
\x20\x20closeStdin: {CHILDPROCESS_CLOSE_STDIN_METHOD:?},\n\
\x20\x20kill: {CHILDPROCESS_KILL_METHOD:?},\n\
}} as const;\n\n\
export const CHILD_PROCESS_NOTIFICATIONS = {{\n\
\x20\x20stdout: {CHILDPROCESS_STDOUT_METHOD:?},\n\
\x20\x20stderr: {CHILDPROCESS_STDERR_METHOD:?},\n\
\x20\x20exit: {CHILDPROCESS_EXIT_METHOD:?},\n\
}} as const;\n"
    )
}

#[cfg(test)]
mod tests {
    use super::render_constants;

    /// Locks snake_case wire names and guards against restoring SDK-only spellings.
    #[test]
    fn renders_snake_case_methods() {
        let source = render_constants();

        assert!(source.contains("agent/list_models"));
        assert!(source.contains("effect/verify_ready"));
        assert!(source.contains("ora/childprocess/close_stdin"));
        assert!(!source.contains("agent/listModels"));
    }
}
