use crate::frontend::{FrontendEndpoint, FrontendResponseMode, frontend_endpoints};
use ora_contracts::export_typescript_bindings_to;
use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

pub(crate) const GENERATED_FILE_HEADER: &str = "// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.\n";

mod client;

/// Exports DTOs, their barrel, the operation manifest, and statically typed client wiring.
pub fn run_export_contracts(workspace_root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let staging = tempfile::tempdir()?;
    render_contracts(staging.path())?;
    crate::generated_artifacts::publish(workspace_root, staging.path())
}

/// Checks generated contents and inventory without modifying the checkout or consulting Git.
pub fn check_export_contracts(workspace_root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let staging = tempfile::tempdir()?;
    render_contracts(staging.path())?;
    crate::generated_artifacts::check(workspace_root, staging.path())
}

/// Renders into a fresh staging directory so failed generation cannot erase previous artifacts.
fn render_contracts(workspace_root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let contracts_source_directory = workspace_root.join("packages/contracts/src");

    fs::create_dir_all(&contracts_source_directory)?;
    export_typescript_bindings_to(&contracts_source_directory)?;
    append_ts_extension_to_exported_imports(&contracts_source_directory)?;
    let endpoints = frontend_endpoints();
    client::export(&contracts_source_directory, &endpoints)?;
    write_generated_file(
        &contracts_source_directory.join("endpoints.ts"),
        &render_endpoints_module(&endpoints),
    )?;
    crate::export_plugin_protocol::run(workspace_root)?;
    crate::export_desktop::export(workspace_root, &endpoints)?;

    Ok(())
}

/// Rewrites every ts-rs cross-file import so Deno can execute the TypeScript sources directly.
///
/// ts-rs emits extensionless specifiers, which `moduleResolution: "NodeNext"` rejects.
fn append_ts_extension_to_exported_imports(
    contracts_source_directory: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    for entry in fs::read_dir(contracts_source_directory)? {
        let path = entry?.path();

        if path.is_dir() {
            append_ts_extension_to_exported_imports(&path)?;
            continue;
        }

        if path.extension().is_some_and(|extension| extension == "ts") {
            let contents = fs::read_to_string(&path)?;
            let rewritten = append_ts_extension_to_relative_specifiers(&contents);

            if rewritten != contents {
                fs::write(&path, rewritten)?;
            }
        }
    }

    Ok(())
}

/// Appends the `.ts` extension to each relative module specifier that still lacks one.
fn append_ts_extension_to_relative_specifiers(contents: &str) -> String {
    const SPECIFIER_PREFIX: &str = "from \"";

    let mut rewritten = String::with_capacity(contents.len());
    let mut remainder = contents;

    while let Some(prefix_start) = remainder.find(SPECIFIER_PREFIX) {
        let specifier_start = prefix_start + SPECIFIER_PREFIX.len();
        let Some(specifier_length) = remainder[specifier_start..].find('"') else {
            break;
        };
        let specifier_end = specifier_start + specifier_length;
        let specifier = &remainder[specifier_start..specifier_end];

        rewritten.push_str(&remainder[..specifier_end]);

        if (specifier.starts_with("./") || specifier.starts_with("../"))
            && !specifier.ends_with(".ts")
        {
            rewritten.push_str(".ts");
        }

        remainder = &remainder[specifier_end..];
    }

    rewritten.push_str(remainder);

    rewritten
}

/// Writes one generated file to disk, creating its parent directory when needed.
pub(crate) fn write_generated_file(
    output_path: &Path,
    contents: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    if let Some(parent_directory) = output_path.parent() {
        fs::create_dir_all(parent_directory)?;
    }

    fs::write(output_path, contents)?;

    Ok(())
}

/// Renders the endpoint manifest and operation type maps consumed by the hand-written client.
///
/// The generated file mixes runtime data (`endpoints` const) with compile-time
/// type maps (`RequestByOperation`, `ResponseByOperation`). The runtime data
/// contains only the metadata needed to route operation names to client members.
fn render_endpoints_module(endpoints: &[FrontendEndpoint]) -> String {
    let mut source = String::from(GENERATED_FILE_HEADER);
    let imports = endpoints
        .iter()
        .flat_map(|endpoint| [endpoint.request_type, endpoint.response_type])
        .collect::<BTreeSet<_>>();
    source.push_str("import type { ");
    source.push_str(&imports.into_iter().collect::<Vec<_>>().join(", "));
    source.push_str(" } from \"./dto.generated.ts\";\n");

    source.push_str("export type FrontendEndpointDefinition = {\n");
    source.push_str("  operationName: string;\n");
    source.push_str("  namespace: string;\n");
    source.push_str("  memberName: string;\n");
    source.push_str("  requestType: string;\n");
    source.push_str("  responseType: string;\n");
    source.push_str("  responseMode: \"unary\" | \"stream\";\n");
    source.push_str("};\n\n");
    source.push_str("export type RequestByOperation = {\n");

    for endpoint in endpoints {
        source.push_str("  ");
        source.push_str(endpoint.operation_name);
        source.push_str(": ");
        source.push_str(endpoint.request_type);
        source.push_str(";\n");
    }

    source.push_str("};\n\n");
    source.push_str("export type ResponseByOperation = {\n");

    for endpoint in endpoints {
        source.push_str("  ");
        source.push_str(endpoint.operation_name);
        source.push_str(": ");
        source.push_str(endpoint.response_type);
        source.push_str(";\n");
    }

    source.push_str("};\n\n");
    source.push_str("export type EndpointOperation = keyof RequestByOperation;\n\n");

    // `as const` preserves each operation's literal namespace/member mapping;
    // the `satisfies` clause keeps the generated catalog structurally checked.
    source.push_str("export const endpoints = {\n");

    for endpoint in endpoints {
        source.push_str("  ");
        source.push_str(endpoint.operation_name);
        source.push_str(": {\n");
        source.push_str("    operationName: \"");
        source.push_str(endpoint.operation_name);
        source.push_str("\",\n");
        source.push_str("    namespace: \"");
        source.push_str(endpoint.namespace);
        source.push_str("\",\n");
        source.push_str("    memberName: \"");
        source.push_str(endpoint.member_name);
        source.push_str("\",\n");
        source.push_str("    requestType: \"");
        source.push_str(endpoint.request_type);
        source.push_str("\",\n");
        source.push_str("    responseType: \"");
        source.push_str(endpoint.response_type);
        source.push_str("\",\n");
        source.push_str("    responseMode: \"");
        source.push_str(match endpoint.response_mode {
            FrontendResponseMode::Unary => "unary",
            FrontendResponseMode::Stream => "stream",
        });
        source.push_str("\",\n");
        source.push_str("  },\n");
    }

    source
        .push_str("} as const satisfies Record<EndpointOperation, FrontendEndpointDefinition>;\n");

    source
}

#[cfg(test)]
mod tests {
    use super::{
        append_ts_extension_to_relative_specifiers, render_endpoints_module, run_export_contracts,
    };
    use crate::frontend::frontend_endpoints;
    use pretty_assertions::assert_eq;
    use std::fs;
    use tempfile::TempDir;

    /// Verifies ts-rs cross-file imports gain the extension `NodeNext` resolution requires.
    #[test]
    fn appends_ts_extension_to_extensionless_relative_imports() {
        let rewritten = append_ts_extension_to_relative_specifiers(
            "import type { Session } from \"./session\";\nimport type { Task } from \"../task\";\n",
        );

        assert_eq!(
            rewritten,
            "import type { Session } from \"./session.ts\";\nimport type { Task } from \"../task.ts\";\n"
        );
    }

    /// Verifies already-suffixed and bare package specifiers survive the rewrite untouched.
    #[test]
    fn preserves_specifiers_that_need_no_extension() {
        let source = "import type { Task } from \"./task.ts\";\nimport { z } from \"zod\";\nexport type A = { from: \"./x\" };\n";

        assert_eq!(append_ts_extension_to_relative_specifiers(source), source);
    }

    /// Verifies the generated endpoint manifest preserves Desktop operation metadata.
    #[test]
    fn renders_endpoint_manifest_with_operation_metadata() {
        let endpoints = frontend_endpoints();
        let module = render_endpoints_module(&endpoints);

        assert!(module.contains("updateTask"));
        assert!(module.contains("memberName: \"update\""));
        assert!(!module.contains("pathTemplate"));
    }

    /// Verifies the generated manifest narrows literal values with `as const`.
    #[test]
    fn emits_as_const_satisfies_clauses() {
        let endpoints = frontend_endpoints();
        let module = render_endpoints_module(&endpoints);

        assert!(module.contains(
            "} as const satisfies Record<EndpointOperation, FrontendEndpointDefinition>;\n"
        ));
    }

    /// Verifies the export workflow writes DTOs and the generated endpoint manifest.
    #[test]
    fn writes_contract_package_files() {
        let workspace_root = TempDir::new().unwrap_or_else(|error| {
            panic!("failed to create workspace root: {error}");
        });
        let package_source_directory = workspace_root.path().join("packages/contracts/src");
        fs::create_dir_all(&package_source_directory).unwrap_or_else(|error| {
            panic!("failed to create package source directory: {error}");
        });

        run_export_contracts(workspace_root.path()).unwrap_or_else(|error| {
            panic!("expected export workflow to succeed: {error}");
        });

        let generated_files = [
            "agent.ts",
            "client.generated.ts",
            "dto.generated.ts",
            "endpoints.ts",
            "file-system.ts",
            "project.ts",
            "session.ts",
            "skill.ts",
            "task.ts",
            "workflow.ts",
            "workspace_diff.ts",
        ];

        for generated_file in generated_files {
            let output_path = package_source_directory.join(generated_file);
            assert!(
                output_path.exists(),
                "missing generated file {output_path:?}"
            );
        }

        let session_source = fs::read_to_string(package_source_directory.join("session.ts"))
            .unwrap_or_else(|error| panic!("failed to read generated session contract: {error}"));
        assert!(session_source.contains("import(\"@agentclientprotocol/sdk\").ContentBlock"));
        assert!(!package_source_directory.join("acp").exists());
    }
}
