// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes an available authentication method.
 *
 * The `type` field acts as the discriminator in the serialized JSON form.
 * When no `type` is present, the method is treated as `agent`.
 */
export type AuthMethod = AuthMethodAgent;

/**
 * Agent handles authentication itself.
 *
 * This is the default authentication method type.
 */
export type AuthMethodAgent = {
  /**
   * Unique identifier for this authentication method.
   */
  id: AuthMethodId;
  /**
   * Human-readable name of the authentication method.
   */
  name: string;
  /**
   * Optional description providing more details about this authentication method.
   */
  description?: string | null;
};

/**
 * Typed identifier used for auth method values on the wire.
 */
export type AuthMethodId = string;

/**
 * Request parameters for the authenticate method.
 *
 * Specifies which authentication method to use.
 */
export type AuthenticateRequest = {
  /**
   * The ID of the authentication method to use.
   * Must be one of the methods advertised in the initialize response.
   */
  methodId: AuthMethodId;
};

/**
 * Response to the `authenticate` method.
 */
export type AuthenticateResponse = Record<symbol, never>;

/**
 * Request parameters for the logout method.
 *
 * Terminates the current authenticated session.
 */
export type LogoutRequest = Record<symbol, never>;

/**
 * Response to the `logout` method.
 */
export type LogoutResponse = Record<symbol, never>;
