// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a successful payload or capability marker whose wire representation is `{}`.
 */
export type EmptyObject = Record<symbol, never>;

/**
 * An environment variable to set when launching an MCP server.
 */
export type EnvVariable = {
  /**
   * The name of the environment variable.
   */
  name: string;
  /**
   * The value to set for the environment variable.
   */
  value: string;
};

/**
 * A unique identifier for a conversation session between a client and agent.
 *
 * Sessions maintain their own context, conversation history, and state,
 * allowing multiple independent interactions with the same agent.
 */
export type SessionId = string;
