// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries optional presentation hints for content.
 */
export type Annotations = {
  audience: Array<Role> | null;
  priority: number | null;
  lastModified: string | null;
};

/**
 * Contains base64-encoded audio.
 */
export type AudioContent = {
  data: string;
  mimeType: string;
  annotations: Annotations | null;
};

/**
 * Embeds a base64-encoded binary resource directly in a content block.
 */
export type BlobResourceContents = {
  uri: string;
  blob: string;
  mimeType: string | null;
};

/**
 * Represents every displayable ACP content block described by the content protocol.
 */
export type ContentBlock =
  | { "type": "text" } & TextContent
  | { "type": "image" } & ImageContent
  | { "type": "audio" } & AudioContent
  | {
    "type": "resource";
    resource: EmbeddedResourceContents;
    annotations: Annotations | null;
  }
  | { "type": "resource_link" } & ResourceLink;

/**
 * Models the two legal representations of an embedded resource.
 */
export type EmbeddedResourceContents =
  | TextResourceContents
  | BlobResourceContents;

/**
 * Contains a base64-encoded image.
 */
export type ImageContent = {
  data: string;
  mimeType: string;
  uri: string | null;
  annotations: Annotations | null;
};

/**
 * References a resource that the agent can access separately.
 */
export type ResourceLink = {
  uri: string;
  name: string;
  mimeType: string | null;
  title: string | null;
  description: string | null;
  size: number | null;
  annotations: Annotations | null;
};

/**
 * Identifies the intended audience for a content block.
 */
export type Role = "user" | "assistant";

/**
 * Contains plain text exchanged in a prompt or update.
 */
export type TextContent = { text: string; annotations: Annotations | null };

/**
 * Embeds a textual resource directly in a content block.
 */
export type TextResourceContents = {
  uri: string;
  text: string;
  mimeType: string | null;
};
