// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional annotations for the client. The client can use annotations to inform how objects are used or displayed
 */
export type Annotations = {
  /**
   * Intended recipients for this content, such as the user or assistant.
   */
  audience?: Array<Role> | null;
  /**
   * Timestamp indicating when the underlying resource was last modified.
   */
  lastModified?: string | null;
  /**
   * Relative importance of this content when clients choose what to surface.
   */
  priority?: number | null;
};

/**
 * Audio provided to or from an LLM.
 */
export type AudioContent = {
  /**
   * Optional annotations that help clients decide how to display or route this content.
   */
  annotations?: Annotations | null;
  /**
   * Base64-encoded media payload.
   */
  data: string;
  /**
   * MIME type describing the encoded media payload.
   */
  mimeType: string;
};

/**
 * Binary resource contents.
 */
export type BlobResourceContents = {
  /**
   * Base64-encoded bytes for a binary resource payload.
   */
  blob: string;
  /**
   * MIME type describing the encoded media payload.
   */
  mimeType?: string | null;
  /**
   * URI associated with this resource or media payload.
   */
  uri: string;
};

/**
 * Content blocks represent displayable information in the Agent Client Protocol.
 *
 * They provide a structured way to handle various types of user-facing content—whether
 * it's text from language models, images for analysis, or embedded resources for context.
 *
 * Content blocks appear in:
 * - User prompts sent via `session/prompt`
 * - Language model output streamed through `session/update` notifications
 * - Progress updates and results from tool calls
 *
 * This structure is compatible with the Model Context Protocol (MCP), enabling
 * agents to seamlessly forward content from MCP tool outputs without transformation.
 */
export type ContentBlock =
  | { "type": "text" } & TextContent
  | { "type": "image" } & ImageContent
  | { "type": "audio" } & AudioContent
  | { "type": "resource_link" } & ResourceLink
  | { "type": "resource" } & EmbeddedResource;

/**
 * The contents of a resource, embedded into a prompt or tool call result.
 */
export type EmbeddedResource = {
  /**
   * Optional annotations that help clients decide how to display or route this content.
   */
  annotations?: Annotations | null;
  /**
   * Embedded resource payload, either text or binary data.
   */
  resource: EmbeddedResourceResource;
};

/**
 * Resource content that can be embedded in a message.
 */
export type EmbeddedResourceResource =
  | TextResourceContents
  | BlobResourceContents;

/**
 * An image provided to or from an LLM.
 */
export type ImageContent = {
  /**
   * Optional annotations that help clients decide how to display or route this content.
   */
  annotations?: Annotations | null;
  /**
   * Base64-encoded media payload.
   */
  data: string;
  /**
   * MIME type describing the encoded media payload.
   */
  mimeType: string;
  /**
   * URI associated with this resource or media payload.
   */
  uri?: string | null;
};

/**
 * A resource that the server is capable of reading, included in a prompt or tool call result.
 */
export type ResourceLink = {
  /**
   * Optional annotations that help clients decide how to display or route this content.
   */
  annotations?: Annotations | null;
  /**
   * Optional human-readable details shown with this protocol object.
   */
  description?: string | null;
  /**
   * MIME type describing the encoded media payload.
   */
  mimeType?: string | null;
  /**
   * Human-readable name shown for this protocol object.
   */
  name: string;
  /**
   * Optional size of the linked resource in bytes, if known.
   */
  size?: bigint | null;
  /**
   * Optional display title for end-user UI.
   */
  title?: string | null;
  /**
   * URI associated with this resource or media payload.
   */
  uri: string;
};

/**
 * The sender or recipient of messages and data in a conversation.
 */
export type Role = "assistant" | "user";

/**
 * Text provided to or from an LLM.
 */
export type TextContent = {
  /**
   * Optional annotations that help clients decide how to display or route this content.
   */
  annotations?: Annotations | null;
  /**
   * Text payload carried by this content block.
   */
  text: string;
};

/**
 * Text-based resource contents.
 */
export type TextResourceContents = {
  /**
   * MIME type describing the encoded media payload.
   */
  mimeType?: string | null;
  /**
   * Text payload carried by this content block.
   */
  text: string;
  /**
   * URI associated with this resource or media payload.
   */
  uri: string;
};
