// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./common.js";

/**
 * Request to read content from a text file.
 *
 * Only available if the client supports the `fs.readTextFile` capability.
 */
export type ReadTextFileRequest = {
  /**
   * The session ID for this request.
   */
  sessionId: SessionId;
  /**
   * Absolute path to the file to read.
   */
  path: string;
  /**
   * Line number to start reading from (1-based).
   */
  line?: number | null;
  /**
   * Maximum number of lines to read.
   */
  limit?: number | null;
};

/**
 * Response containing the contents of a text file.
 */
export type ReadTextFileResponse = {
  /**
   * Content payload returned by this response.
   */
  content: string;
};

/**
 * Request to write content to a text file.
 *
 * Only available if the client supports the `fs.writeTextFile` capability.
 */
export type WriteTextFileRequest = {
  /**
   * The session ID for this request.
   */
  sessionId: SessionId;
  /**
   * Absolute path to the file to write.
   */
  path: string;
  /**
   * The text content to write to the file.
   */
  content: string;
};

/**
 * Response to `fs/write_text_file`
 */
export type WriteTextFileResponse = Record<symbol, never>;
