// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMethod } from "./authentication.js";
import type { EmptyObject } from "./common.js";

/**
 * Authentication-related capabilities supported by the agent.
 */
export type AgentAuthCapabilities = {
  /**
   * Whether the agent supports the logout method.
   *
   * Optional. Omitted or `null` both mean the agent does not advertise support.
   * Supplying `{}` means the agent supports the logout method.
   */
  logout?: EmptyObject | null;
};

/**
 * Capabilities supported by the agent.
 *
 * Advertised during initialization to inform the client about
 * available features and content types.
 */
export type AgentCapabilities = {
  /**
   * Whether the agent supports `session/load`.
   */
  loadSession: boolean;
  /**
   * Prompt capabilities supported by the agent.
   */
  promptCapabilities: PromptCapabilities;
  /**
   * MCP capabilities supported by the agent.
   */
  mcpCapabilities: McpCapabilities;
  /**
   * Session lifecycle and prompt capabilities advertised by the agent.
   */
  sessionCapabilities: SessionCapabilities;
  /**
   * Authentication-related capabilities supported by the agent.
   */
  auth: AgentAuthCapabilities;
};

/**
 * Capabilities supported by the client.
 *
 * Advertised during initialization to inform the agent about
 * available features and methods.
 */
export type ClientCapabilities = {
  /**
   * File system capabilities supported by the client.
   * Determines which file operations the agent can request.
   */
  fs: FileSystemCapabilities;
  /**
   * Whether the Client support all `terminal/*` methods.
   */
  terminal: boolean;
  /**
   * Session-related capabilities supported by the client.
   *
   * Optional. Omitted or `null` both mean the client does not advertise any
   * session-related extensions.
   */
  session?: ClientSessionCapabilities | null;
};

/**
 * Session-related capabilities supported by the client.
 */
export type ClientSessionCapabilities = {
  /**
   * Config option capabilities supported by the client.
   *
   * Omitted or `null` both mean the client does not advertise support for any
   * config option extensions.
   */
  configOptions?: SessionConfigOptionsCapabilities | null;
};

/**
 * File system capabilities that a client may support.
 */
export type FileSystemCapabilities = {
  /**
   * Whether the Client supports `fs/read_text_file` requests.
   */
  readTextFile: boolean;
  /**
   * Whether the Client supports `fs/write_text_file` requests.
   */
  writeTextFile: boolean;
};

/**
 * Metadata about the implementation of the client or agent.
 * Describes the name and version of an ACP implementation, with an optional
 * title for UI representation.
 */
export type Implementation = {
  /**
   * Intended for programmatic or logical use, but can be used as a display
   * name fallback if title isn’t present.
   */
  name: string;
  /**
   * Intended for UI and end-user contexts — optimized to be human-readable
   * and easily understood.
   *
   * If not provided, the name should be used for display.
   */
  title?: string | null;
  /**
   * Version of the implementation. Can be displayed to the user or used
   * for debugging or metrics purposes. (e.g. "1.0.0").
   */
  version: string;
};

/**
 * Request parameters for the initialize method.
 *
 * Sent by the client to establish connection and negotiate capabilities.
 */
export type InitializeRequest = {
  /**
   * The latest protocol version supported by the client.
   */
  protocolVersion: ProtocolVersion;
  /**
   * Capabilities supported by the client.
   */
  clientCapabilities: ClientCapabilities;
  /**
   * Information about the Client name and version sent to the Agent.
   *
   * Note: in future versions of the protocol, this will be required.
   */
  clientInfo?: Implementation | null;
};

/**
 * Response to the `initialize` method.
 *
 * Contains the negotiated protocol version and agent capabilities.
 */
export type InitializeResponse = {
  /**
   * The protocol version the client specified if supported by the agent,
   * or the latest protocol version supported by the agent.
   *
   * The client should disconnect, if it doesn't support this version.
   */
  protocolVersion: ProtocolVersion;
  /**
   * Capabilities supported by the agent.
   */
  agentCapabilities: AgentCapabilities;
  /**
   * Authentication methods supported by the agent.
   */
  authMethods: Array<AuthMethod>;
  /**
   * Information about the Agent name and version sent to the Client.
   *
   * Note: in future versions of the protocol, this will be required.
   */
  agentInfo?: Implementation | null;
};

/**
 * MCP capabilities supported by the agent
 */
export type McpCapabilities = {
  /**
   * Agent supports [`McpServer::Http`].
   */
  http: boolean;
  /**
   * Agent supports [`McpServer::Sse`].
   */
  sse: boolean;
};

/**
 * Prompt capabilities supported by the agent in `session/prompt` requests.
 *
 * Baseline agent functionality requires support for [`ContentBlock::Text`]
 * and [`ContentBlock::ResourceLink`] in prompt requests.
 *
 * Other variants must be explicitly opted in to.
 * Capabilities for different types of content in prompt requests.
 *
 * Indicates which content types beyond the baseline (text and resource links)
 * the agent can process.
 */
export type PromptCapabilities = {
  /**
   * Agent supports [`ContentBlock::Image`].
   */
  image: boolean;
  /**
   * Agent supports [`ContentBlock::Audio`].
   */
  audio: boolean;
  /**
   * Agent supports embedded context in `session/prompt` requests.
   *
   * When enabled, the Client is allowed to include [`ContentBlock::Resource`]
   * in prompt requests for pieces of context that are referenced in the message.
   */
  embeddedContext: boolean;
};

/**
 * Identifies the ACP version negotiated between a client and an agent.
 */
export type ProtocolVersion = number;

/**
 * Session capabilities supported by the agent.
 *
 * As a baseline, all Agents **MUST** support `session/new`, `session/prompt`, `session/cancel`, and `session/update`.
 *
 * Optionally, they **MAY** support other session methods and notifications by specifying additional capabilities.
 *
 * Note: `session/load` is still handled by the top-level `load_session` capability. This will be unified in future versions of the protocol.
 */
export type SessionCapabilities = {
  /**
   * Whether the agent supports `session/list`.
   *
   * Optional. Omitted or `null` both mean the agent does not advertise support.
   * Supplying `{}` means the agent supports listing sessions.
   */
  list?: EmptyObject | null;
  /**
   * Whether the agent supports `session/delete`.
   *
   * Optional. Omitted or `null` both mean the agent does not advertise support.
   * Supplying `{}` means the agent supports deleting sessions from `session/list`.
   */
  delete?: EmptyObject | null;
  /**
   * Whether the agent supports `additionalDirectories` on supported session lifecycle requests.
   *
   * Optional. Omitted or `null` both mean the agent does not advertise support.
   * Supplying `{}` means the agent supports `additionalDirectories` on
   * supported session lifecycle requests.
   *
   * Agents that also support `session/list` may return
   * `SessionInfo.additionalDirectories` to report the complete ordered
   * additional-root list associated with a listed session.
   */
  additionalDirectories?: EmptyObject | null;
  /**
   * Whether the agent supports `session/resume`.
   *
   * Optional. Omitted or `null` both mean the agent does not advertise support.
   * Supplying `{}` means the agent supports resuming sessions.
   */
  resume?: EmptyObject | null;
  /**
   * Whether the agent supports `session/close`.
   *
   * Optional. Omitted or `null` both mean the agent does not advertise support.
   * Supplying `{}` means the agent supports closing sessions.
   */
  close?: EmptyObject | null;
};

/**
 * Session configuration option capabilities supported by the client.
 */
export type SessionConfigOptionsCapabilities = {
  /**
   * Whether the client supports boolean session configuration options.
   *
   * Optional. Omitted or `null` both mean the client does not advertise support.
   * Supplying `{}` means agents may include `type: "boolean"` entries in
   * `configOptions`, and the client may send `session/set_config_option`
   * requests with `type: "boolean"` and a boolean `value`.
   */
  boolean?: EmptyObject | null;
};
