// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvVariable } from "./common.js";

/**
 * An HTTP header to set when making requests to the MCP server.
 */
export type HttpHeader = {
  /**
   * The name of the HTTP header.
   */
  name: string;
  /**
   * The value to set for the HTTP header.
   */
  value: string;
};

/**
 * Selects exactly one MCP transport configuration shape.
 */
export type McpServer =
  | { "type": "http" } & McpServerHttp
  | { "type": "sse" } & McpServerSse
  | McpServerStdio;

/**
 * HTTP transport configuration for MCP.
 */
export type McpServerHttp = {
  /**
   * Human-readable name identifying this MCP server.
   */
  name: string;
  /**
   * URL to the MCP server.
   */
  url: string;
  /**
   * HTTP headers to set when making requests to the MCP server.
   */
  headers: Array<HttpHeader>;
};

/**
 * SSE transport configuration for MCP.
 */
export type McpServerSse = {
  /**
   * Human-readable name identifying this MCP server.
   */
  name: string;
  /**
   * URL to the MCP server.
   */
  url: string;
  /**
   * HTTP headers to set when making requests to the MCP server.
   */
  headers: Array<HttpHeader>;
};

/**
 * Stdio transport configuration for MCP.
 */
export type McpServerStdio = {
  /**
   * Human-readable name identifying this MCP server.
   */
  name: string;
  /**
   * Absolute path to the MCP server executable.
   */
  command: string;
  /**
   * Command-line arguments to pass to the MCP server.
   */
  args: Array<string>;
  /**
   * Environment variables to set when launching the MCP server.
   */
  env: Array<EnvVariable>;
};
