// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./common.js";
import type { SessionUpdate } from "./session.js";

/**
 * Notification to cancel ongoing operations for a session.
 */
export type CancelNotification = {
  /**
   * The ID of the session to cancel operations for.
   */
  sessionId: SessionId;
};

/**
 * Notification containing a session update from the agent.
 *
 * Used to stream real-time progress and results during prompt processing.
 */
export type SessionNotification = {
  /**
   * The ID of the session this update pertains to.
   */
  sessionId: SessionId;
  /**
   * The actual update content.
   */
  update: SessionUpdate;
};
