// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./common.js";
import type { ToolCallUpdate } from "./tool_call.js";

/**
 * An option presented to the user when requesting permission.
 */
export type PermissionOption = {
  /**
   * Unique identifier for this permission option.
   */
  optionId: PermissionOptionId;
  /**
   * Human-readable label to display to the user.
   */
  name: string;
  /**
   * Hint about the nature of this permission option.
   */
  kind: PermissionOptionKind;
};

/**
 * Unique identifier for a permission option.
 */
export type PermissionOptionId = string;

/**
 * The type of permission option being presented to the user.
 *
 * Helps clients choose appropriate icons and UI treatment.
 */
export type PermissionOptionKind =
  | "allow_once"
  | "allow_always"
  | "reject_once"
  | "reject_always";

/**
 * The outcome of a permission request.
 */
export type RequestPermissionOutcome =
  | { "outcome": "cancelled" }
  | { "outcome": "selected" } & SelectedPermissionOutcome;

/**
 * Request for user permission to execute a tool call.
 *
 * Sent when the agent needs authorization before performing a sensitive operation.
 */
export type RequestPermissionRequest = {
  /**
   * The session ID for this request.
   */
  sessionId: SessionId;
  /**
   * Details about the tool call requiring permission.
   */
  toolCall: ToolCallUpdate;
  /**
   * Available permission options for the user to choose from.
   */
  options: Array<PermissionOption>;
};

/**
 * Response to a permission request.
 */
export type RequestPermissionResponse = {
  /**
   * The user's decision on the permission request.
   */
  outcome: RequestPermissionOutcome;
};

/**
 * The user selected one of the provided options.
 */
export type SelectedPermissionOutcome = {
  /**
   * The ID of the option the user selected.
   */
  optionId: PermissionOptionId;
};
