// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlock } from "./content.js";
import type { ToolCall, ToolCallUpdate } from "./tool_calls.js";

/**
 * Streams one chunk of an agent-authored message.
 */
export type AgentMessageChunk = {
  messageId: string | null;
  content: ContentBlock;
};

/**
 * Reports cumulative monetary cost for a session.
 */
export type Cost = { amount: number; currency: string };

/**
 * Represents one item in an agent plan.
 */
export type PlanEntry = {
  content: string;
  priority: PlanEntryPriority;
  status: PlanEntryStatus;
};

/**
 * Describes the urgency of a plan entry.
 */
export type PlanEntryPriority = "high" | "medium" | "low";

/**
 * Describes the lifecycle of a plan entry.
 */
export type PlanEntryStatus = "pending" | "in_progress" | "completed";

/**
 * Replaces the current agent plan shown by the client.
 */
export type PlanUpdate = { entries: Array<PlanEntry> };

/**
 * Carries the internal parameters of the `session/cancel` notification.
 */
export type SessionCancelNotification = { sessionId: string };

/**
 * Carries the internal parameters of `session/prompt`.
 */
export type SessionPromptRequest = {
  sessionId: string;
  prompt: Array<ContentBlock>;
};

/**
 * Carries the internal result of `session/prompt`.
 */
export type SessionPromptResponse = { stopReason: StopReason };

/**
 * Represents the session updates shown across the prompt-turn and tool-call flows.
 */
export type SessionUpdate =
  | { "sessionUpdate": "plan" } & PlanUpdate
  | { "sessionUpdate": "agent_message_chunk" } & AgentMessageChunk
  | { "sessionUpdate": "tool_call" } & ToolCall
  | { "sessionUpdate": "tool_call_update" } & ToolCallUpdate
  | { "sessionUpdate": "usage_update" } & UsageUpdate;

/**
 * Carries the internal parameters of a `session/update` notification.
 */
export type SessionUpdateNotification = {
  sessionId: string;
  update: SessionUpdate;
};

/**
 * Explains why an agent stopped processing a prompt turn.
 */
export type StopReason =
  | "end_turn"
  | "max_tokens"
  | "max_turn_requests"
  | "refusal"
  | "cancelled";

/**
 * Reports current context usage and optional cumulative cost.
 */
export type UsageUpdate = { used: number; size: number; cost: Cost | null };
