// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the session removed by `session/delete`.
 */
export type SessionDeleteRequest = { sessionId: string };

/**
 * Represents the empty successful result of `session/delete`.
 */
export type SessionDeleteResponse = Record<symbol, never>;
