// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./common.js";
import type { ContentBlock } from "./content.js";
import type { McpServer } from "./mcp.js";
import type { Plan } from "./plan.js";
import type { SessionConfigOption } from "./session_config_options.js";
import type { SessionModeId, SessionModeState } from "./session_mode.js";
import type { AvailableCommand } from "./slash_command.js";
import type { ToolCall, ToolCallUpdate } from "./tool_call.js";

/**
 * Available commands are ready or have changed
 */
export type AvailableCommandsUpdate = {
  /**
   * Commands the agent can execute
   */
  availableCommands: Array<AvailableCommand>;
};

/**
 * Request parameters for closing an active session.
 *
 * If supported, the agent **must** cancel any ongoing work related to the session
 * (treat it as if `session/cancel` was called) and then free up any resources
 * associated with the session.
 *
 * Only available if the Agent supports the `sessionCapabilities.close` capability.
 */
export type CloseSessionRequest = {
  /**
   * The ID of the session to close.
   */
  sessionId: SessionId;
};

/**
 * Response from closing a session.
 */
export type CloseSessionResponse = Record<symbol, never>;

/**
 * Session configuration options have been updated.
 */
export type ConfigOptionUpdate = {
  /**
   * The full set of configuration options and their current values.
   */
  configOptions: Array<SessionConfigOption>;
};

/**
 * A streamed item of content
 */
export type ContentChunk = {
  /**
   * A single item of content
   */
  content: ContentBlock;
  /**
   * A unique identifier for the message this chunk belongs to.
   *
   * All chunks belonging to the same message share the same `messageId`.
   * A change in `messageId` indicates a new message has started.
   */
  messageId?: MessageId | null;
};

/**
 * Cost information for a session.
 */
export type Cost = {
  /**
   * Total cumulative cost for session.
   */
  amount: number;
  /**
   * ISO 4217 currency code (e.g., "USD", "EUR").
   */
  currency: string;
};

/**
 * The current mode of the session has changed
 */
export type CurrentModeUpdate = {
  /**
   * The ID of the current mode
   */
  currentModeId: SessionModeId;
};

/**
 * Request parameters for deleting an existing session from `session/list`.
 *
 * Only available if the Agent supports the `sessionCapabilities.delete` capability.
 */
export type DeleteSessionRequest = {
  /**
   * The ID of the session to delete.
   */
  sessionId: SessionId;
};

/**
 * Response from deleting a session.
 */
export type DeleteSessionResponse = Record<symbol, never>;

/**
 * Request parameters for listing existing sessions.
 *
 * Only available if the Agent supports the `sessionCapabilities.list` capability.
 */
export type ListSessionsRequest = {
  /**
   * Filter sessions by working directory. Must be an absolute path.
   */
  cwd?: string | null;
  /**
   * Opaque cursor token from a previous response's nextCursor field for cursor-based pagination
   */
  cursor?: string | null;
};

/**
 * Response from listing sessions.
 */
export type ListSessionsResponse = {
  /**
   * Array of session information objects
   */
  sessions: Array<SessionInfo>;
  /**
   * Opaque cursor token. If present, pass this in the next request's cursor parameter
   * to fetch the next page. If absent, there are no more results.
   */
  nextCursor?: string | null;
};

/**
 * Request parameters for loading an existing session.
 *
 * Only available if the Agent supports the `loadSession` capability.
 *
 * See protocol docs: [Loading Sessions](https://agentclientprotocol.com/protocol/session-setup#loading-sessions)
 */
export type LoadSessionRequest = {
  /**
   * List of MCP servers to connect to for this session.
   */
  mcpServers: Array<McpServer>;
  /**
   * The working directory for this session. Must be an absolute path.
   */
  cwd: string;
  /**
   * Additional workspace roots to activate for this session. Each path must be absolute.
   *
   * When omitted or empty, no additional roots are activated. When non-empty,
   * this is the complete resulting additional-root list for the loaded
   * session. It may differ from any previously used or reported list as long as
   * the request `cwd` matches the session's `cwd`.
   */
  additionalDirectories?: Array<string>;
  /**
   * The ID of the session to load.
   */
  sessionId: SessionId;
};

/**
 * Response from loading an existing session.
 */
export type LoadSessionResponse = {
  /**
   * Initial mode state if supported by the Agent
   */
  modes?: SessionModeState | null;
  /**
   * Initial session configuration options if supported by the Agent.
   */
  configOptions?: Array<SessionConfigOption> | null;
};

/**
 * Unique identifier for a message within a session.
 */
export type MessageId = string;

/**
 * Request parameters for creating a new session.
 */
export type NewSessionRequest = {
  /**
   * The working directory for this session. Must be an absolute path.
   */
  cwd: string;
  /**
   * Additional workspace roots for this session. Each path must be absolute.
   *
   * These expand the session's filesystem scope without changing `cwd`, which
   * remains the base for relative paths. When omitted or empty, no
   * additional roots are activated for the new session.
   */
  additionalDirectories?: Array<string>;
  /**
   * List of MCP (Model Context Protocol) servers the agent should connect to.
   */
  mcpServers: Array<McpServer>;
};

/**
 * Response from creating a new session.
 */
export type NewSessionResponse = {
  /**
   * Unique identifier for the created session.
   *
   * Used in all subsequent requests for this conversation.
   */
  sessionId: SessionId;
  /**
   * Initial mode state if supported by the Agent
   */
  modes?: SessionModeState | null;
  /**
   * Initial session configuration options if supported by the Agent.
   */
  configOptions?: Array<SessionConfigOption> | null;
};

/**
 * Request parameters for resuming an existing session.
 *
 * Resumes an existing session without returning previous messages (unlike `session/load`).
 * This is useful for agents that can resume sessions but don't implement full session loading.
 *
 * Only available if the Agent supports the `sessionCapabilities.resume` capability.
 */
export type ResumeSessionRequest = {
  /**
   * The ID of the session to resume.
   */
  sessionId: SessionId;
  /**
   * The working directory for this session. Must be an absolute path.
   */
  cwd: string;
  /**
   * Additional workspace roots to activate for this session. Each path must be absolute.
   *
   * When omitted or empty, no additional roots are activated. When non-empty,
   * this is the complete resulting additional-root list for the resumed
   * session. It may differ from any previously used or reported list as long as
   * the request `cwd` matches the session's `cwd`.
   */
  additionalDirectories?: Array<string>;
  /**
   * List of MCP servers to connect to for this session.
   */
  mcpServers?: Array<McpServer>;
};

/**
 * Response from resuming an existing session.
 */
export type ResumeSessionResponse = {
  /**
   * Initial mode state if supported by the Agent
   */
  modes?: SessionModeState | null;
  /**
   * Initial session configuration options if supported by the Agent.
   */
  configOptions?: Array<SessionConfigOption> | null;
};

/**
 * Information about a session returned by session/list
 */
export type SessionInfo = {
  /**
   * Unique identifier for the session
   */
  sessionId: SessionId;
  /**
   * The working directory for this session. Must be an absolute path.
   */
  cwd: string;
  /**
   * Additional workspace roots reported for this session. Each path must be absolute.
   *
   * When present, this is the complete ordered additional-root list reported
   * by the Agent. Omitted and empty values are equivalent: the response
   * reports no additional roots.
   */
  additionalDirectories?: Array<string>;
  /**
   * Human-readable title for the session
   */
  title?: string | null;
  /**
   * ISO 8601 timestamp of last activity
   */
  updatedAt?: string | null;
};

/**
 * Update to session metadata. All fields are optional to support partial updates.
 *
 * Agents send this notification to update session information like title or custom metadata.
 * This allows clients to display dynamic session names and track session state changes.
 */
export type SessionInfoUpdate = {
  /**
   * Human-readable title for the session. Set to null to clear.
   */
  title?: string | null;
  /**
   * ISO 8601 timestamp of last activity. Set to null to clear.
   */
  updatedAt?: string | null;
};

/**
 * Different types of updates that can be sent during session processing.
 *
 * These updates provide real-time feedback about the agent's progress.
 */
export type SessionUpdate =
  | { "sessionUpdate": "user_message_chunk" } & ContentChunk
  | { "sessionUpdate": "agent_message_chunk" } & ContentChunk
  | { "sessionUpdate": "agent_thought_chunk" } & ContentChunk
  | { "sessionUpdate": "tool_call" } & ToolCall
  | { "sessionUpdate": "tool_call_update" } & ToolCallUpdate
  | { "sessionUpdate": "plan" } & Plan
  | { "sessionUpdate": "available_commands_update" } & AvailableCommandsUpdate
  | { "sessionUpdate": "current_mode_update" } & CurrentModeUpdate
  | { "sessionUpdate": "config_option_update" } & ConfigOptionUpdate
  | { "sessionUpdate": "session_info_update" } & SessionInfoUpdate
  | { "sessionUpdate": "usage_update" } & UsageUpdate;

/**
 * Context window and cost update for a session.
 */
export type UsageUpdate = {
  /**
   * Tokens currently in context.
   */
  used: bigint;
  /**
   * Total context window size in tokens.
   */
  size: bigint;
  /**
   * Cumulative session cost (optional).
   */
  cost?: Cost | null;
};
