// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./common.js";

/**
 * A boolean on/off toggle session configuration option payload.
 */
export type SessionConfigBoolean = {
  /**
   * The current value of the boolean option.
   */
  currentValue: boolean;
};

/**
 * Unique identifier for a session configuration option value group.
 */
export type SessionConfigGroupId = string;

/**
 * Unique identifier for a session configuration option.
 */
export type SessionConfigId = string;

/**
 * Type-specific session configuration option payload.
 */
export type SessionConfigKind =
  | { "type": "select" } & SessionConfigSelect
  | { "type": "boolean" } & SessionConfigBoolean;

/**
 * A session configuration option selector and its current state.
 */
export type SessionConfigOption =
  & {
    /**
     * Unique identifier for the configuration option.
     */
    id: SessionConfigId;
    /**
     * Human-readable label for the option.
     */
    name: string;
    /**
     * Optional description for the Client to display to the user.
     */
    description?: string | null;
    /**
     * Optional semantic category for this option (UX only).
     */
    category?: SessionConfigOptionCategory | null;
  }
  & (
    | { "type": "select" } & SessionConfigSelect
    | { "type": "boolean" } & SessionConfigBoolean
  );

/**
 * Semantic category for a session configuration option.
 *
 * This is intended to help Clients distinguish broadly common selectors (e.g. model selector vs
 * session mode selector vs thought/reasoning level) for UX purposes (keyboard shortcuts, icons,
 * placement). It MUST NOT be required for correctness. Clients MUST handle missing or unknown
 * categories gracefully.
 *
 * Category names beginning with `_` are free for custom use, like other ACP extension methods.
 * Category names that do not begin with `_` are reserved for the ACP spec.
 */
export type SessionConfigOptionCategory =
  | "mode"
  | "model"
  | "model_config"
  | "thought_level"
  | string;

/**
 * The value to set for a session configuration option.
 *
 * The `type` field acts as the discriminator in the serialized JSON form.
 * When no `type` is present, the value is treated as a [`SessionConfigValueId`]
 * via the [`ValueId`](Self::ValueId) fallback variant.
 *
 * The `type` discriminator describes the *shape* of the value, not the option
 * kind. For example every option kind that picks from a list of ids
 * (`select`, `radio`, …) would use [`ValueId`](Self::ValueId), while a
 * future freeform text option would get its own variant.
 */
export type SessionConfigOptionValue = {
  "type": "boolean";
  /**
   * The boolean value.
   */
  value: boolean;
} | SessionConfigOptionValueId;

/**
 * Wraps a value-id payload so the untagged `ValueId` variant of
 * [`SessionConfigOptionValue`] serializes without a `type` discriminator on the wire.
 */
export type SessionConfigOptionValueId = {
  /**
   * The value ID.
   */
  value: SessionConfigValueId;
};

/**
 * A single-value selector (dropdown) session configuration option payload.
 */
export type SessionConfigSelect = {
  /**
   * The currently selected value.
   */
  currentValue: SessionConfigValueId;
  /**
   * The set of selectable options.
   */
  options: SessionConfigSelectOptions;
};

/**
 * A group of possible values for a session configuration option.
 */
export type SessionConfigSelectGroup = {
  /**
   * Unique identifier for this group.
   */
  group: SessionConfigGroupId;
  /**
   * Human-readable label for this group.
   */
  name: string;
  /**
   * The set of option values in this group.
   */
  options: Array<SessionConfigSelectOption>;
};

/**
 * A possible value for a session configuration option.
 */
export type SessionConfigSelectOption = {
  /**
   * Unique identifier for this option value.
   */
  value: SessionConfigValueId;
  /**
   * Human-readable label for this option value.
   */
  name: string;
  /**
   * Optional description for this option value.
   */
  description?: string | null;
};

/**
 * Possible values for a session configuration option.
 */
export type SessionConfigSelectOptions =
  | Array<SessionConfigSelectOption>
  | Array<SessionConfigSelectGroup>;

/**
 * Unique identifier for a session configuration option value.
 */
export type SessionConfigValueId = string;

/**
 * Request parameters for setting a session configuration option.
 */
export type SetSessionConfigOptionRequest =
  & {
    /**
     * The ID of the session to set the configuration option for.
     */
    sessionId: SessionId;
    /**
     * The ID of the configuration option to set.
     */
    configId: SessionConfigId;
  }
  & ({
    "type": "boolean";
    /**
     * The boolean value.
     */
    value: boolean;
  } | SessionConfigOptionValueId);

/**
 * Response to `session/set_config_option` method.
 */
export type SetSessionConfigOptionResponse = {
  /**
   * The full set of configuration options and their current values.
   */
  configOptions: Array<SessionConfigOption>;
};
