// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./common.js";

/**
 * A mode the agent can operate in.
 */
export type SessionMode = {
  /**
   * Stable identifier used to refer to this protocol object in later messages.
   */
  id: SessionModeId;
  /**
   * Human-readable name shown for this protocol object.
   */
  name: string;
  /**
   * Optional human-readable details shown with this protocol object.
   */
  description?: string | null;
};

/**
 * Unique identifier for a Session Mode.
 */
export type SessionModeId = string;

/**
 * The set of modes and the one currently active.
 */
export type SessionModeState = {
  /**
   * The current mode the Agent is in.
   */
  currentModeId: SessionModeId;
  /**
   * The set of modes that the Agent can operate in
   */
  availableModes: Array<SessionMode>;
};

/**
 * Request parameters for setting a session mode.
 */
export type SetSessionModeRequest = {
  /**
   * The ID of the session to set the mode for.
   */
  sessionId: SessionId;
  /**
   * The ID of the mode to set.
   */
  modeId: SessionModeId;
};

/**
 * Response to `session/set_mode` method.
 */
export type SetSessionModeResponse = Record<symbol, never>;
