// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user-invokable slash command.
 */
export type AvailableCommand = {
  /**
   * Command name (e.g., `create_plan`, `research_codebase`).
   */
  name: string;
  /**
   * Human-readable description of what the command does.
   */
  description: string;
  /**
   * Input for the command if required
   */
  input?: AvailableCommandInput | null;
};

/**
 * Input details for a slash command.
 */
export type AvailableCommandInput = UnstructuredCommandInput;

/**
 * All text that was typed after the command name is provided as input.
 */
export type UnstructuredCommandInput = {
  /**
   * A hint to display when the input hasn't been provided yet
   */
  hint: string;
};
