// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvVariable, SessionId } from "./common.js";

/**
 * Request to create a new terminal and execute a command.
 */
export type CreateTerminalRequest = {
  /**
   * The session ID for this request.
   */
  sessionId: SessionId;
  /**
   * The command to execute.
   */
  command: string;
  /**
   * Array of command arguments.
   */
  args?: Array<string>;
  /**
   * Environment variables for the command.
   */
  env?: Array<EnvVariable>;
  /**
   * Working directory for the command. Must be an absolute path.
   */
  cwd?: string | null;
  /**
   * Maximum number of output bytes to retain.
   *
   * When the limit is exceeded, the Client truncates from the beginning of the output
   * to stay within the limit.
   *
   * The Client MUST ensure truncation happens at a character boundary to maintain valid
   * string output, even if this means the retained output is slightly less than the
   * specified limit.
   */
  outputByteLimit?: bigint | null;
};

/**
 * Response containing the ID of the created terminal.
 */
export type CreateTerminalResponse = {
  /**
   * The unique identifier for the created terminal.
   */
  terminalId: TerminalId;
};

/**
 * Request to kill a terminal without releasing it.
 */
export type KillTerminalRequest = {
  /**
   * The session ID for this request.
   */
  sessionId: SessionId;
  /**
   * The ID of the terminal to kill.
   */
  terminalId: TerminalId;
};

/**
 * Response to `terminal/kill` method
 */
export type KillTerminalResponse = Record<symbol, never>;

/**
 * Request to release a terminal and free its resources.
 */
export type ReleaseTerminalRequest = {
  /**
   * The session ID for this request.
   */
  sessionId: SessionId;
  /**
   * The ID of the terminal to release.
   */
  terminalId: TerminalId;
};

/**
 * Response to terminal/release method
 */
export type ReleaseTerminalResponse = Record<symbol, never>;

/**
 * Exit status of a terminal command.
 */
export type TerminalExitStatus = {
  /**
   * The process exit code (may be null if terminated by signal).
   */
  exitCode?: number | null;
  /**
   * The signal that terminated the process (may be null if exited normally).
   */
  signal?: string | null;
};

/**
 * Typed identifier used for terminal values on the wire.
 */
export type TerminalId = string;

/**
 * Request to get the current output and status of a terminal.
 */
export type TerminalOutputRequest = {
  /**
   * The session ID for this request.
   */
  sessionId: SessionId;
  /**
   * The ID of the terminal to get output from.
   */
  terminalId: TerminalId;
};

/**
 * Response containing the terminal output and exit status.
 */
export type TerminalOutputResponse = {
  /**
   * The terminal output captured so far.
   */
  output: string;
  /**
   * Whether the output was truncated due to byte limits.
   */
  truncated: boolean;
  /**
   * Exit status if the command has completed.
   */
  exitStatus?: TerminalExitStatus | null;
};

/**
 * Request to wait for a terminal command to exit.
 */
export type WaitForTerminalExitRequest = {
  /**
   * The session ID for this request.
   */
  sessionId: SessionId;
  /**
   * The ID of the terminal to wait for.
   */
  terminalId: TerminalId;
};

/**
 * Response containing the exit status of a terminal command.
 */
export type WaitForTerminalExitResponse = {
  /**
   * The process exit code (may be null if terminated by signal).
   */
  exitCode?: number | null;
  /**
   * The signal that terminated the process (may be null if exited normally).
   */
  signal?: string | null;
};
