// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlock } from "./content.js";
import type { TerminalId } from "./terminal.js";

/**
 * Standard content block (text, images, resources).
 */
export type Content = {
  /**
   * The actual content block.
   */
  content: ContentBlock;
};

/**
 * A diff representing file modifications.
 *
 * Shows changes to files in a format suitable for display in the client UI.
 */
export type Diff = {
  /**
   * The absolute file path being modified.
   */
  path: string;
  /**
   * The original content (None for new files).
   */
  oldText?: string | null;
  /**
   * The new content after modification.
   */
  newText: string;
};

/**
 * Embed a terminal created with `terminal/create` by its id.
 *
 * The terminal must be added before calling `terminal/release`.
 */
export type Terminal = {
  /**
   * Identifier of the terminal instance to embed in the content stream.
   */
  terminalId: TerminalId;
};

/**
 * Represents a tool call that the language model has requested.
 *
 * Tool calls are actions that the agent executes on behalf of the language model,
 * such as reading files, executing code, or fetching data from external sources.
 */
export type ToolCall = {
  /**
   * Unique identifier for this tool call within the session.
   */
  toolCallId: ToolCallId;
  /**
   * Human-readable title describing what the tool is doing.
   */
  title: string;
  /**
   * The category of tool being invoked.
   * Helps clients choose appropriate icons and UI treatment.
   */
  kind?: ToolKind;
  /**
   * Current execution status of the tool call.
   */
  status?: ToolCallStatus;
  /**
   * Content produced by the tool call.
   */
  content?: Array<ToolCallContent>;
  /**
   * File locations affected by this tool call.
   * Enables "follow-along" features in clients.
   */
  locations?: Array<ToolCallLocation>;
  /**
   * Raw input parameters sent to the tool.
   */
  rawInput?: unknown;
  /**
   * Raw output returned by the tool.
   */
  rawOutput?: unknown;
};

/**
 * Content produced by a tool call.
 *
 * Tool calls can produce different types of content including
 * standard content blocks (text, images) or file diffs.
 */
export type ToolCallContent =
  | { "type": "content" } & Content
  | { "type": "diff" } & Diff
  | { "type": "terminal" } & Terminal;

/**
 * Unique identifier for a tool call within a session.
 */
export type ToolCallId = string;

/**
 * A file location being accessed or modified by a tool.
 *
 * Enables clients to implement "follow-along" features that track
 * which files the agent is working with in real-time.
 */
export type ToolCallLocation = {
  /**
   * The absolute file path being accessed or modified.
   */
  path: string;
  /**
   * Optional line number within the file.
   */
  line?: number | null;
};

/**
 * Execution status of a tool call.
 *
 * Tool calls progress through different statuses during their lifecycle.
 */
export type ToolCallStatus = "pending" | "in_progress" | "completed" | "failed";

/**
 * An update to an existing tool call.
 *
 * Used to report progress and results as tools execute. All fields except
 * the tool call ID are optional - only changed fields need to be included.
 */
export type ToolCallUpdate = {
  /**
   * The ID of the tool call being updated.
   */
  toolCallId: ToolCallId;
  /**
   * Update the tool kind.
   */
  kind?: ToolKind | null;
  /**
   * Update the execution status.
   */
  status?: ToolCallStatus | null;
  /**
   * Update the human-readable title.
   */
  title?: string | null;
  /**
   * Replace the content collection.
   */
  content?: Array<ToolCallContent> | null;
  /**
   * Replace the locations collection.
   */
  locations?: Array<ToolCallLocation> | null;
  /**
   * Update the raw input.
   */
  rawInput?: unknown;
  /**
   * Update the raw output.
   */
  rawOutput?: unknown;
};

/**
 * Optional fields that can be updated in a tool call.
 *
 * All fields are optional - only include the ones being changed.
 * Collections (content, locations) are overwritten, not extended.
 */
export type ToolCallUpdateFields = {
  /**
   * Update the tool kind.
   */
  kind?: ToolKind | null;
  /**
   * Update the execution status.
   */
  status?: ToolCallStatus | null;
  /**
   * Update the human-readable title.
   */
  title?: string | null;
  /**
   * Replace the content collection.
   */
  content?: Array<ToolCallContent> | null;
  /**
   * Replace the locations collection.
   */
  locations?: Array<ToolCallLocation> | null;
  /**
   * Update the raw input.
   */
  rawInput?: unknown;
  /**
   * Update the raw output.
   */
  rawOutput?: unknown;
};

/**
 * Categories of tools that can be invoked.
 *
 * Tool kinds help clients choose appropriate icons and optimize how they
 * display tool execution progress.
 */
export type ToolKind =
  | "read"
  | "edit"
  | "delete"
  | "move"
  | "search"
  | "execute"
  | "think"
  | "fetch"
  | "switch_mode"
  | "other";
