// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlock } from "./content.js";

/**
 * Wraps a standard content block produced by a tool.
 */
export type ContentToolCallContent = { content: ContentBlock };

/**
 * Describes a file modification produced by a tool.
 */
export type DiffToolCallContent = {
  path: string;
  oldText?: string | null;
  newText: string;
};

/**
 * Defines one user-selectable permission choice.
 */
export type PermissionOption = {
  optionId: string;
  name: string;
  kind: PermissionOptionKind;
};

/**
 * Hints how a permission choice should be presented and remembered.
 */
export type PermissionOptionKind =
  | "allow_once"
  | "allow_always"
  | "reject_once"
  | "reject_always";

/**
 * Carries the internal parameters of `session/request_permission`.
 */
export type SessionRequestPermissionRequest = {
  sessionId: string;
  toolCall: ToolCallUpdate;
  options: Array<PermissionOption>;
};

/**
 * Carries the internal result of `session/request_permission`.
 */
export type SessionRequestPermissionResponse = {
  outcome: ToolPermissionOutcome;
};

/**
 * References a live terminal produced by a tool.
 */
export type TerminalToolCallContent = { terminalId: string };

/**
 * Announces a new tool call and its initial presentation state.
 */
export type ToolCall = {
  toolCallId: string;
  title: string;
  kind: ToolKind;
  status: ToolCallStatus;
  content?: Array<ToolCallContent> | null;
  locations?: Array<ToolCallLocation> | null;
  rawInput?: unknown;
  rawOutput?: unknown;
};

/**
 * Represents content that a tool call can expose to the client.
 */
export type ToolCallContent =
  | { "type": "content" } & ContentToolCallContent
  | { "type": "diff" } & DiffToolCallContent
  | { "type": "terminal" } & TerminalToolCallContent;

/**
 * Points to a file location affected by a tool call.
 */
export type ToolCallLocation = { path: string; line?: number | null };

/**
 * Describes the execution lifecycle of a tool call.
 */
export type ToolCallStatus = "pending" | "in_progress" | "completed" | "failed";

/**
 * Carries a partial update to an existing tool call.
 */
export type ToolCallUpdate = {
  toolCallId: string;
  title?: string | null;
  kind?: ToolKind | null;
  status?: ToolCallStatus | null;
  content?: Array<ToolCallContent> | null;
  locations?: Array<ToolCallLocation> | null;
  rawInput?: unknown;
  rawOutput?: unknown;
};

/**
 * Categorizes a tool call for client presentation.
 */
export type ToolKind =
  | "read"
  | "edit"
  | "delete"
  | "move"
  | "search"
  | "execute"
  | "think"
  | "fetch"
  | "other";

/**
 * Models the two legal permission outcomes without optional-field ambiguity.
 */
export type ToolPermissionOutcome = { "outcome": "cancelled" } | {
  "outcome": "selected";
  optionId: string;
};
