//! Static SDK wiring derived from the operation catalog and ts-rs-owned DTO files.

use super::{GENERATED_FILE_HEADER, write_generated_file};
use crate::frontend::{FrontendEndpoint, FrontendResponseMode};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

/// Emits the client factory and DTO barrel without adding another type-to-file registry.
pub(super) fn export(
    directory: &Path,
    endpoints: &[FrontendEndpoint],
) -> Result<(), Box<dyn std::error::Error>> {
    let mut dto_modules = BTreeSet::new();
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let path = entry.path();
        if entry.file_type()?.is_file()
            && path.extension().is_some_and(|extension| extension == "ts")
            && fs::read_to_string(&path)?.starts_with("// This file was generated by [ts-rs]")
        {
            dto_modules.insert(
                entry
                    .file_name()
                    .into_string()
                    .map_err(|name| format!("generated DTO module name is not UTF-8: {name:?}"))?,
            );
        }
    }
    let mut barrel = String::from(GENERATED_FILE_HEADER);
    for module in dto_modules {
        barrel.push_str(&format!("export * from \"./{module}\";\n"));
    }
    write_generated_file(&directory.join("dto.generated.ts"), &barrel)?;
    write_generated_file(
        &directory.join("client.generated.ts"),
        &render_client(endpoints)?,
    )
}

/// Validates catalog uniqueness before generating a statically checked client object.
fn render_client(endpoints: &[FrontendEndpoint]) -> Result<String, String> {
    let mut operations = BTreeSet::new();
    let mut namespaces = BTreeMap::<_, BTreeMap<_, _>>::new();
    for endpoint in endpoints {
        if !operations.insert(endpoint.operation_name) {
            return Err(format!("duplicate operation: {}", endpoint.operation_name));
        }
        if namespaces
            .entry(endpoint.namespace)
            .or_default()
            .insert(endpoint.member_name, endpoint)
            .is_some()
        {
            return Err(format!(
                "duplicate client member: {}.{}",
                endpoint.namespace, endpoint.member_name
            ));
        }
    }

    let executors = endpoints
        .iter()
        .map(|endpoint| match endpoint.response_mode {
            FrontendResponseMode::Unary => "executeOperation",
            FrontendResponseMode::Stream => "executeStreamOperation",
        })
        .chain(std::iter::once("type ContractsClient"))
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect::<Vec<_>>()
        .join(", ");
    let mut source = format!(
        "{GENERATED_FILE_HEADER}\
import {{ {executors} }} from \"./client-runtime.ts\";\n\
import type {{ ContractTransport }} from \"./transport.ts\";\n\n\
/** Binds every catalog member to the injected transport. */\n\
export function createContractsClient(transport: ContractTransport): ContractsClient {{\n\
  return {{\n"
    );
    for (namespace, members) in namespaces {
        source.push_str(&format!("    {namespace}: {{\n"));
        for (member, endpoint) in members {
            let executor = match endpoint.response_mode {
                FrontendResponseMode::Unary => "executeOperation",
                FrontendResponseMode::Stream => "executeStreamOperation",
            };
            let operation = endpoint.operation_name;
            source.push_str(&format!(
                "      {member}: (request, options) => {executor}(\"{operation}\", request, transport, options),\n"
            ));
        }
        source.push_str("    },\n");
    }
    source.push_str("  };\n}\n");
    Ok(source)
}

#[cfg(test)]
mod tests {
    use super::render_client;
    use crate::frontend::{FrontendEndpoint, FrontendResponseMode};
    use pretty_assertions::assert_eq;

    const UNARY: FrontendEndpoint = FrontendEndpoint {
        operation_name: "readFixture",
        namespace: "fixture",
        member_name: "read",
        request_type: "FixtureRequest",
        response_type: "FixtureResponse",
        response_mode: FrontendResponseMode::Unary,
    };

    const STREAM: FrontendEndpoint = FrontendEndpoint {
        operation_name: "followFixture",
        member_name: "follow",
        response_mode: FrontendResponseMode::Stream,
        ..UNARY
    };

    /// A previously unknown stream needs only its declaration, and removal leaves no stale member.
    #[test]
    fn adding_and_removing_operations_changes_only_the_generated_members() {
        let original = render_client(&[UNARY])
            .unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        let extended = render_client(&[UNARY, STREAM])
            .unwrap_or_else(|error| panic!("fixture operation failed: {error}"));
        let stream_line = "      follow: (request, options) => executeStreamOperation(\"followFixture\", request, transport, options),\n";
        assert_eq!(
            extended,
            original
                .replace(
                    "executeOperation, type",
                    "executeOperation, executeStreamOperation, type"
                )
                .replace(
                    "    fixture: {\n",
                    &format!("    fixture: {{\n{stream_line}")
                )
        );
        assert_eq!(
            render_client(&[STREAM, UNARY]),
            render_client(&[UNARY, STREAM])
        );
        assert_eq!(
            render_client(&[UNARY])
                .unwrap_or_else(|error| panic!("fixture operation failed: {error}")),
            original
        );
    }

    /// Duplicate declarations must fail generation instead of shadowing client behavior.
    #[test]
    fn rejects_duplicate_operations_and_members() {
        assert_eq!(
            render_client(&[UNARY, UNARY]),
            Err("duplicate operation: readFixture".to_string())
        );
        assert_eq!(
            render_client(&[
                UNARY,
                FrontendEndpoint {
                    member_name: "read",
                    ..STREAM
                }
            ]),
            Err("duplicate client member: fixture.read".to_string())
        );
    }
}
