[package]
name = "ora-node-db"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
ora-node-protocol = { workspace = true }
ora-process-protocol.workspace = true
rusqlite = { workspace = true, features = ["bundled"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
pretty_assertions.workspace = true
tempfile.workspace = true
