// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
export const JSON_RPC_VERSION = "2.0" as const;
export const JSON_RPC_FRAME_TYPE = 1;
export const MAX_FRAME_LENGTH = 16777216;
export const INVALID_PARAMS = -32602;
export const METHOD_NOT_FOUND = -32601;
export const INTERNAL_ERROR = -32603;
export const AGENT_NOT_INSTALLED = -32001;
export const AGENT_UNUSABLE = -32002;
export const SUPPORTED_ACP_VERSION = 1;
export const SKILL_DIRECTORY_V1 = "ora/skill-directory.v1" as const;
export const OPENCODE_MCP_CONFIG_V1 = "ora/opencode-mcp-config.v1" as const;
export const CLAUDE_MCP_CONFIG_V1 = "ora/claude-mcp-config.v1" as const;
export const MAX_STORAGE_FILE_BYTES = 8388608;

export const PLUGIN_METHODS = {
  register: "ora/register",
  shutdown: "ora/shutdown",
} as const;

export const AGENT_METHODS = {
  start: "agent/start",
  stop: "agent/stop",
  listModels: "agent/list_models",
  acp: "agent/acp",
} as const;

export const EFFECT_METHODS = {
  coordinate: "effect/coordinate",
  reactivate: "effect/reactivate",
  verifyReady: "effect/verify_ready",
} as const;

export const STORAGE_METHODS = {
  list: "ora/storage/list",
  read: "ora/storage/read",
  write: "ora/storage/write",
  remove: "ora/storage/remove",
} as const;

export const CHILD_PROCESS_METHODS = {
  spawn: "ora/childprocess/spawn",
  write: "ora/childprocess/write",
  closeStdin: "ora/childprocess/close_stdin",
  kill: "ora/childprocess/kill",
} as const;

export const CHILD_PROCESS_NOTIFICATIONS = {
  stdout: "ora/childprocess/stdout",
  stderr: "ora/childprocess/stderr",
  exit: "ora/childprocess/exit",
} as const;
