// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects the runtime barrier required before Ora mutates one declared Resource.
 */
export type PluginEffectCoordination =
  | "uninterrupted"
  | "quiesce_before_mutation";

/**
 * One Workspace-relative Effect Resource included in immutable plugin registration.
 */
export type PluginEffectResource = {
  workspaceRelativePath: string;
  materializationFormat: string;
  coordination: PluginEffectCoordination;
};

/**
 * Wire payload of the `ora/register` notification.
 */
export type PluginRegistrationParams = {
  methods: Array<string>;
  emits: Array<string>;
  effectResources?: Array<PluginEffectResource>;
  traceProviders?: Array<PluginTraceProvider>;
};

/**
 * A safe trace file template below one host-owned filesystem root.
 */
export type PluginTraceLocator = {
  root: PluginTraceRoot;
  directory: string;
  fileNameTemplate: string;
  recursive: boolean;
};

/**
 * One host-resolved trace source declared by a provider plugin.
 */
export type PluginTraceProvider = {
  providerId: string;
  format: string;
  locator: PluginTraceLocator;
};

/**
 * Filesystem roots a provider may name without learning a concrete host path.
 */
export type PluginTraceRoot = "home" | "workspace";
