[package]
name = "ora-process-guardian"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc = { workspace = true }
ora-process-runtime = { workspace = true }
tokio = { workspace = true, features = ["rt", "signal", "net"] }

[dev-dependencies]
ora-process-protocol = { workspace = true }
ora-process-client = { workspace = true }
ora-utils = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
libc = { workspace = true }
rusqlite = { workspace = true, features = ["bundled"] }
